"""Fetchable views of the two large control documents, for the outside reviewer.

`docs/prompts/audit-2026-09-25-outside.md` (about 210 KB on 2026-09-26) and
`docs/prompts/backlog-2026-09-25.md` (about 235 KB) are past the reviewer's fetch limit: on
2026-09-26 it retrieved the audit file with Parts 22 and 23 as empty headings although both were
at HEAD. The canonical files stay whole; this script writes one file per audit Part and one file
per matrix series under `docs/prompts/views/`, regenerated by the orchestrator before every
record commit. The views are copies, never edited by hand; a divergence means the script was not
run.

Run from the repository root: `python tools/docs/split_prompt_views.py`.
"""
from __future__ import annotations

import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PROMPTS = ROOT / "docs" / "prompts"
VIEWS = PROMPTS / "views"
AUDIT = PROMPTS / "audit-2026-09-25-outside.md"
BACKLOG = PROMPTS / "backlog-2026-09-25.md"

HEADING = re.compile(r"^===== (.+?) =====\s*$", re.M)


def slug(title: str) -> str:
    m = re.match(r"PART (\d+)", title)
    if m:
        return f"part-{int(m.group(1)):02d}"
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:60]


def split_audit() -> list[tuple[str, str]]:
    text = AUDIT.read_text(encoding="utf-8")
    marks = list(HEADING.finditer(text))
    out: list[tuple[str, str]] = []
    if marks:
        out.append(("preamble", text[: marks[0].start()]))
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(text)
        out.append((slug(m.group(1)), text[m.start():end]))
    return out


def split_backlog() -> tuple[str, dict[str, list[str]]]:
    lines = BACKLOG.read_text(encoding="utf-8").splitlines()
    header_lines: list[str] = []
    rows: dict[str, list[str]] = {}
    table_head: list[str] = []
    for line in lines:
        m = re.match(r"^\| ([A-Z]+)\d+ \|", line)
        if m:
            rows.setdefault(m.group(1), []).append(line)
        elif line.startswith("| id |") or line.startswith("|---") or line.startswith("| ---"):
            if len(table_head) < 2:
                table_head.append(line)
        elif not rows:
            header_lines.append(line)
    head = "\n".join(header_lines).rstrip() + "\n\n" + "\n".join(table_head) + "\n"
    return head, rows


def main() -> None:
    if VIEWS.exists():
        shutil.rmtree(VIEWS)
    (VIEWS / "audit").mkdir(parents=True)
    (VIEWS / "backlog").mkdir(parents=True)
    index = ["# Fetchable views of the audit file and the matrix", "",
             "Copies for the outside reviewer's fetch limit, regenerated by `tools/docs/split_prompt_views.py` before every record commit. The canonical files are `../audit-2026-09-25-outside.md` and `../backlog-2026-09-25.md`; edit those, never these.", "",
             "## The audit file, one file per Part", ""]
    for name, body in split_audit():
        path = VIEWS / "audit" / f"{name}.md"
        path.write_text(body.strip("\n") + "\n", encoding="utf-8")
        first = body.strip().splitlines()[0][:110] if body.strip() else name
        index.append(f"- [{name}](audit/{name}.md) — {first}")
    head, rows = split_backlog()
    index += ["", "## The matrix, one file per series", ""]
    for series, lines in rows.items():
        path = VIEWS / "backlog" / f"{series}.md"
        path.write_text(head + "\n".join(lines) + "\n", encoding="utf-8")
        index.append(f"- [{series}](backlog/{series}.md) — {len(lines)} rows")
    (VIEWS / "README.md").write_text("\n".join(index) + "\n", encoding="utf-8")
    print(f"audit parts: {len(list((VIEWS / 'audit').glob('*.md')))}; series: {', '.join(f'{k} {len(v)}' for k, v in rows.items())}")


if __name__ == "__main__":
    main()
