"""
Writes what `difficulty.py` makes of the score fixtures, for the app to check against.

replan §4.4 puts a second implementation of the levelling model in the app, so
a score imported on the phone gets the same number as one the quarry found.
Two implementations of one formula drift; this is what stops them.

The fixture holds, per score, the features Python measured and the level it
reached. `app/tests/unit/difficulty.test.ts` parses the same files with OSMD,
computes its own features, and asserts the two levels agree within 0.2 stages.
It compares *levels* rather than features because the features are measured off
different representations — music21 keeps tie continuations as notes and the
app's ScoreModel merges them — and the agreement that matters is the one the
owner sees.

    py -3.11 tools\\content\\export_levelling_fixture.py
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import difficulty  # noqa: E402
from common import REPO_ROOT  # noqa: E402

FIXTURES = REPO_ROOT / "app" / "tests" / "fixtures" / "scores"
DEFAULT_OUT = REPO_ROOT / "app" / "tests" / "fixtures" / "levelling.json"

#: Only the hand-written edge cases and the generated exercises. The golden
#: directory is a different kind of fixture and some of it is deliberately
#: malformed, which is not what a levelling comparison is for.
SUBDIRS = ("edge", "generated")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    from music21 import converter

    model = difficulty.load_model()
    scores = []
    for sub in SUBDIRS:
        directory = FIXTURES / sub
        if not directory.is_dir():
            continue
        for path in sorted(directory.iterdir()):
            if path.suffix.lower() not in {".musicxml", ".xml", ".mxl"}:
                continue
            try:
                parsed = converter.parse(str(path))
            except Exception as cause:  # noqa: BLE001 - a fixture that will not parse is data
                print(f"  skip {path.name}: {cause}", file=sys.stderr)
                continue
            values = difficulty.features(parsed)
            estimate = difficulty.estimate(values, model)
            scores.append(
                {
                    "name": path.stem,
                    "dir": sub,
                    "features": {k: round(v, 6) for k, v in values.items()},
                    "level": estimate.level,
                    "source": estimate.source,
                }
            )

    args.out.write_text(
        json.dumps(
            {
                "_comment": [
                    "GENERATED by tools/content/export_levelling_fixture.py.",
                    "What difficulty.py measures on the score fixtures, so the TypeScript port",
                    "in app/src/score/difficulty.ts can be held to the same numbers (replan §4.4).",
                    "Re-run it whenever difficulty.py or level-model.json changes.",
                ],
                "modelFitted": bool(model.get("fitted")),
                "scores": scores,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"{len(scores)} score(s) -> {args.out}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
