#!/usr/bin/env python3
"""
Runs every registered measurement over every notated catalogue item and reports, per
characteristic, how much trustworthy evidence it produces on real scores (the progress
number, FABLE section 2 item 7).

Writes build/classifier/measurements.json (every item, every characteristic, value or
UNKNOWN with provenance; not committed) and docs/classifier/measurements/summary.md (per
characteristic: items measured, items UNKNOWN with the commonest reasons, value spread,
errors). The row count is asserted equal to the notated catalogue count.

    python tools/classifier/measure.py                 # all registered characteristics
    python tools/classifier/measure.py --only texture.  # ids starting with a prefix
    python tools/classifier/measure.py --limit 50      # the first 50 items (a trial, never a result)
"""
from __future__ import annotations

import argparse
import collections
import importlib
import json
import pkgutil
import sys
import time
import traceback
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import score as S  # noqa: E402

ROOT = S.ROOT
CATALOG = ROOT / "app/public/content/catalog.json"
OUT_JSON = ROOT / "build/classifier/measurements.json"
OUT_MD = ROOT / "docs/classifier/measurements/summary.md"
MODULE_DIRS = ("direct", "rules")


def load_modules() -> list[str]:
    names = []
    for d in MODULE_DIRS:
        pkg = Path(__file__).resolve().parent / d
        if not pkg.exists():
            continue
        for m in pkgutil.iter_modules([str(pkg)]):
            if not m.name.startswith("_"):
                importlib.import_module(f"{d}.{m.name}")
                names.append(f"{d}.{m.name}")
    return names


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only")
    ap.add_argument("--limit", type=int)
    a = ap.parse_args()
    modules = load_modules()
    ids = sorted(k for k in S.REGISTRY if not a.only or k.startswith(a.only))
    items = [i for i in json.loads(CATALOG.read_text(encoding="utf-8")) if i.get("file")]
    if a.limit:
        items = items[: a.limit]
    out, errors = {}, collections.Counter()
    t0 = time.time()
    for it in items:
        row = {}
        try:
            sc = S.load(it)
        except Exception as e:  # noqa: BLE001 - recorded per item
            out[it["id"]] = {"_load_error": f"{type(e).__name__}: {e}"[:200]}
            errors["_load"] += 1
            continue
        for cid in ids:
            try:
                row[cid] = S.REGISTRY[cid](sc).to_json()
            except Exception as e:  # noqa: BLE001
                row[cid] = {"error": f"{type(e).__name__}: {e}"[:200], "trace": traceback.format_exc(limit=2)[-300:]}
                errors[cid] += 1
        out[it["id"]] = row
    assert len(out) == len(items), "a catalogue item was skipped"
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(out), encoding="utf-8")
    lines = ["# Measurements on the catalogue", "",
             f"Generated by `tools/classifier/measure.py`; do not edit. {len(items)} notated items{' (a --limit trial, not a result)' if a.limit else ''}; "
             f"{errors['_load']} failed to load; modules: {', '.join(modules) or 'none'}; {time.time() - t0:.0f}s.", "",
             "| Characteristic | Measured | UNKNOWN | Errors | Commonest UNKNOWN reasons | Values (commonest) |", "| --- | --- | --- | --- | --- | --- |"]
    for cid in ids:
        vals = [r.get(cid) for r in out.values() if cid in r]
        known = [v for v in vals if v and "value" in v]
        unk = [v["unknown"] for v in vals if v and "unknown" in v]
        reasons = "; ".join(f"{r} ({n})" for r, n in collections.Counter(unk).most_common(2))
        spread = ", ".join(f"{json.dumps(v)[:30]} ({n})" for v, n in collections.Counter(json.dumps(k["value"]) for k in known).most_common(3))
        lines.append(f"| `{cid}` | {len(known)} | {len(unk)} | {errors[cid]} | {reasons.replace('|', '/') or '-'} | {spread.replace('|', '/') or '-'} |")
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{len(items)} items, {len(ids)} characteristics, {sum(errors.values())} errors -> {OUT_MD.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
