// Generated by build/u125/make-spec.mjs; the test is engine.spec.ts's U66
// case copied verbatim (lines 156-225), under CPU throttling.
import { expect, test } from '@playwright/test';
import { openDevScore } from '../../../tests/e2e/fixtures/devScore';

test.describe('Tempo mode end to end', () => {
  // U125_THROTTLE_AT=start (default): throttled from before the page loads.
  // U125_THROTTLE_AT=run: throttled from the harness's startRun on, so the
  // page's setup runs at full speed and the run itself is throttled; the
  // test's body is the same either way.
  // U125_LOG=1: the page's timers logged (as u66-diag.spec.ts does) and, for
  // a failed run, the log and the engine's events written to build/u125/diag/.
  test.afterEach(async ({ page }, info) => {
    if (!process.env.U125_LOG || info.status === info.expectedStatus) return;
    const dump = await page.evaluate(() => ({
      log: (window as unknown as { __u125?: unknown[] }).__u125 ?? [],
      events: window.__pianopathDevScore?.engineEvents() ?? [],
      notes: (window.__pianopathDevScore?.engineScore() as unknown as { notes?: unknown[] } | null)?.notes ?? [],
    }));
    const fs = await import('node:fs');
    fs.mkdirSync('build/u125/diag', { recursive: true });
    fs.writeFileSync(`build/u125/diag/verbatim-FAIL-${info.repeatEachIndex}.json`, JSON.stringify({ error: info.error?.message, ...dump }));
  });

  test.beforeEach(async ({ page }) => {
    if (process.env.U125_LOG) {
      await page.addInitScript(() => {
        const log: [string, number, number, string?][] = [];
        (window as unknown as { __u125: typeof log }).__u125 = log;
        const now = () => performance.now();
        let seenEv = 0;
        const ev = (): string => {
          const h = (window as unknown as { __pianopathDevScore?: { engineEvents?: () => { kind: string; step?: number }[] } }).__pianopathDevScore;
          const all = h?.engineEvents?.() ?? [];
          if (all.length < seenEv) seenEv = 0;
          const fresh = all.slice(seenEv).map((e) => e.kind + (e.step ?? '')).join(',');
          seenEv = all.length;
          return fresh;
        };
        const st = window.setTimeout.bind(window);
        window.setTimeout = ((fn: () => void, ms?: number, ...rest: unknown[]) => {
          const at = now();
          const d = ms ?? 0;
          return st(() => {
            if (d >= 50) log.push([`to${d}`, at + d, now()]);
            fn(...(rest as []));
            if (d >= 50) log.push([`to${d}:end`, at + d, now(), ev()]);
          }, ms);
        }) as typeof window.setTimeout;
        const si = window.setInterval.bind(window);
        window.setInterval = ((fn: () => void, ms?: number) =>
          si(() => {
            const t = now();
            fn();
            log.push(['iv', t, now(), ev()]);
          }, ms)) as typeof window.setInterval;
        const raf = window.requestAnimationFrame.bind(window);
        window.requestAnimationFrame = ((fn: FrameRequestCallback) =>
          raf((ts) => {
            const t = now();
            fn(ts);
            log.push(['raf', t, now(), ev()]);
          })) as typeof window.requestAnimationFrame;
      });
    }
    const rate = Number(process.env.U125_CPU_RATE ?? '1');
    if (rate <= 1) return;
    const cdp = await page.context().newCDPSession(page);
    if (process.env.U125_THROTTLE_AT !== 'run') {
      await cdp.send('Emulation.setCPUThrottlingRate', { rate });
      return;
    }
    await page.exposeBinding('__u125Throttle', () => cdp.send('Emulation.setCPUThrottlingRate', { rate }));
    await page.addInitScript(() => {
      const w = window as unknown as Record<string, unknown>;
      let handle: unknown;
      Object.defineProperty(window, '__pianopathDevScore', {
        configurable: true,
        get: () => handle,
        set: (v: { startRun?: (...a: unknown[]) => unknown } | undefined) => {
          if (v && typeof v.startRun === 'function') {
            const original = v.startRun;
            v.startRun = (...a: unknown[]) => {
              void (w.__u125Throttle as () => Promise<void>)();
              return original(...a);
            };
          }
          handle = v;
        },
      });
    });
  });

  test('a long task across the first note’s window: the note, stamped inside it, is judged in it (U66)', async ({
    page,
  }) => {
    // U66 (B1), on the page's real timers, as H0's `wall-stalled` probe ran
    // (`runs/H0/red-q39-browser-probe.txt`): the main thread kept busy for
    // 400 ms from about 90 ms after the replay connects. The first note is due
    // at 100 and its window closes at 150, so the note waits behind the long
    // task past its window's close and the harness's own tick, due first,
    // comes off the queue before it. 400 ms is longer than the note's
    // remaining tolerance and well short of the stamp-trust bound (a second):
    // the case the hold is for. The engine without it counted 1 hit, 1 miss and
    // 1 wrong note here.
    const dev = await openDevScore(page);
    await dev.load('tempo-change');
    await dev.startRun('tempo', { countInBars: 0, tempoPct: 130, toleranceMs: 150 });
    const run = await page.evaluate(
      async (script) => {
        const h = window.__pianopathDevScore;
        if (!h) throw new Error('dev score harness is not attached');
        const marks = { before: 0, after: 0, busyFrom: 0, busyTo: 0 };
        setTimeout(() => {
          marks.busyFrom = performance.now();
          while (performance.now() - marks.busyFrom < 400) {
            // the long task
          }
          marks.busyTo = performance.now();
        }, 90);
        // `replay` restarts the run and connects its source before it returns
        // its promise: the connect lies between these two readings.
        marks.before = performance.now();
        const replayed = h.replay(script);
        marks.after = performance.now();
        await replayed;
        // Read at once: the third note's window (bar 2) opens long after the
        // replay's tail, so this reading holds the first bar's judgement only.
        const score = h.engineScore() as
          | (ReturnType<typeof h.engineScore> & {
              notes: { midi: number; stepIndex: number | null; ok: boolean }[];
            })
          | null;
        return {
          marks,
          hits: score?.hits,
          wrong: score?.wrongNotesTotal,
          n: score?.timing.n,
          latePct: score?.timing.latePct,
          notes: score?.notes.map((n) => [n.midi, n.stepIndex, n.ok]),
          barOneMisses: (score?.hotSpots ?? []).filter((s) => s.measureIndex === 0).map((s) => s.misses),
        };
      },
      [
        { atMs: 100, midi: 60 },
        { atMs: 869, midi: 62 },
      ],
    );
    // The long task began before the first window closed (150 ms after the
    // connect) and ended after it.
    expect(run.marks.busyFrom - run.marks.before).toBeLessThan(150);
    expect(run.marks.busyTo - run.marks.after).toBeGreaterThan(150);
    expect(run.notes).toEqual([
      [60, 0, true],
      [62, 1, true],
    ]);
    expect(run.hits).toBe(2);
    expect(run.wrong).toBe(0);
    expect(run.barOneMisses.filter((m) => m > 0)).toEqual([]);
    expect(run.n).toBe(2);
    expect(run.latePct).toBe(100);
    await dev.stopRun();
  });
});
