"""
E50's doc rows, applied as text splices (each old text must occur once; line endings kept as the file has them;
idempotent: a splice whose new text is already there is skipped). Output: prints what it did.
"""
from __future__ import annotations

import sys
from pathlib import Path

W = Path(__file__).resolve().parents[4]

SPLICES = [
    ("docs/02-curriculum.md",
     "  run's summary or a project stored against a dated file names the same material after the date\n"
     ">   was removed; nothing stored is rewritten, and D2's record stays exact bytes.\n",
     "  run's summary or a project stored against a dated file names the same material after the date\n"
     ">   was removed; nothing stored is rewritten, and D2's record stays exact bytes. Since E50 the list\n"
     ">   also carries the old identity of a reviewed musical repair (`tools/content/repaired_identities.json`:\n"
     ">   the seven PDMX scores whose printed \"= N\" became their tempo), so a learner who met the old file\n"
     ">   has met the piece; the old run stays a run at its recorded tempo, and no standard reads the list.\n"),
    ("docs/03-content-pipeline.md",
     "  resolves and never loses to a launch measurement.\n",
     "  resolves and never loses to a launch measurement.\n"
     "- **The build's tempo printed as text** (E50): the content converter reads the same mark before it\n"
     "  inserts its default (`convert.tempo_printed_as_text`, in `normalise`'s default branch, E32's rule\n"
     "  ported: `TEXT_MARK` verbatim, SMuFL's metronome glyphs, the metre's beat in x/4 or x/2 where the\n"
     "  glyph is missing, 20–400) where it stands before any note sounds (X31a's opening rule), and writes it\n"
     "  as the score's `<metronome>` with a `<sound tempo>` in quarters, the words removed; a mark after a\n"
     "  note has sounded stays as words and the conversion's warnings name it. The seven bundled PDMX\n"
     "  scores that printed `= N` were re-converted with it and their `pdmx.json` rows respliced\n"
     "  (`tempoDefaulted: false`), so their tempo fact is authored, via the upload. One rule, two\n"
     "  definitions (the door's TypeScript, the converter's Python); one shared definition is the later\n"
     "  ingestion seam.\n"),
    ("docs/03-content-pipeline.md",
     "  drops them. A stored\n",
     "  drops them. Beside them, since E50, the old identity each reviewed musical repair names\n"
     "  (`tools/content/repaired_identities.json`, generated by the repaired-identities generator kept beside\n"
     "  Entry 163, `docs/prompts/runs/E50/`, never edited by hand): an entry of the table above, related to the\n"
     "  repaired file, recorded for a row only where the row's file with the repair's restore lines put back,\n"
     "  then the old date, zipped under the old system, is the old file's bytes. A stored\n"),
    ("docs/08-test-map.md",
     "- `formerIdentity.test.ts` — a stored row names the same material after the converter stopped writing a date (E50a),",
     "- `repairedTempoLineage.test.ts` — the seven PDMX scores whose printed tempo became their mark (E50), from the committed relation (`tools/content/repaired_identities.json`), `pdmx.json` and E50a's table: one relation per row, from E50a's recorded old file to the row's `convertedSha256`; a run of the old file met, played, under the piece's id and another id, a hearing of it familiarity, a project kept against it the piece's project, and none of it without the relation; and the boundary: `meetsStandard` over the old runs the same with and without the relation (at 60 % of its own base a run meets no full-tempo standard), a rung counting no old run under another id, every rung reading the same with and without it, and the old run never rewritten, its base the defaulted 96.\n"
     "- `formerIdentity.test.ts` — a stored row names the same material after the converter stopped writing a date (E50a),"),
    ("docs/08-test-map.md",
     "- `test_convert.py` — `convert.py` against a sample of every input format; the grand-staff merge.\n",
     "- `test_convert.py` — `convert.py` against a sample of every input format; the grand-staff merge. Since E50 (`TestTheTempoPrintedAsText`), an opening metronome mark printed as text read before the default: the Wabash shape (`= 120` boxed in MuseJazz, 4/4) a quarter, one `<metronome>`, `<sound tempo=\"120\">`, the words gone, the warning; the door's four glyph cases (a quarter glyph, an eighth sounding at half its number, a dotted quarter, no glyph in 2/2 a half); a mark after a bar of rests read; not read, the default and the words kept: no glyph in 6/8, `Allegro`, `bars 1 = 12`, a mark after a note has sounded (named in the warnings), a file with a `<metronome>` of its own; and a forced tempo replacing the printed one.\n"),
    ("docs/08-test-map.md",
     "; and a changed note new material.\n",
     "; and a changed note new material. Since E50 (`TestRepairedIdentities`), a reviewed repair names the old file it rebuilds (its restore lines and date put back under its system) and nothing else: not for a restore line the old file did not hold or the new one does not, no restore, another day, machine or repaired file, a line held twice, or an old identity E50a's table did not record for that file; and the seven committed relations re-prove on the committed scores, each `to` the row's `convertedSha256`, no `pdmx.json` row naming a former identity.\n"),
    ("docs/08-test-map.md",
     "never a current identity of any row, and none on a cut, a generated row or a dated committed copy.",
     "never a current identity of any row, and none on a cut, a generated row or a dated committed copy; since E50 also each reviewed repair's old identity on its row, the repaired rows untagged `tempo-defaulted`, and an excerpt approved on a parent's old bytes still stale, its `parentSha256` the parent's current file."),
]


def main() -> int:
    for rel, old, new in SPLICES:
        path = W / rel
        raw = path.read_bytes()
        crlf = b"\r\n" in raw
        text = raw.decode("utf-8").replace("\r\n", "\n")
        if new in text:
            print(f"{rel}: already applied: {new[:60]!r}")
            continue
        if text.count(old) != 1:
            print(f"{rel}: STOP, the old text occurs {text.count(old)} times: {old[:60]!r}")
            return 1
        text = text.replace(old, new, 1)
        path.write_bytes((text.replace("\n", "\r\n") if crlf else text).encode("utf-8"))
        print(f"{rel}: applied ({'CRLF' if crlf else 'LF'}): {new[:60]!r}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
