"""Insert one status paragraph under each section heading of area-1A.md (idempotent: skips a section that has one)."""
import re
from pathlib import Path

A = Path(__file__).resolve().parents[2] / "docs/classifier/rules/area-1A.md"
V = "`docs/classifier/audits/rules-1A/validation.md`"
S = {
"item.format": ("failing", "Re-run on the 15 named items and the catalogue [measured: build/val/r_format.py, survey_format.py, survey_lead.py, survey_last.py, corpus_lyr.py]. Right on every named example (So Danço Samba is now a lead sheet; Joyful and Holy, Holy, Holy are 4(b) candidates; Kreutzer, the violin gavotte and the trombone solo are flagged; bwv66.6 fires rule 2's chorale bullet). Wrong: `song.jazz.kenny-dorham-blue-bossa.pdmx`, a lead sheet whose last four bars harmonise the melody (11.8% two-note onsets), comes out *piano score (one-hand part)* because of the under-10% chord-onset share; the UNKNOWN-layout rule (lower staff silent in half the bars) fires on 27 generated items (the rootless ii-V-I and montuno families), where a generated layout must be code's. Passed on as candidates: Duvernoy op. 176 no. 11 meets both parts of 4(b) (one onset per quarter in every quarter), and the title word \"Flute\" flags `song.folk.the-flute-tune-soulpride-remix.pdmx`. Thresholds' bases are in " + V + " section 2."),
"notation.staves": ("validated", "Re-run on the 6 named items and the catalogue [measured: build/val/r_format.py, survey_a.py]: every answer as stated, the two clave items unpitched."),
"prereq.hand-assignment": ("uncertain", "Re-run on the 9 named items and the catalogue [measured: build/val/r_format.py, survey_a.py]: every named positive and near-miss as stated, and the flag counts reproduce (cross-staff 29 and 18, collisions 4 and 4, hand words 10 and 2, reach 43 and 59; generated none, widest one-staff chord 14). What remains: flag 1 over-flags on PDMX and its refinement is not run; no bracketed hand word exists in the catalogue, so that branch is untested."),
"texture.melody-location": ("failing", "Re-run with the guard over score.py and texture.py's per-hand bar sets on the named items and 60 random two-staff PDMX files [measured: build/val/r_melody.py]. The guard turns the Fantaisie-Impromptu bar 4 and Mariage d'amour bars 1 and 2 into UNKNOWN, and the named positives and near-misses come out as stated. Wrong: the Fantaisie-Impromptu bar 1 (held G♯ octaves) and bar 3 (the left-hand arpeggio, whose first onset is an octave, so `texture.broken-chord` does not fire) are still named a left-hand melody by rule 1: the guard works only where a pattern rule fires. Coverage now: 619 of 3,447 sampled bars (18.0%)."),
"notation.clefs": ("validated", "Re-run on the 6 named items and the catalogue [measured: build/val/r_format.py, survey_a.py]: treble on staff 2 and bass on a one-staff part flagged, the soprano clef flagged, the percussion staff not read as bass."),
"notation.clef-change": ("validated", "Re-run on the 4 named items [measured: build/val/r_format.py]: Asturias inside bars, Beethoven Anh. 5 no. 2 at bar lines only, Ballade 4 130 changes; the counterexample, a same-clef restatement, occurs in 50 catalogue files (Asturias 2) and none is counted [measured: survey_a.py]."),
"pitch.ledger": ("uncertain", "Re-run on the 7 named items [measured: build/val/r_ledger.py]: the geometry reproduces every example, and El Choclo and the 4-octave C scale fall beyond the limit. What remains: the limit of 6 lines is open, because 97 real items (many NIFC Chopin files, none of the 116 NIFC files carrying an `<octave-shift>`) reach 6 or more lines as well as the 154 generated ones [measured: survey_ledger.py, nifc_oct.py]."),
"mark.ottava": ("uncertain", "Re-run on the 6 named items [measured: build/val/r_ledger.py]: kinds, closed, unclosed and empty spans and ottava words as stated; S4 against music21 on all 93 files with a shift: 81 agree with the exclusive stop, 21 with an inclusive one [measured: ottava_m21.py]. What remains: the extent agrees with a second reader, never with a printed page."),
"notation.keys": ("validated", "Re-run on the 4 named items and the catalogue [measured: build/val/r_format.py, survey_a.py]: first signatures and changes as stated; the per-staff and non-traditional branches have no instance."),
"key.signature-exercised": ("uncertain", "Re-run on the 4 named items [measured: build/val/r_acc.py]: Ballade 4 now 2,393 exercised and 158 restated (2,551 together, the old count); the D minor arpeggio and Itsy Bitsy Spider never exercised. Never exercised, recounted: 100 generated, 4 PDMX, 2 other [measured: survey_acc.py]. What remains: \"accidental shown\" comes from section 12's model, which fails against the render, so a signature-restating accidental that OSMD draws can be counted as exercised."),
"pitch.chromatic": ("validated", "Re-run by spelling on 10 items with the existing key helper [measured: build/val/r_chrom.py]: Asturias 80 chromatic and 106 minor-raised (the G♭ and F♭ now chromatic), Ballade 4 1,086 and 490, Bach Aria 0 and 18; harmonic and melodic minor scales give minor-raised only; blue notes count chromatic. It depends on `key.tonic-mode` (area 1.B)."),
"reading.accidental-kinds": ("failing", "Rendered with OSMD 2.1.2 under jsdom and compared note by note [measured: build/val/osmd_acc.cjs, osmd_compare.py]. The named items agree, including the check's blues-scale example. Wrong: on a random 30 items, 147 notes in 8 files that the rule calls \"in the file, not shown\" are drawn (76 are not), for example `exercise.chromatic.d.1oct.right` bar 2, the second C♯5. In 2.1.2 a file accidental on a note equal to the in-bar record is printed unless the position is in OSMD's list of positions altered against the key, and each check removes the position from that list; an emulation of that logic matched the render on every matched note of 28 of the 30 files [measured: osmd_emul.py]. Catalogue by the emulation: of the accidentals the rule calls not shown, OSMD draws 839 of 1,054 PDMX, 290 of 954 generated, 8,868 of 15,484 other [measured: survey_osmd.py]."),
"reading.accidental-churn": ("validated", "Re-run on the 6 items [measured: build/val/r_acc.py]: the chromatic scale, Muse (24), Ballade 4 (44) and Nocturne op. 9 no. 2 (29) give events; the single cancellation of the A blues scale and Silent Night give none."),
"reading.visual-density": ("uncertain", "Re-run on the 4 named items [measured: build/val/r_acc.py]: dense and sparse as stated. What remains: its accidental count inherits section 12's failing model, its ledger count the open limit."),
"reading.unusual-notation": ("uncertain", "Re-run on the 7 named items and the catalogue [measured: build/val/r_misc.py, nested.py, survey_misc.py]: cue notes, cross-staff beams, slash noteheads and the three unclosed brackets as stated. What remains: the number test splits the old 13 files into 10 unclosed and 3 nested (`song.classical.chopin-ballade-1` bar 179, the Fantaisie-Impromptu PDMX bar 72, `song.classical.debussy-clair-de-lune` bars 19 and 23), so \"none\" below does not hold, and whether they are true nesting is unverified; the time-modification test is undefined among the catalogue's 83 ratios."),
"reading.pitch-entropy": ("validated", "Re-run by an independent implementation on 5 items [measured: build/val/r_misc.py]: the page's values reproduce (5.42, 5.46, 1.0, 1.66, 1.19)."),
"reading.redundancy": ("validated", "Re-run by an independent LZ76 on 4 items [measured: build/val/r_misc.py]: the page's shares reproduce (0.013, 0.047, 0.53, 0.54)."),
"notation.turn-opportunity": ("uncertain", "Re-run on the 4 named items [measured: build/val/r_misc.py]: the rest spans are as stated (a whole bar in BWV 924 and the Inno; none in the Cello Suite and Away in a Manger). What remains: no \"long enough\" answer, its threshold open."),
"mark.fingering": ("validated", "Re-run on 6 items and the catalogue [measured: build/val/r_misc.py, survey_misc.py]: printed digits, substitutions, stacked chord fingerings, digit words as candidates and Kreutzer's item-level UNKNOWN as stated; fingering `0` occurs in no other catalogue file. Its title-word input (item.format rule 6) carries one false flag (the Flute Tune)."),
"notation.lyrics": ("uncertain", "Run on music21's corpus and three synthetic streams [measured: build/val/corpus_lyr.py]: the two lead sheets class as words. What remains: no real lyric held; and a synthetic counting stream \"1 e & a\" whose \"a\" falls on an A and \"e\" on an E classes as words once the alignment step moves them (counting 6 of 8, under 80%)."),
"notation.chord-symbols": ("failing", "Re-run on 8 items and the catalogue [measured: build/val/r_misc.py, r_melody.py, survey_misc.py]: de-duplication, slash chords, N.C. and text candidates as stated. Wrong: step 3 on its own example `exercise.montuno.a.2note.son-3-2`: `texture.melody-location` rule 1 settles the montuno's only sounding staff as the melody, no texture pattern fires, and the family contract (`tools/content/family_contracts.json`, \"a right-hand montuno of chord tones on the clave's strokes\") states no role, so all four symbols come out *over a melody line*."),
"harmony.figured-bass": ("uncertain", "Re-run on the 2 named items and the catalogue [measured: build/val/r_misc.py, survey_misc.py]: no `<figured-bass>`; candidates in 18 items, every one seen a number that is not a figure, all to the agent. What remains: no positive held."),
"mark.repeat": ("failing", "The unroller was written to the specification and run [measured: build/val/r_repeat.py, survey_repeat.py]: the Romance 80 (music21 64), the Haydn 194 (music21 956). Wrong: the Beethoven bagatelle op. 119 no. 3 comes out 133; by its structure it plays 115, music21's count, because the jump list has no rule for two coda signs without \"To Coda\" words (the first sign is the jump point). With that convention added it gives 115, and `song.folk.down-by-the-riverside.pdmx.2` 78, as music21."),
"notation.reading-aids": ("uncertain", "Re-run on the 5 named items and the catalogue [measured: build/val/r_misc.py, survey_misc.py, fing_share.py]: rule 2 fires on the Chopin waltz (0.954) and on nothing else; rule 4 on the easy Twinkle. What remains: the 0.9 finger share splits sibling arrangements (Ode to Joy 0.893 and 0.895 below, 0.916 above); counting, notehead text and shape notes have no instance."),
"notation.slash-rhythm": ("validated", "Re-run on the 4 named items [measured: build/val/r_misc.py]: beat slashes in So Danço Samba (bars 1 to 7) and Blues Riff in C, none in the near-misses; the rhythmic-slash branch has no instance."),
"integrity.notation-sanity": ("failing", "Re-run on 9 items [measured: build/val/r_sanity.py, survey_acc.py, nested.py, survey_ledger.py]: kinds 1, 2, 3 and 5 as stated on their examples (OSMD draws the blues scale's missing flat itself); kind 4 holds 10 files, not 13. Wrong: test 2b flags correct spellings: every harmonic-minor scale's augmented second (`exercise.scale.a-harmonic-minor.1oct.similar.both.2`, F–G♯), the chromatic scale's augmented unisons (`exercise.chromatic.d.1oct.right`, 10), and the E–D♭ augmented second of F minor in Bach's Invention 9."),
}
t = A.read_text(encoding="utf8")
n = 0
for cid, (st, ev) in S.items():
    pat = re.compile(r"^(## \d+\. " + re.escape(cid) + r"\n\n)(?!\*\*Status)", re.M)
    para = f"**Status (validation, 2026-10-08): {st}.** {ev} One line in {V}.\n\n"
    t, k = pat.subn(lambda m: m.group(1) + para, t)
    n += k
A.write_text(t, encoding="utf8")
print("inserted", n)
