// Generated by tools/content/preflight_chains.py from docs/chains/A7b.1.yaml: a journey SKELETON (class 6).
// Not an acceptance journey: it carries no `acceptance-ability` marker. Placed in app/tests/e2e/ it would run
// with the helpers below; a test.fixme line marks a step no template could make.
import { expect, test, type Page } from '@playwright/test';
import { installMidiMock, type MidiMock } from './fixtures/midiMock';
import { playInTime } from './fixtures/playInTime';

const RUNG = "jazz.6";
const screen = (page: Page) => page.locator('section[data-screen="score"]');
type Run = { step: number; expected: number[]; bar: number; paused: boolean } | null;
type Hooked = Window & { __pianopath?: { scoreRun?: () => Run } };
const run = (page: Page): Promise<Run> => page.evaluate(() => (window as Hooked).__pianopath?.scoreRun?.() ?? null);
async function toLesson(page: Page, rung = RUNG): Promise<void> {
  const done = page.locator('#summary-done');
  if (await done.isVisible().catch(() => false)) await done.tap();
  await page.evaluate((r) => { window.location.hash = `#/lesson/${r}`; }, rung);
  await expect(page.locator('#lesson-text')).toBeVisible({ timeout: 30_000 });
}
async function countsLine(page: Page): Promise<string> {
  await toLesson(page);
  return ((await page.locator('#lesson-counts summary').textContent()) ?? '').trim();
}
async function openRow(page: Page, title: string, rung = RUNG): Promise<void> {
  await toLesson(page, rung);
  await page.getByRole('button', { name: `Open ${title}`, exact: true }).tap();
  await expect(page).toHaveURL(/#\/score\//, { timeout: 30_000 });
  await expect(page.locator('#score-stage')).toHaveAttribute('data-settled', 'true', { timeout: 60_000 });
}
async function menu(page: Page, open: boolean): Promise<void> {
  const sheet = page.locator('#score-more-sheet');
  if ((await sheet.isVisible()) === open) return;
  await page.locator(open ? '#score-more' : '#score-more-sheet-close').tap();
}
async function setMode(page: Page, mode: 'wait' | 'tempo' | 'listen'): Promise<void> {
  await page.locator('#score-mode').selectOption(mode);
  await expect(screen(page)).toHaveAttribute('data-mode', mode);
}
async function setHand(page: Page, hand: 'L' | 'R' | 'both'): Promise<void> {
  await page.locator(`#score-hands-${hand}`).tap();
}
async function setToggle(page: Page, id: string, on: boolean): Promise<void> {
  await menu(page, true);
  const toggle = page.locator(`#${id}`);
  if (((await toggle.textContent()) ?? '').trim() !== (on ? 'On' : 'Off')) await toggle.tap();
  await expect(toggle).toHaveText(on ? 'On' : 'Off');
  await menu(page, false);
}
async function setTempo(page: Page, pct: number): Promise<void> {
  await page.locator('#score-tempo-label').tap();
  await page.locator('#score-tempo').fill(String(pct));
  await page.locator('#score-tempo-sheet-close').tap();
}
async function loopBars(page: Page, from: number, to: number): Promise<void> {
  // The double-tap on the first bar and then the last (LB1); a bar off the page is played to first.
  test.fixme(true, `loop ${from}-${to}: reuse the hand-written journey's loopBars`);
}
async function hearIt(page: Page): Promise<void> {
  await page.locator('#score-hear').tap();
  await expect(screen(page)).toHaveAttribute('data-hearing', 'true', { timeout: 15_000 });
}
async function playToSummary(page: Page): Promise<void> {
  await page.locator('#score-play').tap();
  await playInTime(page, 'midi', 240_000);
  await expect(page.locator('#score-summary')).toBeVisible({ timeout: 180_000 });
}
async function waitToSummary(page: Page, midi: MidiMock): Promise<void> {
  await page.locator('#score-play').tap();
  for (let i = 0; i < 2_000 && !(await page.locator('#score-summary').isVisible()); i += 1) {
    const now = await run(page);
    if (!now) break;
    for (const note of now.expected) await midi.noteOn(note, 78);
    for (const note of now.expected) await midi.noteOff(note);
    await page.waitForTimeout(60);
  }
}

test("A7b.1: the journey derived from the record", async ({ page }) => {
  test.setTimeout(90 * 60_000);
  const midi = await installMidiMock(page, { permission: 'granted' });
  void midi; // the input is attached; no Wait for me step strikes it
  // Route: Plan -> the tracks sheet -> jazz on -> Stage 6 -> jazz.6.
  await page.goto('/#/plan');
  await page.locator('#plan-tracks-open').tap();
  const chip = page.locator("#plan-track-jazz");
  if ((await chip.getAttribute('aria-pressed')) !== 'true') await chip.tap();
  await page.locator('#plan-tracks-sheet-close').tap();
  const stage = page.locator(".list-row[data-stage=\"6\"]");
  if ((await stage.getAttribute('data-open')) !== 'true') await stage.tap();
  await page.locator(`.list-row[data-lesson="${RUNG}"]`).tap();
  await expect(page.locator('#lesson-exercises .list-row')).toHaveCount(8);
  await expect(page.locator('#lesson-songs .list-row')).toHaveCount(7);

  // record step 1: lesson
  await test.step("step 1", async () => {
    await toLesson(page);
  });

  // record step 2: fixme
  await test.step("step 2", async () => {
    test.fixme(true, "no journey template for the tool 'Free play, standalone' on content/lessons/jazz.6.md (no catalogue item: a Lab build or a lesson file)");
  });

  // record step 3: fixme; open 'Ear drill — seventh-chord qualities'
  await test.step("step 3", async () => {
    test.fixme(true, "no journey template for the tool 'Ear drills'");
  });

  // record step 4: fixme; open 'Minor ii-V-i with shell voicings'
  await test.step("step 4", async () => {
    test.fixme(true, "no journey template for the tool 'Reading and theory drills'");
  });

  // record step 5: fixme
  await test.step("step 5", async () => {
    test.fixme(true, "no journey template for the tool 'Hear it' on app/src/engine/sightReading.ts (no catalogue item: a Lab build or a lesson file)");
  });

  // record step 6: fixme
  await test.step("step 6", async () => {
    test.fixme(true, "no journey template for the tool 'Read it' on app/src/engine/sightReading.ts (no catalogue item: a Lab build or a lesson file)");
  });

  // record step 7: fixme
  await test.step("step 7", async () => {
    test.fixme(true, "no journey template for the tool 'Read it' on app/src/engine/sightReading.ts (no catalogue item: a Lab build or a lesson file)");
  });

  // record step 8: fixme
  await test.step("step 8", async () => {
    test.fixme(true, "no journey template for the tool 'Play the tune' on app/src/engine/sightReading.ts (no catalogue item: a Lab build or a lesson file)");
  });

  // record step 9: tempo; open 'Blue Bossa'; mode tempo; counts unchanged
  await test.step("step 9", async () => {
    const before = await countsLine(page);
    await openRow(page, "Blue Bossa");
    await setMode(page, "tempo");
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 10: fixme; open 'Blue Bossa'
  await test.step("step 10", async () => {
    test.fixme(true, "no journey template for the tool 'Chord chart'");
  });

  // record step 11: fixme; open 'Blue Bossa'
  await test.step("step 11", async () => {
    test.fixme(true, "no journey template for the tool 'Chord chart'");
  });

  // record step 12: fixme; open 'Blue Bossa'
  await test.step("step 12", async () => {
    test.fixme(true, "no journey template for the tool 'Chord chart'");
  });

  // record step 13: fixme; open 'Blue Bossa'
  await test.step("step 13", async () => {
    test.fixme(true, "no journey template for the tool 'Chord chart'");
  });

  // record step 14: fixme; open 'Insensatez (How Insensitive)'
  await test.step("step 14", async () => {
    test.fixme(true, "no journey template for the tool 'Chord chart'");
  });

  // record step 15: fixme; open 'Insensatez (How Insensitive)'
  await test.step("step 15", async () => {
    test.fixme(true, "no journey template for the tool 'Chord chart'");
  });

  // record step 16: fixme; open 'Insensatez (How Insensitive)'
  await test.step("step 16", async () => {
    test.fixme(true, "no journey template for the tool 'Chord chart'");
  });

  // Completion: the rung reads complete on Plan.
  await page.evaluate(() => { window.location.hash = '#/plan'; });
  const row = page.locator(`.list-row[data-lesson="${RUNG}"]`);
  await expect(row.locator('.badge')).toContainText([/complete/i]);
});
