// Generated by tools/content/preflight_chains.py from docs/chains/A7c.1.yaml: a journey SKELETON (class 6).
// Not an acceptance journey: it carries no `acceptance-ability` marker. Placed in app/tests/e2e/ it would run
// with the helpers below; a test.fixme line marks a step no template could make.
import { expect, test, type Page } from '@playwright/test';
import { installMidiMock, type MidiMock } from './fixtures/midiMock';
import { playInTime } from './fixtures/playInTime';

const RUNG = "latin.4";
const screen = (page: Page) => page.locator('section[data-screen="score"]');
type Run = { step: number; expected: number[]; bar: number; paused: boolean } | null;
type Hooked = Window & { __pianopath?: { scoreRun?: () => Run } };
const run = (page: Page): Promise<Run> => page.evaluate(() => (window as Hooked).__pianopath?.scoreRun?.() ?? null);
async function toLesson(page: Page, rung = RUNG): Promise<void> {
  const done = page.locator('#summary-done');
  if (await done.isVisible().catch(() => false)) await done.tap();
  await page.evaluate((r) => { window.location.hash = `#/lesson/${r}`; }, rung);
  await expect(page.locator('#lesson-text')).toBeVisible({ timeout: 30_000 });
}
async function countsLine(page: Page): Promise<string> {
  await toLesson(page);
  return ((await page.locator('#lesson-counts summary').textContent()) ?? '').trim();
}
async function openRow(page: Page, title: string, rung = RUNG): Promise<void> {
  await toLesson(page, rung);
  await page.getByRole('button', { name: `Open ${title}`, exact: true }).tap();
  await expect(page).toHaveURL(/#\/score\//, { timeout: 30_000 });
  await expect(page.locator('#score-stage')).toHaveAttribute('data-settled', 'true', { timeout: 60_000 });
}
async function menu(page: Page, open: boolean): Promise<void> {
  const sheet = page.locator('#score-more-sheet');
  if ((await sheet.isVisible()) === open) return;
  await page.locator(open ? '#score-more' : '#score-more-sheet-close').tap();
}
async function setMode(page: Page, mode: 'wait' | 'tempo' | 'listen'): Promise<void> {
  await page.locator('#score-mode').selectOption(mode);
  await expect(screen(page)).toHaveAttribute('data-mode', mode);
}
async function setHand(page: Page, hand: 'L' | 'R' | 'both'): Promise<void> {
  await page.locator(`#score-hands-${hand}`).tap();
}
async function setToggle(page: Page, id: string, on: boolean): Promise<void> {
  await menu(page, true);
  const toggle = page.locator(`#${id}`);
  if (((await toggle.textContent()) ?? '').trim() !== (on ? 'On' : 'Off')) await toggle.tap();
  await expect(toggle).toHaveText(on ? 'On' : 'Off');
  await menu(page, false);
}
async function setTempo(page: Page, pct: number): Promise<void> {
  await page.locator('#score-tempo-label').tap();
  await page.locator('#score-tempo').fill(String(pct));
  await page.locator('#score-tempo-sheet-close').tap();
}
async function loopBars(page: Page, from: number, to: number): Promise<void> {
  // The double-tap on the first bar and then the last (LB1); a bar off the page is played to first.
  test.fixme(true, `loop ${from}-${to}: reuse the hand-written journey's loopBars`);
}
async function hearIt(page: Page): Promise<void> {
  await page.locator('#score-hear').tap();
  await expect(screen(page)).toHaveAttribute('data-hearing', 'true', { timeout: 15_000 });
}
async function playToSummary(page: Page): Promise<void> {
  await page.locator('#score-play').tap();
  await playInTime(page, 'midi', 240_000);
  await expect(page.locator('#score-summary')).toBeVisible({ timeout: 180_000 });
}
async function waitToSummary(page: Page, midi: MidiMock): Promise<void> {
  await page.locator('#score-play').tap();
  for (let i = 0; i < 2_000 && !(await page.locator('#score-summary').isVisible()); i += 1) {
    const now = await run(page);
    if (!now) break;
    for (const note of now.expected) await midi.noteOn(note, 78);
    for (const note of now.expected) await midi.noteOff(note);
    await page.waitForTimeout(60);
  }
}

test("A7c.1: the journey derived from the record", async ({ page }) => {
  test.setTimeout(90 * 60_000);
  const midi = await installMidiMock(page, { permission: 'granted' });
  // Route: Plan -> the tracks sheet -> latin on -> Stage 4 -> latin.4.
  await page.goto('/#/plan');
  await page.locator('#plan-tracks-open').tap();
  const chip = page.locator("#plan-track-latin");
  if ((await chip.getAttribute('aria-pressed')) !== 'true') await chip.tap();
  await page.locator('#plan-tracks-sheet-close').tap();
  const stage = page.locator(".list-row[data-stage=\"4\"]");
  if ((await stage.getAttribute('data-open')) !== 'true') await stage.tap();
  await page.locator(`.list-row[data-lesson="${RUNG}"]`).tap();
  await expect(page.locator('#lesson-exercises .list-row')).toHaveCount(7);
  await expect(page.locator('#lesson-songs .list-row')).toHaveCount(4);

  // record step 1: lesson
  await test.step("step 1", async () => {
    await toLesson(page);
  });

  // record step 2: hear; open 'Tresillo bass in C — three, three, two'; counts unchanged
  await test.step("step 2", async () => {
    const before = await countsLine(page);
    await openRow(page, "Tresillo bass in C — three, three, two");
    await hearIt(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 3: hear; open "L'amour est un oiseau rebelle, bars 1–12, left hand"; counts unchanged
  await test.step("step 3", async () => {
    const before = await countsLine(page);
    await openRow(page, "L'amour est un oiseau rebelle, bars 1–12, left hand");
    await hearIt(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 4: rhythm; open 'Tresillo bass in C — three, three, two'; mode tempo; Rhythm only on; counts unchanged
  await test.step("step 4", async () => {
    const before = await countsLine(page);
    await openRow(page, "Tresillo bass in C — three, three, two");
    await setMode(page, "tempo");
    await setToggle(page, 'score-rhythm', true);
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 5: rhythm; open "L'amour est un oiseau rebelle, bars 1–12, left hand"; mode tempo; hand L; Rhythm only on; counts unchanged
  await test.step("step 5", async () => {
    const before = await countsLine(page);
    await openRow(page, "L'amour est un oiseau rebelle, bars 1–12, left hand");
    await setMode(page, "tempo");
    await setHand(page, "L");
    await setToggle(page, 'score-rhythm', true);
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 6: rhythm; open 'Tresillo bass in C, in 2/4'; mode tempo; Rhythm only on; counts unchanged
  await test.step("step 6", async () => {
    const before = await countsLine(page);
    await openRow(page, "Tresillo bass in C, in 2/4");
    await setMode(page, "tempo");
    await setToggle(page, 'score-rhythm', true);
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 7: rhythm; open 'Habanera bass in C, in 2/4'; mode tempo; Rhythm only on; counts unchanged
  await test.step("step 7", async () => {
    const before = await countsLine(page);
    await openRow(page, "Habanera bass in C, in 2/4");
    await setMode(page, "tempo");
    await setToggle(page, 'score-rhythm', true);
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 8: tempo; open 'Habanera bass in C, in 2/4'; mode tempo; Rhythm only off; counts unchanged
  await test.step("step 8", async () => {
    const before = await countsLine(page);
    await openRow(page, "Habanera bass in C, in 2/4");
    await setMode(page, "tempo");
    await setToggle(page, 'score-rhythm', false);
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 9: tempo; open 'Habanera bass in F, in 2/4'; mode tempo; counts unchanged
  await test.step("step 9", async () => {
    const before = await countsLine(page);
    await openRow(page, "Habanera bass in F, in 2/4");
    await setMode(page, "tempo");
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 10: tempo; open 'Habanera bass in G, in 2/4'; mode tempo; counts unchanged
  await test.step("step 10", async () => {
    const before = await countsLine(page);
    await openRow(page, "Habanera bass in G, in 2/4");
    await setMode(page, "tempo");
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 11: tempo; open 'Tresillo bass in C, in 2/4'; mode tempo; speed 90 %; counts 1 of 2
  await test.step("step 11", async () => {
    await openRow(page, "Tresillo bass in C, in 2/4");
    await setMode(page, "tempo");
    await setTempo(page, 90);
    expect(page.url()).toContain(`from=${RUNG}`);
    expect((await screen(page).getAttribute('data-loop')) ?? '', 'no loop').toBe('');
    await playToSummary(page);
    expect(await countsLine(page)).toMatch(/1 of 2/);
  });

  // record step 12: tempo; open 'Tresillo bass in C — three, three, two'; mode tempo; counts unchanged
  await test.step("step 12", async () => {
    const before = await countsLine(page);
    await openRow(page, "Tresillo bass in C — three, three, two");
    await setMode(page, "tempo");
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 13: tempo; open 'Tresillo bass in F — three, three, two'; mode tempo; counts unchanged
  await test.step("step 13", async () => {
    const before = await countsLine(page);
    await openRow(page, "Tresillo bass in F — three, three, two");
    await setMode(page, "tempo");
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 14: tempo; open 'Tresillo bass in G — three, three, two'; mode tempo; counts unchanged
  await test.step("step 14", async () => {
    const before = await countsLine(page);
    await openRow(page, "Tresillo bass in G — three, three, two");
    await setMode(page, "tempo");
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 15: hear; open "L'amour est un oiseau rebelle"; loop 1-12; counts unchanged
  await test.step("step 15", async () => {
    const before = await countsLine(page);
    await openRow(page, "L'amour est un oiseau rebelle");
    await loopBars(page, 1, 12);
    await hearIt(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 16: wait; open "L'amour est un oiseau rebelle, bars 1–12, left hand"; mode wait; hand L; counts unchanged
  await test.step("step 16", async () => {
    const before = await countsLine(page);
    await openRow(page, "L'amour est un oiseau rebelle, bars 1–12, left hand");
    await setMode(page, "wait");
    await setHand(page, "L");
    await waitToSummary(page, midi);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 17: tempo; open "L'amour est un oiseau rebelle, bars 1–12, left hand"; mode tempo; hand L; speed 90 %; counts 2 of 2
  await test.step("step 17", async () => {
    await openRow(page, "L'amour est un oiseau rebelle, bars 1–12, left hand");
    await setMode(page, "tempo");
    await setHand(page, "L");
    await setTempo(page, 90);
    expect(page.url()).toContain(`from=${RUNG}`);
    expect((await screen(page).getAttribute('data-loop')) ?? '', 'no loop').toBe('');
    await playToSummary(page);
    expect(await countsLine(page)).toMatch(/2 of 2/);
  });

  // record step 18: tempo; open "L'amour est un oiseau rebelle"; loop 1-12; mode tempo; hand L; Duet on; counts unchanged
  await test.step("step 18", async () => {
    const before = await countsLine(page);
    await openRow(page, "L'amour est un oiseau rebelle");
    await loopBars(page, 1, 12);
    await setMode(page, "tempo");
    await setHand(page, "L");
    await setToggle(page, 'score-duet', true);
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 19: hear; open 'The Crave'; loop 21-26; counts unchanged
  await test.step("step 19", async () => {
    const before = await countsLine(page);
    await openRow(page, "The Crave");
    await loopBars(page, 21, 26);
    await hearIt(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 20: rhythm; open 'The Crave'; loop 21-22; mode tempo; Rhythm only on; counts unchanged
  await test.step("step 20", async () => {
    const before = await countsLine(page);
    await openRow(page, "The Crave");
    await loopBars(page, 21, 22);
    await setMode(page, "tempo");
    await setToggle(page, 'score-rhythm', true);
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 21: lesson; open 'Por Una Cabeza - Carlos Gardel'
  await test.step("step 21", async () => {
    await openRow(page, "Por Una Cabeza - Carlos Gardel");
    // The decision is the learner's: nothing is pressed and nothing is recorded.
  });

  // record step 22: hear; open 'Por Una Cabeza - Carlos Gardel'; loop 1-14; counts unchanged
  await test.step("step 22", async () => {
    const before = await countsLine(page);
    await openRow(page, "Por Una Cabeza - Carlos Gardel");
    await loopBars(page, 1, 14);
    await hearIt(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 23: rhythm; open 'Por Una Cabeza - Carlos Gardel'; loop 1-14; mode tempo; hand L; Rhythm only on; counts unchanged
  await test.step("step 23", async () => {
    const before = await countsLine(page);
    await openRow(page, "Por Una Cabeza - Carlos Gardel");
    await loopBars(page, 1, 14);
    await setMode(page, "tempo");
    await setHand(page, "L");
    await setToggle(page, 'score-rhythm', true);
    await playToSummary(page);
    expect(await countsLine(page)).toBe(before);
  });

  // record step 24: later-rung; open 'Por Una Cabeza - Carlos Gardel'; on latin.6
  await test.step("step 24", async () => {
    await openRow(page, "Por Una Cabeza - Carlos Gardel", "latin.6");
  });

  // Completion: the rung reads complete on Plan.
  await page.evaluate(() => { window.location.hash = '#/plan'; });
  const row = page.locator(`.list-row[data-lesson="${RUNG}"]`);
  await expect(row.locator('.badge')).toContainText([/complete/i]);
});
