"""statuses.py: insert one 'Validation status' paragraph under each section heading of area-1C.md (build helper; the
paragraphs are this pass's findings, recorded line by line in docs/classifier/audits/rules-1C/validation.md)."""
import re
from pathlib import Path
P = Path(__file__).resolve().parents[2] / "docs/classifier/rules/area-1C.md"
V = "[validation: `build/v1c/`, `docs/classifier/audits/rules-1C/validation.md`]"
S = {
"notation.times": ("failing", "The pair clause is right on the Bagatelle (idx 8-9, 26-27, 35-36) and on Mozart's Minuets K. 1e (three 2/4 bars, each followed by a one-beat bar: 2 + 1 = 3/4) and K. 1f; the final-bar clause on the Bagatelle idx 60; the words clause on Op. 9 No. 2. **Wrong:** \"a one-bar signature longer than the bars around it\" turns measured one-bar changes into cadenza bars and drops them from the changes of metre: *Mariage d'amour* idx 2 (5/4 of running sixteenths, and four more 5/4 bars), *Scarborough Fair* piano solo idx 101 (4/4 of quarters and eighths in 3/4), *The Lonely Man* idx 3 (5/4), *Holy, Holy, Holy* idx 15 (the final 6/4 chord). **Undecidable by code:** \"a one-bar pickup to a new section\" has no test; Radetzky's 1/4 bar has no barline, repeat, key change or words anywhere in idx 60-80 (the check's open point, measured), and *Rêverie* idx 74 and *Wake Me Up* idx 19 are single short bars at boundaries that are not pickups. The bar after a device (the return to 3/8) is literally \"a bar whose signature differs from the one before\"."),
"metre.class": ("uncertain", "The table classes the named items as stated (7/8, 12/8, 6/8, 3/8 apart, ¢ over 4/4). Open: T49 never fires: `metre.grouping` reads beams only with denominator 8 or 16 and none of the 11 files with 6/4 has counting words, so every 6/4 bar falls to compound duple, Debussy's *Cathédrale* included, which this section reads in three halves."),
"mark.anacrusis": ("validated", "Re-run on the named items: *Away in a Manger* first bar one quarter of 3/4, *Alexander's Ragtime Band* two of four, Für Elise one eighth of 3/8; *Oh! Susanna* and *Clair de lune* (beginner) full first bars, the late-entry near-misses. The hidden-rest guard (T51) has no case to run on."),
"rhythm.values": ("validated", "Counts re-run: 512ths 29 in 4 files, 256ths 15 in 3, 128ths 11 in 4 (the check's); the writer's five files are the union of the 512th and 256th files. Every sub-128th value sits in a bar that also carries a quantisation ratio (Prelude No. 15 no. 4-5 and 23-24, *Ain't Misbehavin'* 12-13 and 23-24, *O mio babbino caro* 50-52, *Malagueña* 61 and 69, Ballade No. 4 156-157), none in a rep or generated file. **The text below is wrong in two places:** Ballade No. 4's three 512ths are a 512th rest at a 5:4 ratio at no. 156-157, not the bar-50 fioritura; and the app's file keeps cue size (`<type size=\"cue\">`), so nothing was \"made full size\" (section 0). *O mio babbino caro* has 7 512ths and 2 256ths."),
"rhythm.dotted-quarter": ("validated", "Re-run: 4 dotted-quarter-eighth pairs in the drill, 12 dotted-eighth-16th pairs in Für Elise; the 6/8 drill's dotted quarters all sit in 6/8 bars (the beat, excluded by the metre); the 6/8 long-short drill has no dot."),
"rhythm.ties": ("uncertain", "Re-run as corrected: `exercise.syncopation.tied-across-bar` 2 chains from a weak beat; the tumbao 7; Waltz Op. 69 No. 2 23; *Cielito lindo* 12; *Alexander's Ragtime Band* 9 from off the beat; `exercise.ii-v-i.a` 0 (chords tied from the downbeat). The inner-chain choice holds on the items read (Bach's Prelude in C: the held inner E; *I Got Rhythm*: inner chord members under a top note found anyway; Mazurka Op. 68 No. 4: inner suspensions); a melody in an inner voice was not looked for. Open: a final note from a weak beat tied into the last bar counts (Ode to Joy easy, *Sakura*), as in `rhythm.syncopation`. The counts under the corrected rule replace the first definition's below (Output)."),
"rhythm.syncopation": ("failing", "**Right:** every case the check showed failing is now found: tied-across-bar (beat-level held, beat 4 into the bar and beat 3 over the bar), sixteenth (held at the subdivision), *Åse's Death* idx 7 (`song.classical.grieg-ase-s-tod.pdmx`), the Vivaldi *Spring* simple arrangement idx 14 (`song.classical.vivaldi-vivaldi-spring-simple-arrangement.pdmx`), *Let It Snow* idx 2 (`song.pop.frank-sinatra-let-it-snow-leadsheet.pdmx`), Waltz Op. 69 No. 2 (`song.classical.chopin-waltz-op69-2.nifc`, 23), *Cielito lindo* (`song.folk.cielito-lindo.simple` and `song.folk.exercise-cielito-lindo.pdmx`, 12 each), the tumbao. The recipe cross-check passes: all 44 generated items whose concepts name syncopation, and both `syncopation`-family drills, are present. Rejected: `ii-v-i`, Alberti, stride, oom-pah, scales, Hanon, arpeggios, boogie, walking bass (0 present in those families); Bach's Prelude in C, BWV 999, `broken7` (silent-beat report only); the triplet quarters, *Joyful, Joyful*, the Handel Sarabande (none). Of 1,165 generated items whose recipe declares no syncopation, 73 are present, each by a figure the definition names (comping off-beats 46, the 4:3 waltz 5, the tresillo bass cell 1, half or dotted half on beat 2 in riffs and studies 11, a final note anticipated off the beat in the shaping drills 10). **Wrong:** (1) `song.classical.satie-gnossienne-1` has no `<time>`; partitura's default metre gives it 14 beat-level events: the rule needs UNKNOWN `unmetred`. (2) The bass-then-held-chord test splits one figure: the Tarantella's left hand (bass on 1, chord on 2 tied over the bar) gives 4 such events and 22 beat-level held ones, the 22 having an octave bass, not \"a single note\"; and it fires in a right-hand melody (Mazurka Op. 68 No. 4 idx 32, 34). It is right on the PDMX *Gnossienne* No. 1 left hand (30). (3) \"Present\" includes off-beat attack and bass-then-held-chord, so 67 generated items and Mazurka Op. 68 No. 4 are present by an accompaniment figure alone. **Open:** a final note started on a weak beat and tied into the last bar decides presence in 3 items (*Kum ba yah*, this section's near-miss, now present; Ode to Joy easy; *Sakura*); the accent kind counts an accent on beat 3 of 3/4 and not on beat 2 (Mazurka Op. 17 No. 4, 15). The sf/sfz/fz reading was run: partitura reads them as `ImpulsiveLoudnessDirection` (Moonlight III 49, *Hall of the Mountain King* 39, equal to the raw counts); sf on beat 4 (Moonlight III) and beats 2 and 4 (Mountain King) are found, the Tarantella's 15 fz on downbeats are not."),
"rhythm.triplets": ("uncertain", "Re-run: `exercise.independence.c.3v2` 48 notes at 3:2; Black Bottom Stomp 372 with rests (the page's 320 not reconciled); no tuplet in the 6/8 drill. Open (T52): delimiting groups by bracket was not run; 576 closed brackets in the catalogue hold fewer notes than their actual-notes because they hold long-short pairs or rests, so a group cannot be required to hold three notes."),
"rhythm.tuplets-other": ("failing", "Kept, right: Polonaise Op. 53 29:20, Ballade No. 1 39:32, 28:16, 21:16, 29:16. Within 5 per cent of 1 only artefact ratios (23:24, 40:39, 160:159, 80:79, 320:319, 48:47, 96:95, 160:157) and ratio 1 (8:8, 2:2 in the Ständchen); no printed ratio lies inside the bound. **Wrong:** the bound leaves as tuplets 12 more artefact ratios of *Malagueña* (160:107, 80:53, 120:67, 48:43, 320:179, 320:301, 60:53, 640:321, 320:161, 15:14, 20:17, 480:371), 320:239 and 160:119 (*O mio babbino caro*), 24:17 and 40:37 (*Ain't Misbehavin'*), 12:11 (*Silent Night* trombone duet), and the irregular kind (11 or more actual notes) then hands the three-digit ones to `rhythm.cadenza`; the fewer-notes test misses the named 480:371 (a single half rest with no bracket, no. 61) and flags 576 real brackets (Black Bottom Stomp's sixteenth-eighth triplets, Prelude Op. 28 No. 1's figures with rests, Op. 15 No. 2's 5:4)."),
"rhythm.cadenza": ("failing", "Found as stated: Ballade No. 4 PDMX no. 50 (14 cue notes; also no. 120, 135-136), Op. 9 No. 2's \"Senza tempo\", the Berceuse (9 grace notes, 11:8), Polonaise Op. 53 29:20, Op. 9 No. 1 11:6, Prelude No. 18 11:8; also Liebestraum No. 3 cue runs no. 25 and 60, *Malagueña* no. 61-69 beside \"a piacere\" no. 70, Moonlight III (alt) 30 grace notes no. 188. **Wrong:** the cue route reads a \"source\" that is the app's own file (section 0) and answers UNKNOWN where no source is mapped (the applier's choice), which is every rep item, though 12 rep files carry cue notes in their own file (Liebestraum No. 3 368, *La Campanella* 388); the named positive Fantaisie-Impromptu no. 5 is a cue half and quarter in the left hand, and the cue route gives 40 candidate runs in that piece, which has no cadenza (a near-miss for the agent, not a positive); the irregular route receives the artefact ratios `rhythm.tuplets-other` fails to remove. The word list finds 9 items, one a pedalling instruction (\"Pedal Freely\")."),
"rhythm.repeated-notes": ("validated", "Re-run: Asturias right hand longest run 96; Prelude No. 15 left hand 56; `exercise.repeated-notes.c.4x.right` 4; the Alberti left hand 0 pairs."),
"rhythm.equal-stream": ("validated", "Re-run: Hanon 20 241 sixteenths; Prelude No. 2 384 and 408; Étude Op. 10 No. 1 75 from bar 41; Ode to Joy 3; Prelude in C 15 per hand, 529 merged. T16 stays open."),
"rhythm.habanera": ("validated", "Re-run (cells as a pattern): right hand *Chrysanthemum* 14, *Cleopha* 11, *Country Club* 4, *Die wilden Hühner* 21, Bizet 26; left hand Bizet 85, *Carioca* 22, *El Choclo* 9 (`song.classical.el-choclo-piano.pdmx`), *Solace* 49 (`song.ragtime.joplin-solace`), *La Cumparsita* 7, `exercise.bass-cell.habanera.c` 8; *Auld Lang Syne* doubled right hand 9 and left hand 0 (not 12); `exercise.tresillo.c` none. Code names a habanera only for the declared generated cells; every other occurrence goes to the agent, so no near-miss reaches a habanera claim."),
"rhythm.tresillo": ("validated", "Re-run: `exercise.tresillo.c` left hand 8 (doubled), `exercise.clave.son-3-2` right hand 4, `exercise.tumbao.c` and `exercise.bass-cell.habanera.c` none. **Example wrong:** `song.classical.rodriguez-la-cumparsita.pdmx` holds the habanera cell (left hand 7 bars) and no tresillo bar."),
"rhythm.cinquillo": ("validated", "Re-run: *The Entertainer* right hand 7 (idx 58, 66, 75 ...), *Cascades* 11 (the page says 10), *Chicken Reel* 4 (idx 74-75, 78-79), *Chrysanthemum* 2 scattered, the study 1 bar. Naming goes to the agent."),
"rhythm.secondary-rag": ("validated", "`rules/rhythm.py` `secondary_rag` re-run: 12th Street Rag 10 bars in both editions, *Memphis Blues* 6; `exercise.secondary-rag.c.4bar`, Moonlight I, the Prelude in C and *Elite Syncopations* 0 (S8 stays open)."),
"rhythm.shuffle": ("uncertain", "`rules/rhythm.py` `shuffle` re-run; the style field is the catalogue's `tracks`. Black Bottom Stomp: 29 triplet bars, track blues-boogie, a shuffle; Op. 55 No. 2 (`song.classical.chopin-nocturne-op55-2.nifc`): 21 bars of 12/8 pairs, track classical, no claim. **The examples contradict the rule:** *Ain't Misbehavin'* has 14 marked bars and no notated long-short pair, so it is no shuffle positive here; `exercise.meter.12-8` has tracks blues-boogie and jazz and concepts shuffle, slow-blues and twelve-bar-blues, so the rule asserts a shuffle for it. Whether a 12/8 slow-blues drill should be called a shuffle no one in this process can hear."),
"notation.swing-mark": ("validated", "Re-run: `exercise.swing-pair.c` \"Straight\" then \"Swing: long, then late\"; the shuffle-eighths drill; *Lullaby of Birdland* \"Med-Swing\" (matched); `exercise.boogie.a.pinetop` no words."),
"rhythm.backbeat": ("validated", "Code part re-run: accents kind *I'm Blue* 6 bars; onsets kind *Light the World* left hand 26 bars (one bass note on 2 and 4 under a held right hand: the agent's question, as the Examples say); *Blinding Lights* right hand 4, *Arabesque* left hand 4, *Tiger Rag* right hand 11, *Rêverie* left hand 3 and the Fantaisie-Impromptu's accents (4 bars) go to the residual; `exercise.stride.c` none."),
"rhythm.hemiola": ("uncertain", "Re-run: two-bar kind Boléro idx 197 and *La plus que lente* idx 115, 117; 6/8 as 3/4 *Song of Storms* left hand 12 bars; cross-grouped 3/4 bars *Carol of the Bells* medley right hand 45, *Scarborough Fair* left hand 4; the Sarabande none. Open: \"alternate\" is not defined (read as a cross-grouped bar beside a bar of the metre's own grouping, 2 in each piece), and present-at-one-occurrence (T26) has no basis."),
"texture.polyrhythm": ("validated", "Re-run: 3v2 3:2, 2v3 2:3, *Arabesque* 3:2 and 2:3, Fantaisie-Impromptu 4:3, the waltz accompaniment 4:3 (generator defect), Alberti none. Wording: \"a span inside one already found is skipped\" should read \"containing\"; read literally it counts the pair and bar spans too (28 in 3v2 against 16 beats)."),
"rhythm.beat-onset-share": ("validated", "Re-run: Hanon 61 of 62 beats, Für Elise 304 of 312, `exercise.ii-v-i.a` 3 of 16, *Hesitating Blues* 80 of 192."),
"mark.tempo-text": ("validated", "Re-run: Op. 10 No. 1 quarter = 176, *Scarborough Fair* 165, Asturias no metronome (sound tempo 144), the 6/8 drill quarter = 80, the 12/8 drill quarter = 76."),
"mark.tempo-change": ("validated", "Re-run on the named words: Op. 9 No. 2 (\"poco rit.\", \"a tempo\", \"poco rubato\", \"Senza tempo\" at MusicXML numbers 10, 11, 26, 33: the page's bar numbers are one higher), *Malagueña*, *Clair de lune*; *La plus que lente*'s French words unclassified (the file has \"Animez un peu\", not \"Tempo animé\"). T32 open."),
"technique.velocity": ("validated", "Re-run: Hanon 20 3.89 a second at quarter = 60; Op. 10 No. 1 right hand 11.32 and left 0.69 at 176; the 6/8 drill 2.67 at quarter = 80; Asturias no printed tempo."),
"technique.endurance": ("validated", "Re-run: Hanon 241 onsets over 62 quarters; Prelude No. 2 384 (96 quarters) and 408; the Prelude in C short spans; the 12/8 drill's right hand 1 onset."),
"metre.grouping": ("validated", "Re-run: 7/8 beams 2+2+3 and \"Count 2 + 2 + 3\"; 5/4 \"Count 3 + 2\"; the 6/8 drill beams 3+3; *Take Five* has no counting words (UNKNOWN by code). The 12/8 drill's beams were not re-read. T37's consequence for 6/4 is under `metre.class`."),
"rhythm.silence": ("validated", "Re-run: swing-pair 4 beats at idx 4; *Weary Blues* 7.5 beats at idx 2; Scherzo No. 2 up to 9; the clave's gaps 1 to 1.5; *Doctor Gradus* 167.5 (the integrity case). The \"original upload\" is not held (section 0), so the other-parts question answers UNKNOWN for every item by the rule's own fallback."),
"rhythm.bar-patterns": ("validated", "Re-run: the Prelude in C top share 0.91 of 34 bars, 7/8 1.0, Für Elise 16 distinct (0.37), the clave 0.5."),
"rhythm.clave-alignment": ("uncertain", "The scoring re-implemented and re-run: `exercise.clave.son-2-3` 2-3 in 4 of 4 cycles, `son-3-2` 3-2, the montuno 3-2, the `.pulse` left hand and `exercise.tumbao.c` neutral, *Recado* 21 2-3 and 3 3-2 (as stated). No repertoire item in the catalogue declares a direction (ids searched for clave, son, salsa, mambo, bossa, samba, rumba, montuno), and Mauleón is unread: repertoire stays unverified."),
}
t = P.read_text(encoding="utf-8")
n = 0
for cid, (st, body) in S.items():
    pat = re.compile(r"^## " + re.escape(cid) + r"\n\n", re.M)
    assert len(pat.findall(t)) == 1, cid
    t = pat.sub(lambda m: m.group(0) + f"**Validation status (2026-10-08): {st}.** {body} {V}\n\n", t)
    n += 1
P.write_text(t, encoding="utf-8")
print("inserted", n)
