"""Adds two columns to ChatGPT's 213-row detectability review: claude_batch and claude_opinion (the owner, 2026-10-10:
"reviewed it line by line to add your opinion in a new column"). Output: chatgpt-detectability-213-with-claude.csv.

claude_batch values:
  EASY Exx   in the first batch, row Exx/Dxx of characteristics-easy.csv
  PATTERNS   the next batch: named accompaniment and run patterns (definitions are the risk; each needs fooling cases)
  HARMONY    needs key or harmony estimation from notes; later, after the easy batch
  STEP 4     belongs to generators and exercises, not to placing real pieces
  DONE       already done by the step-3 pipeline (matching, file checks)
  SKIP       no rung, difficulty statistic or generator check needs it, or code cannot settle it

Usage: python docs/pieces/review/characteristics/add_claude_opinion.py
"""
import csv, os

HERE = os.path.dirname(os.path.abspath(__file__))

OP = {
    "item.format": ("EASY E01", "Layout part only (parts, staves, instrument names). I would not infer 'purpose' or 'exercise versus piece': E01 refuses any layout other than one two-staff piano part instead of interpreting it. Agree CONDITIONAL for the rest."),
    "notation.staves": ("EASY E01", "Agree DIRECT."),
    "prereq.hand-assignment": ("SKIP", "Agree INFERRED. Every easy row reports staves and never says 'hand'. The old branch measured the staff rule disagreeing with a second reader on 3.3% of notes in a 33-item sample and being wrong on 41.5% of notes under printed hand words, so staff = hand is a stated convention, not a fact."),
    "texture.melody-location": ("SKIP", "Agree INFERRED. E39 uses the top line of staff 1 as a stated convention for leap statistics, never as 'the melody'."),
    "notation.clefs": ("EASY E03", "Agree DIRECT."),
    "notation.clef-change": ("EASY E03", "Agree DIRECT; restated clefs must not count as changes (50 files in the old catalogue restate)."),
    "pitch.ledger": ("EASY E05", "Agree it is codable, but DIRECT only once clef (E03) and ottava (E04) are read; the line-versus-space boundary is the main risk, pinned by hand-made cases. More than 5 ledger lines usually means a lost 8va in the file."),
    "mark.ottava": ("EASY E04", "Agree DIRECT; unclosed and empty spans occur (old branch) and '8va' typed as words is listed separately."),
    "notation.keys": ("EASY E06", "Agree DIRECT."),
    "key.signature-exercised": ("EASY E08", "Agree; I would call it DIRECT for the encoded notes."),
    "pitch.chromatic": ("EASY E07", "Only the encoded accidentals (E07). 'Out of the local key' needs key estimation, which is HARMONY. Agree CONDITIONAL."),
    "reading.accidental-kinds": ("EASY E07", "DIRECT for the file's <accidental> elements only. Which accidentals a page actually shows is not easy: the old branch's display model was wrong on 11.1% of notes with an accidental against a real renderer."),
    "reading.accidental-churn": ("SKIP", "Disagree with DIRECT: churn depends on the displayed accidental state through a bar, the part the old branch got wrong on 11.1% of notes. E46 gives accidentals per bar instead, which is enough for choosing reading excerpts."),
    "reading.visual-density": ("EASY E46", "Agree; built from E05, E07, E11 so it avoids the old display model."),
    "reading.unusual-notation": ("SKIP", "No rung needs a generic 'unusual' list; the specific marks that matter are their own easy rows."),
    "reading.pitch-entropy": ("EASY E35", "Agree DIRECT; used only as a difficulty statistic."),
    "reading.redundancy": ("SKIP", "The number depends on the tokenisation chosen and no rung needs it. Revisit only if D02 shows the easy statistics miss something repetition would explain."),
    "notation.turn-opportunity": ("SKIP", "Page turns do not apply to an app that scrolls."),
    "mark.fingering": ("EASY E27", "Agree DIRECT; digits typed as words are listed separately, never merged."),
    "notation.lyrics": ("SKIP", "No rung, difficulty statistic or generator check needs it (dropped from the easy batch on the owner's question, 2026-10-10)."),
    "notation.chord-symbols": ("EASY E29", "Agree; structured <harmony> only (music21 equal on 459 of 460 items in the old branch). Chord names typed as text are left out: music21 misread 'Bb7' as root B."),
    "harmony.figured-bass": ("SKIP", "1 of our 842 candidate files has it and no rung reads figured bass."),
    "mark.repeat": ("EASY E31", "Presence and position of signs only. Agree CONDITIONAL for playback order: on 81 disputed files music21's expander was right on 27 and partitura's on 21, so expansion is a later, separate job."),
    "notation.reading-aids": ("STEP 4", "Note-name and finger-number aids are things our generators print for Levels P-A; in PDMX files they are rare."),
    "notation.slash-rhythm": ("EASY E30", "Agree DIRECT; only 1 of 842 files has slashes, so low value."),
    "integrity.notation-sanity": ("DONE", "Bar lengths and part layout are already checked by file_checks.py and quality_check.py; E02 reuses that. Spelling 'typos' I would skip: unusual spelling is often intended."),
    "hands.per-bar-range": ("EASY E33", "Per staff, not per hand. A verified hand assignment is not available (see prereq.hand-assignment), so the row states staff."),
    "pitch.black-key-share": ("EASY E34", "Agree DIRECT; every note of a chord counts."),
    "technique.five-finger": ("PATTERNS", "Useful for P.4, A.2 and B.3 pieces. The span over a window is easy; 'stays in one position through the passage' needs a definition and fooling cases (old branch: frame-based spans failed on semitone-shifted patterns)."),
    "technique.position-shift": ("SKIP", "Depends on fingering, which the score does not fix. pianoplayer could estimate fingering, but that is not easy and no rung needs shift counts from pieces."),
    "key.tonic-mode": ("HARMONY", "Agree INFERRED. Useful later as a generator check (the exercise is in the key it claims) and for minor pieces, but music21's key estimate is an estimate and needs its own test set."),
    "key.minor-form": ("HARMONY", "Needs a confirmed minor tonic first."),
    "key.change": ("EASY E06", "Signature changes are E06. Modulation without a signature change is HARMONY."),
    "scale.collection": ("HARMONY", "Small pitch sets fit many scales; useful later for improvisation material, not for placing pieces."),
    "pitch.inventory": ("EASY E34", "Agree DIRECT."),
    "reading.enharmonic-spelling": ("SKIP", "No rung needs it; unusual spellings are usually intended."),
    "key.polytonal": ("SKIP", "No rung."),
    "pitch.tone-row": ("SKIP", "No rung; Grade 8 serial pieces come from published lists by title."),
    "notation.times": ("EASY E09", "Agree DIRECT; music21 and partitura matched the raw reader on all 187 changes tested in the old branch."),
    "metre.class": ("EASY E09", "Class from the written signature only (simple, compound, irregular). Grouping of 5/8 and 7/8 only when the numerator is written as a sum; otherwise UNKNOWN."),
    "mark.anacrusis": ("EASY E10", "Agree; report the first and last bar lengths and the implicit flag rather than decide."),
    "rhythm.values": ("EASY E11", "Agree DIRECT; values shorter than a 128th came only from PDMX re-export artefacts in the old branch and are flagged, not used."),
    "rhythm.dotted-quarter": ("EASY E12", "Agree; simple time only, as ChatGPT says."),
    "rhythm.ties": ("EASY E11", "Agree DIRECT."),
    "rhythm.syncopation": ("PATTERNS", "Needed (2.4, RG.2, BL.1) and worth doing early in the next batch. The old branch's dispute was whether a pickup counts: 82 of 83 disagreements were pickup bars. Needs a quoted definition first."),
    "rhythm.triplets": ("EASY E13", "Agree, with the old branch's rule: only printed brackets of 2 or more notes (kept 14 of 14 real figures and dropped 21 of 21 artefacts)."),
    "rhythm.tuplets-other": ("EASY E13", "Same rule as triplets; raw time-modification ratios include artefacts such as 160:107."),
    "rhythm.cadenza": ("SKIP", "No rung; rare."),
    "rhythm.repeated-notes": ("EASY E40", "Agree CONDITIONAL is fair; within one written voice it is a run count."),
    "rhythm.equal-stream": ("EASY E40", "Agree; useful for Hanon-type rungs (1.13, 2.11, 3.10)."),
    "rhythm.habanera": ("PATTERNS", "An exact onset cell is easy to match, but only style rungs use it; low priority in the pattern batch."),
    "rhythm.tresillo": ("PATTERNS", "As habanera; low priority."),
    "rhythm.cinquillo": ("SKIP", "No rung names it."),
    "rhythm.secondary-rag": ("PATTERNS", "RG.2 and RG.3; harder than the plain cells (three-note groups occur everywhere). Rags can be found by title and published lists first."),
    "rhythm.shuffle": ("PATTERNS", "Written long-short figures are easy; the swing direction is read in E26. Whether a piece is played swung is not in the notes."),
    "notation.swing-mark": ("EASY E26", "Read with the tempo-change words (E26). 0 of our 842 files carry the <swing> element, so the words are what matter."),
    "rhythm.backbeat": ("SKIP", "Agree INFERRED; a piano score usually lacks the drums that make a backbeat."),
    "rhythm.hemiola": ("SKIP", "Interpretive; no rung."),
    "texture.polyrhythm": ("PATTERNS", "A tuplet group on one staff over straight values on the other is easy to find from E13; whether it is a real cross-rhythm needs the fooling cases ChatGPT names."),
    "rhythm.beat-onset-share": ("EASY E42", "Agree DIRECT."),
    "mark.tempo-text": ("EASY E25", "Read numbers only: metronome marks and <sound tempo>. A tempo word alone gives no number (music21 would map 'Allegro' to 132, which is a guess)."),
    "mark.tempo-change": ("EASY E26", "Closed word list; anything else is listed unclassified."),
    "technique.velocity": ("EASY D01", "Agree CONDITIONAL: UNKNOWN when no tempo is written; a <sound tempo> of exactly 120 with no metronome mark is flagged as a possible export default."),
    "technique.endurance": ("EASY E40", "Runs of equal values (E40) and notes per second (D01) are the measurable parts; fatigue itself is not in the score."),
    "metre.grouping": ("EASY E09", "Only where the numerator is written as a sum; otherwise UNKNOWN, as ChatGPT says."),
    "rhythm.silence": ("EASY E11", "Rest counts are in E11. Silence of the whole texture I would skip: no rung uses it."),
    "rhythm.bar-patterns": ("STEP 4", "Useful for rhythm generators and for spotting repetition; not needed to place pieces."),
    "rhythm.clave-alignment": ("SKIP", "No rung needs it from piano scores."),
    "interval.melodic": ("EASY E39", "Per staff with a stated convention (top line of staff 1, bottom line of staff 2) and per written voice; never called the melody."),
    "quality.contour": ("STEP 4", "A quality check for generated melodies; not needed to place real pieces."),
    "quality.leap-recovery": ("STEP 4", "As contour."),
    "melody.tessitura": ("SKIP", "Range per staff (E33) covers what placement needs."),
    "melody.degree-profile": ("HARMONY", "Needs a key."),
    "melody.chord-relation": ("HARMONY", "Needs harmony."),
    "melody.motif-repetition": ("SKIP", "2.6 asks the learner to point out a motive; finding pieces with clear motives by code is hard and the pieces come from published lists. Revisit in step 4 for generated melodies."),
    "melody.sequence": ("SKIP", "As motif repetition (2.6, 3.11 are learner tasks)."),
    "technique.written-ornament": ("PATTERNS", "Written-out trills and mordents; lower priority than the left-hand patterns because E15 already finds ornament signs."),
    "harmony.chord-quality": ("EASY E29", "From chord symbols only (the <kind> element) it is a direct read. From notes it is HARMONY."),
    "harmony.inversion": ("HARMONY", "Needs chord identity."),
    "harmony.roman": ("HARMONY", "The old branch's notes path agreed with printed symbols on the root in 0.864 of the beats it resolved and left 6,282 of 14,397 symbol beats unresolved; not easy."),
    "harmony.progression": ("HARMONY", "Needs harmony; from chord symbols it is easier, but only 39 of 842 files have symbols."),
    "harmony.applied": ("SKIP", "No rung needs it from pieces."),
    "harmony.cadence": ("HARMONY", "3.5 and 7.5 are keyboard tasks for the learner; pieces with clear cadences are not needed from code."),
    "harmony.chromatic-share": ("SKIP", "No rung."),
    "harmony.rhythm": ("EASY E29", "Symbols per bar from chord symbols is a direct count (added to E29). From notes it is HARMONY."),
    "harmony.chord-vocabulary": ("EASY E29", "Distinct chord symbols from <harmony> only; from notes it is HARMONY."),
    "harmony.voicing": ("HARMONY", "Jazz rungs; later."),
    "harmony.voice-leading": ("SKIP", "No rung needs it from pieces."),
    "harmony.chord-connection": ("STEP 4", "For comping generators."),
    "harmony.bass-behaviour": ("PATTERNS", "Overlaps the named bass patterns (oom-pah, walking, boogie); do those instead of a general bass detector."),
    "texture.bass-walk-up": ("SKIP", "No rung needs it from pieces."),
    "texture.pedal-point": ("SKIP", "No rung."),
    "harmony.implied": ("SKIP", "Agree: never present a guessed harmony."),
    "harmony.planing": ("SKIP", "No rung."),
    "harmony.dissonance-share": ("SKIP", "Interval counts are exact, but calling them dissonant is a style judgment and no rung uses it."),
    "harmony.chord-scale": ("HARMONY", "Improvisation material; later."),
    "texture.type": ("SKIP", "Agree INFERRED; no clean use."),
    "texture.hands-together": ("EASY E43", "Per staff (shared attacks and bars where both staves sound)."),
    "texture.voice-count": ("EASY E41", "Written voices only, as ChatGPT says; partitura's voice estimate is not used (it raised RecursionError on a corpus file)."),
    "texture.counterpoint": ("SKIP", "Contrapuntal pieces for 7.4 come from published lists (inventions, fugues by title)."),
    "texture.imitation": ("SKIP", "As counterpoint."),
    "texture.block-chords": ("EASY E36", "Per staff, not per verified hand; reported both across voices and within one voice (they differed on 23 of the 109 shortlist files)."),
    "interval.harmonic": ("EASY E36", "Two-note attacks per staff, in semitones."),
    "texture.double-notes": ("STEP 4", "7.2 and 8.2 are technique exercises (thirds and sixths), made by generators; finding double-note passages in pieces is not needed."),
    "texture.octaves": ("EASY E38", "Simultaneous octaves per staff from E36; broken octaves are a pattern."),
    "texture.power-chord": ("PATTERNS", "Root-fifth-octave with no third is easy from E36 (MT.1); low priority."),
    "texture.broken-chord": ("PATTERNS", "Needed for B.5, B.6 and PR.4; definition and fooling cases first."),
    "texture.alberti": ("PATTERNS", "High priority: rung 1.5 still has no piece. The current rung_pieces.py rule counts one figure per bar, which an incidental figure passes."),
    "texture.arpeggio": ("PATTERNS", "With broken chords."),
    "texture.waltz-bass": ("PATTERNS", "High priority (B.6, 1.5). The current rule misses broken waltz-bass shapes."),
    "texture.oom-pah": ("PATTERNS", "RG.1."),
    "texture.stride": ("PATTERNS", "RG.4 (optional rung); after oom-pah."),
    "texture.boogie-bass": ("PATTERNS", "BL.1."),
    "texture.walking-bass": ("PATTERNS", "BL.5, J.4; the old app detector exists and can be brought over and tested."),
    "texture.left-hand-pattern": ("SKIP", "Replaced by the named patterns; 'any active left hand' tells nothing."),
    "texture.ostinato": ("PATTERNS", "B.6 (meet) and 1.5."),
    "texture.repeated-chords": ("PATTERNS", "Easy from E36 and E40 (PR.2 rock comping)."),
    "texture.offbeat-chords": ("PATTERNS", "PR.5; low priority."),
    "texture.charleston": ("PATTERNS", "J.4 and J.5; low priority."),
    "texture.montuno": ("SKIP", "No rung asks for it from piano scores."),
    "texture.tumbao": ("SKIP", "No rung."),
    "texture.clave": ("SKIP", "No rung asks for it from piano scores."),
    "texture.bossa": ("SKIP", "Agree INFERRED; no rung needs it from pieces."),
    "texture.tango": ("SKIP", "No rung."),
    "texture.mazurka": ("SKIP", "Mazurkas come by title from published lists."),
    "texture.stop-time": ("SKIP", "No rung needs it from pieces."),
    "texture.tremolo-thirds": ("PATTERNS", "BL.6; E17 covers the tremolo sign."),
    "texture.crushed-note": ("PATTERNS", "Grace notes are E14; a grace note a semitone below a chord tone (the blues crushed note, BL.6) is a small pattern on top."),
    "texture.half-time": ("SKIP", "Agree INFERRED."),
    "texture.call-response": ("SKIP", "Agree INFERRED."),
    "texture.melody-in-chords": ("SKIP", "No clean use."),
    "texture.sustained": ("EASY E45", "Held notes under a moving staff are E45; whole-bar chords alone I would skip."),
    "texture.build": ("SKIP", "No rung."),
    "texture.register-trajectory": ("SKIP", "No rung needs it."),
    "texture.part-roles": ("SKIP", "E01 refuses multi-part files instead of guessing roles."),
    "texture.piano-role": ("SKIP", "As part roles."),
    "mark.extended-technique": ("SKIP", "No rung."),
    "mark.glissando": ("EASY E18", "Agree DIRECT; rare (6 of 842 files) but 3.4 names glissando."),
    "texture.latin-pattern": ("SKIP", "Agree: no catch-all detector."),
    "coordination.synchrony-share": ("EASY E43", "DIRECT per staff; per hand it inherits the staff-versus-hand problem."),
    "coordination.rhythmic-independence": ("SKIP", "The measurable parts are E42 and E43; 'independence' needs a definition no rung asks for."),
    "coordination.unequal-rates": ("EASY E42", "Agree DIRECT."),
    "coordination.articulation-conflict": ("PATTERNS", "Easy from E22 per staff at the same time (staccato against slurred); low priority."),
    "coordination.dynamic-balance": ("EASY E20", "E20 reports where the staves carry different dynamics; balance itself cannot be read from a score."),
    "coordination.register-overlap": ("SKIP", "No rung."),
    "coordination.pedal-with-hands": ("SKIP", "Needs harmony and the pedal is judged by self-review in B.8 and 1.6."),
    "coordination.sustain-vs-move": ("EASY E45", "Agree DIRECT per staff."),
    "coordination.hand-interval": ("SKIP", "No rung."),
    "texture.motion": ("STEP 4", "Contrary motion in B.4 is a scale exercise made by generators."),
    "texture.alternating-hands": ("EASY E44", "Agree; written durations, pedal ignored."),
    "technique.hand-crossing": ("SKIP", "Agree INFERRED; no rung needs it."),
    "technique.scale-run": ("PATTERNS", "Useful (scale passages in pieces for the scale rungs, and as a generator check); definition and fooling cases first."),
    "technique.arpeggio-run": ("PATTERNS", "As scale runs."),
    "technique.arpeggio-chord": ("PATTERNS", "After arpeggio runs."),
    "technique.thumb-under": ("SKIP", "Depends on fingering."),
    "technique.finger-independence": ("SKIP", "Not observable from a score."),
    "technique.span": ("EASY E37", "Per staff, not per verified hand; ChatGPT's DIRECT holds only for the staff. Arpeggio-signed chords are flagged."),
    "technique.leap-size": ("EASY E39", "Per staff with time between attacks (Sébastien et al.'s over 12 semitones within 2 beats)."),
    "technique.displacement-rate": ("EASY E39", "Jumps per bar from E39; a finer rate can wait for D02's result."),
    "technique.fingering-demand": ("SKIP", "pianoplayer could estimate fingering (Ramoneda et al. 2022 got their best result from its finger-velocity cost), but that is the D03 route, not an easy row."),
    "technique.pedal-implied": ("SKIP", "Agree INFERRED."),
    "mark.dynamics": ("EASY E20", "Agree DIRECT; partitura classed the word 'calando' as a dynamic, so read raw XML."),
    "mark.hairpin": ("EASY E21", "Agree."),
    "mark.articulation": ("EASY E22", "Agree DIRECT."),
    "mark.slur": ("EASY E23", "Agree DIRECT; same-pitch slurs listed as possible ties."),
    "mark.pedal": ("EASY E24", "Agree DIRECT; music21 lost one of 33 pedal starts on one of our files, so raw XML is the reference."),
    "mark.pedal-kind": ("EASY E24", "Una corda and tre corde from a closed word list."),
    "mark.ornament": ("EASY E15", "Agree DIRECT; grace notes are E14."),
    "mark.arpeggiate": ("EASY E16", "Agree DIRECT."),
    "mark.tremolo": ("EASY E17", "The sign is DIRECT; written-out tremolos are a pattern."),
    "mark.fermata": ("EASY E19", "Agree DIRECT."),
    "mark.expression-text": ("SKIP", "E26 lists unclassified words; a character-word lexicon has no rung that needs it."),
    "expression.character": ("SKIP", "Agree INFERRED."),
    "form.length": ("EASY E32", "Written bars only; played length waits for repeat expansion (see mark.repeat)."),
    "form.sections": ("SKIP", "Double bars and rehearsal marks are easy to read but do not establish sections; no rung needs it from code."),
    "form.phrase": ("SKIP", "Agree INFERRED."),
    "form.period": ("SKIP", "Agree INFERRED."),
    "form.twelve-bar": ("HARMONY", "From chord symbols it is a template match (BL.2, 2.6), but only 39 of 842 files have symbols."),
    "form.turnaround": ("SKIP", "Agree INFERRED."),
    "form.intro-ending": ("SKIP", "Agree INFERRED."),
    "form.multi-strain": ("SKIP", "Rags come by title from published lists."),
    "form.thirty-two-bar": ("SKIP", "Standards come by title from published lists."),
    "form.binary-ternary": ("SKIP", "1.7 gets repeat signs from E31; the form itself is a reading."),
    "form.variations": ("SKIP", "Titles say so."),
    "form.sonata": ("SKIP", "Agree NO."),
    "form.rondo": ("SKIP", "Titles say so."),
    "form.fugue": ("SKIP", "Titles say so."),
    "form.song-sections": ("SKIP", "Agree INFERRED."),
    "form.improvisation-space": ("SKIP", "Not in PDMX piano scores."),
    "style.evidence": ("SKIP", "Style comes from the published list a piece is on (jazz, pop, ragtime syllabuses)."),
    "style.genre-label": ("DONE", "The list source records the style (candidates-passing.csv)."),
    "meta.composer-era": ("SKIP", "Period comes with the published list entry; no rung needs code for it."),
    "meta.genre-tags": ("SKIP", "Uploader tags are unreliable and not needed."),
    "meta.title": ("DONE", "match.py already reads titles, catalogue numbers and movement names."),
    "meta.collection": ("DONE", "Already recorded per file (PDMX, shelf, list source)."),
    "meta.published-grade": ("DONE", "This is step 3's matching (wanted.csv to available.csv); D02 uses it as the answer key."),
    "meta.familiarity": ("DONE", "Decided by the picker agents and the owner ('I'd know the song'), not by code."),
    "meta.arrangement": ("EASY D02", "D02's mismatch alarm flags files whose statistics disagree with the listed level (the usual sign of a different arrangement); confirming the arrangement stays with the reference check (ref_check.py)."),
    "generated.spec-declared": ("STEP 4", "Every easy row doubles as a check that a generated exercise contains what its spec says; that is how this batch serves step 4."),
    "style.dance-type": ("SKIP", "Titles say so."),
    "meta.keyboard-sound": ("SKIP", "No rung."),
    "difficulty.reading": ("EASY D02", "Agree NO as a single number from rules. D02 measures whether the reading statistics (ledger lines, accidentals, density) track published levels."),
    "difficulty.rhythm": ("EASY D02", "As difficulty.reading."),
    "difficulty.pitch-navigation": ("EASY D02", "As difficulty.reading."),
    "difficulty.coordination": ("EASY D02", "As difficulty.reading; uses E42 and E43."),
    "difficulty.technique": ("EASY D02", "As difficulty.reading."),
    "difficulty.harmonic-load": ("SKIP", "Needs harmony from notes; leave out of D02."),
    "difficulty.expressive": ("SKIP", "More marks need not mean harder; leave out of D02 unless the first run suggests otherwise."),
    "difficulty.perceptual": ("EASY E46", "Page layout is not in the file; E46's counts are the measurable part."),
    "difficulty.level": ("EASY D02", "Agree: keep the published level; D02 tests a calibrated predictor against it and D03 runs the published CIPI model. Neither replaces a published level."),
    "difficulty.local-profile": ("EASY D01", "Densest bars come with D01 and E46; a 'hardest passage' label I would not claim."),
    "quality.coherence": ("SKIP", "Agree NO."),
    "quality.idiomatic": ("SKIP", "Agree NO."),
}


def main():
    src = os.path.join(HERE, "chatgpt-detectability-213.csv")
    rows = list(csv.DictReader(open(src, encoding="utf-8-sig")))
    ids = [r["characteristic_id"] for r in rows]
    missing, extra = set(ids) - set(OP), set(OP) - set(ids)
    assert not missing and not extra, (missing, extra)
    cols = list(rows[0].keys())
    cols = cols[:4] + ["claude_batch", "claude_opinion"] + cols[4:]
    out = os.path.join(HERE, "chatgpt-detectability-213-with-claude.csv")
    with open(out, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        for r in rows:
            b, o = OP[r["characteristic_id"]]
            w.writerow({**r, "claude_batch": b, "claude_opinion": o})
    from collections import Counter
    print(out, len(rows), "rows;", Counter(OP[i][0].split()[0] for i in ids).most_common())


if __name__ == "__main__":
    main()
