"""Writes characteristics-easy.csv: the first, easy batch of code-detectable score characteristics, one implementation
idea per row, for the owner's ChatGPT review (the owner, 2026-10-10, docs/inputs/2026-10-10.md). Nothing here is built.

Inputs read when this was written: chatgpt-detectability-213.csv (ChatGPT's ids in column chatgpt_ids),
old-library-findings.md (the old branch's measured comparisons at c8b33af6), new-library-research.md (music21 10.5.0 /
partitura 1.9.0 functions run on corpus scores; published difficulty code), the element counts over our 842 candidate
files (candidates-passing.csv plus chosen.csv; column in_our_files), and rungs.md for the rung ids in used_for.

Usage: python docs/pieces/review/characteristics/make_easy_csv.py
"""
import csv, os

HERE = os.path.dirname(os.path.abspath(__file__))
COLS = ["id", "group", "fact", "chatgpt_ids", "reports", "definition", "implementation", "library_and_prior_evidence",
        "pitfalls", "tests_pass_fail_fool", "in_our_files", "used_for", "why_easy", "review_change"]

ROWS = [
    # ---------------------------------------------------------------- foundation
    dict(id="E01", group="foundation", fact="Score layout: parts and staves",
         chatgpt_ids="notation.staves; item.format",
         reports="Number of parts, part names and instruments, staves per part; layout verdict: SUPPORTED (one pitched part with two staves) or UNSUPPORTED with the reason.",
         definition="Parts from <part-list>/<score-part>; staves from <attributes><staves>. Only one pitched part with two staves is supported; staff 1 and staff 2 are then the two staves. Every other layout (two parts, one staff, a voice or other instrument part, staves changing mid-piece) is UNSUPPORTED and every per-staff row below returns UNKNOWN for that file instead of guessing.",
         implementation="Raw MusicXML walk with ElementTree, namespace-agnostic, opening .mxl through META-INF/container.xml (as build_available.py and export_shortlist.py already do). music21 score.parts (two PartStaff objects) as the second reader. Reuse quality_check.not_piano for instrument names.",
         library_and_prior_evidence="Old branch: the validators' own raw walk read all 2,020 notated files with 0 errors. music21 gives two PartStaff for a two-staff part; partitura gives one Part with number_of_staves 2 (new-library-research A).",
         pitfalls="Two parts both named Piano (a right-hand/left-hand split or a duet: several in the 109-file shortlist); voice plus piano (shortlist Ave Maria, part 'Voix'); unnamed parts; a staff added mid-piece.",
         tests_pass_fail_fool="Pass: a standard grand-staff file -> SUPPORTED. Fail: a voice-plus-piano file -> UNSUPPORTED (extra part). Fool: two parts, each one staff, both named 'Piano' -> UNSUPPORTED, not merged by guess.",
         in_our_files="<staff> element present in 714 of 842 (84.8%), a proxy for one part with two staves",
         used_for="Every row below (precondition); step 4: checking that a generated exercise has the intended layout",
         why_easy="Direct element read; the only decision is to refuse unusual layouts rather than interpret them."),
    dict(id="E02", group="foundation", fact="Bar references and bar lengths",
         chatgpt_ids="form.length (part); integrity.notation-sanity (part)",
         reports="For each measure: position index, printed number (measure@number), implicit flag, notated length against the time signature (full, short, over-full).",
         definition="Notated length of a measure = the largest end time over its voices, from <duration>, <backup> and <forward> in divisions; compared with the time signature in force.",
         implementation="Raw walk (the same logic file_checks.py already uses for its bar check). music21 Measure.number and paddingLeft as the second reader. All later rows report locations with the printed number, so a reader or a Haiku agent can find the bar in the score.",
         library_and_prior_evidence="file_checks.py already flags under-full and over-full interior bars on this pipeline; the old project's raw walk did the same.",
         pitfalls="Printed numbers repeated or with suffixes ('12a'), multi-bar rests, first and second endings sharing numbers, cue-size notes counted into the length.",
         tests_pass_fail_fool="Pass: 4/4 bar of four quarters -> full. Fail: 4/4 bar with three quarters and no rest -> short. Fool: a bar whose second voice has a <forward> instead of rests -> full (largest voice end), not short.",
         in_our_files="all files",
         used_for="Locations in every row; anacrusis (E10); excerpts handed to Haiku agents; step 4 generator output check",
         why_easy="Arithmetic over durations already implemented and tested in file_checks.py."),
    # ---------------------------------------------------------------- notation reads
    dict(id="E03", group="notation", fact="Clefs and clef changes, per staff",
         chatgpt_ids="notation.clefs; notation.clef-change",
         reports="Starting clef of each staff (sign, line, octave change); every change as (bar, staff, from, to, inside the bar or at its start); count of changes per staff.",
         definition="A change is a <clef number=staff> whose sign, line or octave change differs from the clef in force on that staff. A clef equal to the one in force (restated at a system break) is not a change.",
         implementation="Raw walk of <attributes><clef> including attributes in the middle of a measure; a clef without a number attribute applies to staff 1. music21 clef.Clef objects per PartStaff as the second reader.",
         library_and_prior_evidence="Old branch: raw walk validated (clef changes in 145 PDMX ids, 96 inside a bar; same-clef restatements in 50 files not counted). The old app detector read staff 2 as bass and never read the clef, which failed on clef changes. music21 ran on corpus scores: staff 2 of Clara Schumann Op. 1 No. 1 has 14 bass, 7 treble and 1 treble-8va clef objects.",
         pitfalls="Restated clefs; cue clefs; treble-8va or bass-8vb clefs (octave change); a staff that starts in the 'wrong' clef (both staves treble).",
         tests_pass_fail_fool="Pass: corpus Maple Leaf Rag -> clef changes on staff 2 at bars 9 and 13 (as music21 reads it). Fail: a file with only the opening clefs -> 0. Fool: the same treble clef restated at every system -> 0 changes.",
         in_our_files="348 of 842 files have more than two <clef> elements (includes restatements, so an upper bound)",
         used_for="A.1 (both clefs), 6.7 (clef changes in reading), E05 ledger lines (needs the clef in force), step 4 generator check",
         why_easy="Direct read; the only rule is 'changed from the clef in force'."),
    dict(id="E04", group="notation", fact="Ottava lines (8va, 8vb, 15ma)",
         chatgpt_ids="mark.ottava",
         reports="Each span: staff, kind and size, first and last bar, notes inside; spans not closed are listed as UNCLOSED with their start.",
         definition="<octave-shift type='up|down|stop' size='8|15' number='n'> pairs, matched by number within a staff. Notes inside a span are those between start and stop in that staff.",
         implementation="Raw walk; music21 spanner.Ottava as the second reader. In our files music21 imports the notes under an ottava at sounding pitch (Ottava.transposing is False); our probe on 4 candidate files found the same number of spans as the raw <octave-shift> starts in all 4.",
         library_and_prior_evidence="Old branch: own span reading agreed with music21 on 81 of 93 files (exclusive stop); unclosed spans (3 in Malagueña), empty spans and '8va cont.' words occur. Never compared with a printed page.",
         pitfalls="Unclosed or empty spans; '8va' written only as <words> (no span); whether the stop note is inside the span (exclusive vs inclusive).",
         tests_pass_fail_fool="Pass: an 8va over bars 5-6 of staff 1 -> one span, bars 5-6. Fail: no <octave-shift> -> none. Fool: '8va' typed as <words> with no <octave-shift> -> no span; listed under 'ottava words' only.",
         in_our_files="153 of 842 (18.2%)",
         used_for="A.1 (a passage marked 8va), 7.8 (8va in reading), E05 (written position under an 8va)",
         why_easy="Direct read; library and raw reader agreed on our sample."),
    dict(id="E05", group="notation", fact="Ledger lines, per staff",
         chatgpt_ids="pitch.ledger",
         reports="Per staff: notes by number of ledger lines needed (0, 1, 2, 3, 4, 5, more than 5), above and below; the bars of notes with 1-2 and 3+ ledger lines.",
         definition="Written staff position from the clef in force and the written pitch (sounding pitch moved back by any ottava in force, E04). Ledger lines needed = how many lines beyond the five staff lines the note sits on or past: middle C in treble = 1 below; A5 in treble = 1 above; C6 in treble = 2 above; middle C in bass = 1 above; E2 in bass = 1 below.",
         implementation="music21: diatonicNoteNum of the written pitch against clef.lowestLine (treble 31, bass 19): below = (lowestLine - d) // 2 when d < lowestLine, above = (d - topLine) // 2 when d > topLine, with topLine = lowestLine + 8 (checked by hand: treble D4 0, C4 1, B3 1, A3 2; G5 0, A5 1, B5 1, C6 2; bass E2 1, C4 1). Each note of a chord counted; grace notes counted separately. Replaces rung_pieces.py's pitch-range proxy for B.1 and 1.1.",
         library_and_prior_evidence="Old branch: own staff-position geometry validated on named pieces (Satie, Silent Night, We Three Kings); 6 or more ledger lines happen in 97 real files, many where an 8va mark was lost in transcription. The research agent checked a 3-line formula on 4 hand cases (C4 treble 1, A5 treble 1, C4 bass 1, E2 bass 1).",
         pitfalls="A lost 8va gives absurd counts: more than 5 is reported as 'possible missing 8va', not as a reading demand; cross-staff notes use the clef of the staff they are written on; the off-by-one between notes on a ledger line and in the space beyond it (the formula's main risk).",
         tests_pass_fail_fool="Pass: C4 treble 1 below; B3 treble 1 below (space under the first ledger line); D4 treble 0; A5 treble 1 above; B5 treble 1 above; C6 treble 2; E2 bass 1 below; C4 bass 1 above. Fail: notes inside the staff -> 0. Fool: written D6 under an 8va (sounding D7) -> 2 ledger lines, not 5.",
         in_our_files="all files",
         used_for="B.1 (to two ledger lines), 1.1 (ledger lines above and below), reading difficulty, step 4 generator check (no note beyond the ledger lines a level allows)",
         why_easy="Small formula from two library values; the hand-made cases above pin every boundary."),
    dict(id="E06", group="notation", fact="Key signatures and key-signature changes",
         chatgpt_ids="notation.keys",
         reports="Fifths (and mode when written) at the start and at each change, with bar and staff; number of changes.",
         definition="<key><fifths> (and <mode>) per staff (number attribute) or for all staves; a change is a value different from the one in force. Non-traditional keys (<key-step>/<key-alter>) are reported as such.",
         implementation="Raw walk; music21 key.KeySignature as the second reader (some files give the subclass key.Key, so test with isinstance).",
         library_and_prior_evidence="Old branch: validated (Beethoven Symphony 7 four changes; key changes in 55 PDMX ids). The old app detector kept only the first key. music21 on corpus Maple Leaf Rag: -4, -5, -4 at bars 0, 51, 68.",
         pitfalls="Signatures restated at system breaks; cancellation naturals; per-staff keys; the written mode is often missing, so the mode is never inferred here.",
         tests_pass_fail_fool="Pass: Maple Leaf Rag -> -4 (bar 0), -5 (bar 51), -4 (bar 68). Fail: a C major file with one signature -> one entry, 0 changes. Fool: G major restated at every system -> 0 changes.",
         in_our_files="840 of 842",
         used_for="B.4, 1.12 and the scale rungs' keys (which keys a piece is in), level fit (key signature size), step 4 generator check (requested key = written key)",
         why_easy="Direct read; library agreed on the corpus test."),
    dict(id="E07", group="notation", fact="Accidentals as encoded in the file",
         chatgpt_ids="reading.accidental-kinds; reading.accidental-churn; pitch.chromatic (written part only)",
         reports="Per staff: count of <accidental> elements by kind (sharp, flat, natural, double sharp, double flat), how many are cautionary or editorial; accidentals per 100 notes; bars with the most.",
         definition="Only the file's own <accidental> elements: what the file says is printed. Whether a given renderer would draw an accidental is NOT computed (that is the hard part; see pitfalls).",
         implementation="Raw walk of <note><accidental> with its cautionary, editorial and parentheses attributes.",
         library_and_prior_evidence="Old branch: a model of which accidentals are displayed was wrong on 8,543 of 76,813 file-accidental notes (11.1%) against OpenSheetMusicDisplay's render, so the display layer is out of this batch. music21 raised 'incorrect accidental' on one old file (Mozart K. 545 alt). music21 Pitch.accidental.displayStatus exists but reading it as 'printed' is unverified.",
         pitfalls="Exporters that omit <accidental> for printed accidentals or add redundant ones; the count is the file's claim, not the page.",
         tests_pass_fail_fool="Pass: bar with F-sharp then F-natural, both with <accidental> -> 1 sharp, 1 natural. Fail: a C major scale -> 0. Fool: an F-sharp tied over the barline with no <accidental> on the second note -> counted once (as encoded).",
         in_our_files="all files (element counts not yet taken)",
         used_for="A.5 (sharps and flats), 1.1 (occasional accidentals), reading difficulty (accidental rate, one of Sébastien et al.'s seven criteria), step 4 generator check",
         why_easy="Direct read once the display question is left out."),
    dict(id="E08", group="notation", fact="Notes the key signature actually alters",
         chatgpt_ids="key.signature-exercised",
         reports="For each key-signature span: which of the signature's altered letters occur with the signature's alteration, and how often.",
         definition="A note counts when its step is one the signature alters and its alter equals the signature's alter for that step (e.g. F-sharp under one sharp). Notes carrying a different alter (an F-natural) do not count.",
         implementation="music21 KeySignature.accidentalByStep(step) compared with each note's pitch.accidental alter, per key span from E06; or the same from raw <step>/<alter>.",
         library_and_prior_evidence="Old branch: implemented in the app detector (keySignature, detect.ts line 532) but measured only through its failing display model. music21 alteredPitches ran on Maple Leaf Rag (B-flat, E-flat, A-flat, D-flat); the per-note comparison was not run.",
         pitfalls="Non-traditional keys; a signature with no affected notes (e.g. a G major piece with no F at all) is a real result, not an error.",
         tests_pass_fail_fool="Pass: G major melody with F-sharps -> F-sharp counted. Fail: G major piece without any F -> 0 (signature not exercised). Fool: an F-natural with an explicit natural in G major -> not counted.",
         in_our_files="all files",
         used_for="B.4 and 1.12 (key signatures met in pieces), step 4 generator check (an exercise in G that uses F-sharp)",
         why_easy="One comparison per note from library values."),
    dict(id="E09", group="notation", fact="Time signatures, changes and metre class",
         chatgpt_ids="notation.times; metre.class",
         reports="Each signature with its bar; number of changes; class of each: simple (2, 3, 4 beats), compound (numerator 6, 9 or 12 over 4, 8 or 16), irregular (5, 7, 11 and others, and composite numerators like 3+2); 'no time signature' when absent.",
         definition="A change is a signature different from the one in force. Class from the numerator and denominator only, by the rule above (6/4 is compound duple; 3/8 is simple triple). Grouping of irregular metres (2+3 or 3+2) is not decided unless the numerator is written as a sum.",
         implementation="Raw <time><beats>/<beat-type> (with <senza-misura> and symbol attributes); music21 meter.TimeSignature.classification as the second reader.",
         library_and_prior_evidence="Old branch: music21 and partitura plain reads equal the raw reader on all 187 changes in 49 items. Gnossienne No. 1 has no <time>; partitura returns an empty list. Old detector problems were in classing a change as a device or pickup, not in reading it.",
         pitfalls="Restatements; a pickup written as its own short signature at the start (reported as 'possible pickup signature'); cadenza bars; cut and common time symbols (read the numbers, keep the symbol).",
         tests_pass_fail_fool="Pass: 6/8 -> compound; 3/4 then 2/4 at bar 9 -> 1 change. Fail: 4/4 throughout -> 0 changes, simple. Fool: 4/4 restated at bar 17 -> 0 changes; 3/8 -> simple, not compound.",
         in_our_files="838 of 842",
         used_for="A.3 (2/4), B.2 (a change of time signature), 1.4 (6/8), 3.3 (12/8 and changing metres), 6.7 (9/8, 5/8, 5/4), 7.8 (7/8, 7/4), step 4 generator check",
         why_easy="Direct read; two libraries matched the raw reader on every change tested."),
    dict(id="E10", group="notation", fact="Anacrusis (pickup bar)",
         chatgpt_ids="mark.anacrusis",
         reports="Whether the first bar is shorter than the signature, its length, the implicit flag, and the last bar's length (a classical pickup is often balanced by a short last bar).",
         definition="First measure's notated length (E02) less than the time signature's length, or measure@implicit='yes'. Both lengths are reported; nothing else is decided.",
         implementation="From E02. music21 Measure.paddingLeft as the second reader (corpus Maple Leaf Rag bar 0: paddingLeft 1.5, duration 0.5 of 2.0).",
         library_and_prior_evidence="Old branch: validated on 5 named items (Away in a Manger one quarter of 3/4; Alexander's Ragtime Band 2 of 4; Für Elise one eighth of 3/8; two full-bar starts).",
         pitfalls="A first bar that is short only because a rest was omitted looks like a pickup; the implicit flag is reported so the two cases can be told apart where the file sets it.",
         tests_pass_fail_fool="Pass: Away in a Manger (shortlist file 002) -> 1 quarter of 3. Fail: a piece starting on a full bar -> no pickup. Fool: first bar with one voice full and the other missing its rest -> full (largest voice).",
         in_our_files="all files",
         used_for="A.3 (the upbeat), reading rungs, step 4 generator check",
         why_easy="Comes free from E02."),
    dict(id="E11", group="notation", fact="Note and rest values, dots and ties, per staff",
         chatgpt_ids="rhythm.values; rhythm.ties; rhythm.silence (rest counts only)",
         reports="Per staff: counts of notes and of rests by written type (whole to 32nd and shorter), dotted and double-dotted counts, tie chains (count, how many cross a barline), the shortest written value, and bars where the written type disagrees with the duration.",
         definition="Written <type> and <dot> of each non-grace, non-cue note and rest; a tie chain is a run of notes linked by <tie type='start'/'stop'> (two tied notes are one chain, two written notes).",
         implementation="Raw walk; music21 duration.type and dots as the second reader; ties from <tie> (sound) with <tied> (notation) as a check.",
         library_and_prior_evidence="Old branch: values validated over 2,020 files; every value shorter than a 128th sat in a bar that also carries a quantisation ratio (a PDMX re-export artefact); cue-size notes kept in 26 files. music21 and partitura agreed on tie starts in a corpus file (4 and 4).",
         pitfalls="Notes without <type> (derive from duration and report); cue notes; re-export artefacts with odd values (reported, not used for difficulty); grace notes are counted in E14, not here.",
         tests_pass_fail_fool="Pass: bar of four eighths -> 4 eighths. Fail: bar of half notes -> no eighths. Fool: a quarter tied to an eighth -> one quarter, one eighth, one tie chain; not a dotted quarter.",
         in_our_files="ties present in 575 of 842 (68.3%)",
         used_for="A.3 (rests, eighths), B.2 (eighth patterns), 2.4 (sixteenths), level fit (no sixteenths at B), difficulty (shortest value, share of short values), step 4 generator check",
         why_easy="Direct read; replaces the duration counting in rung_pieces.py with a tested one."),
    dict(id="E12", group="notation", fact="Dotted figures in simple time",
         chatgpt_ids="rhythm.dotted-quarter",
         reports="Per staff: count and bars of dotted quarter followed by an eighth, and of dotted eighth followed by a sixteenth, in simple metres.",
         definition="Two consecutive notes or rests in the same voice and staff: (dotted quarter, eighth) or (dotted eighth, sixteenth), in a bar whose metre class (E09) is simple. In compound time a dotted quarter is the beat, not the figure, so compound bars are excluded.",
         implementation="Per-voice sequence from the raw walk or music21; pairs read from E11 values.",
         library_and_prior_evidence="Old app detector (dottedQuarters, detect.ts line 416) counted simple time only; validated on 4 items (Für Elise 12 dotted-eighth pairs). rung_pieces.py already counts both figures without the simple-time rule.",
         pitfalls="The eighth before the dotted quarter (reverse figure) is a different figure and not counted; a dotted quarter tied into an eighth.",
         tests_pass_fail_fool="Pass: 4/4 bar 'dotted quarter, eighth, half' -> 1. Fail: even quarters -> 0. Fool: 6/8 bar of two dotted quarters -> 0.",
         in_our_files="all files",
         used_for="B.2 (dotted quarter-eighth), 2.4 (dotted eighth-sixteenth), step 4 generator check",
         why_easy="A pair lookup over E11 with one metre condition."),
    dict(id="E13", group="notation", fact="Triplets and other tuplets",
         chatgpt_ids="rhythm.triplets; rhythm.tuplets-other",
         reports="Per staff: groups by ratio (3:2, 6:4, 5:4, 2:3 duplets and others), notes per group, bars.",
         definition="A group is a printed bracket: <tuplet type='start'> ... <tuplet type='stop'> enclosing 2 or more notes whose <time-modification> ratio is not 1. Ratios on notes with no bracket element are not counted (see evidence).",
         implementation="Raw walk; music21 duration.tuplets as the second reader (corpus Clara Schumann Op. 1 No. 1: music21 66 notes at 3:2; partitura 22 groups; they agree).",
         library_and_prior_evidence="Old branch: raw <time-modification> alone included re-export artefacts (77 distinct ratios, e.g. 160:107); reading only closed brackets of 2 or more notes kept 14 of 14 real figures and dropped 21 of 21 artefacts, and lost 1 of 231 3:2 groups.",
         pitfalls="Unclosed brackets (10 in the old catalogue); nested tuplets; files that encode triplets with ratios but no <tuplet> element (missed by this definition; reported as 'unbracketed ratios' for review).",
         tests_pass_fail_fool="Pass: three eighths under a 3:2 bracket -> one triplet group. Fail: plain eighths -> 0. Fool: a 160:107 ratio with no bracket -> 0 groups, listed under unbracketed ratios.",
         in_our_files="234 of 842 (27.8%)",
         used_for="1.4 (triplets), 2.4 (triplets), BL.4 (triplet licks), 6.7 (triplets in reading), difficulty (tuplet share; one of Sébastien et al.'s criteria), step 4 generator check",
         why_easy="Direct read with the artefact rule the old project already measured."),
    dict(id="E14", group="notation", fact="Grace notes",
         chatgpt_ids="mark.ornament (grace part); texture.crushed-note (the grace note only)",
         reports="Per staff: count, slashed (acciaccatura) versus unslashed (appoggiatura), runs of consecutive grace notes and their longest length, bars.",
         definition="Notes with a <grace> element; slash='yes' marks the slashed kind. A run is consecutive grace notes before one main note.",
         implementation="Raw walk; music21 duration.isGrace as the second reader (corpus Clara Schumann Op. 1 No. 3: 39 in both music21 and partitura). Do not use partitura's note_array with grace notes included (it crashed in 1.9.0).",
         library_and_prior_evidence="Old branch: 247 real items carry <grace>; runs of 6 or more occur in Chopin files (written-out flourishes).",
         pitfalls="Cue-size notes that are not <grace>; long grace runs are a different thing from an ornamental grace note and are reported as runs.",
         tests_pass_fail_fool="Pass: one slashed grace before a quarter -> 1 slashed. Fail: no <grace> -> 0. Fool: small cue-size notes without <grace> -> 0.",
         in_our_files="266 of 842 (31.6%)",
         used_for="2.6 (grace notes), 3.4 (appoggiatura), BL.6 (crushed notes), difficulty, step 4 generator check",
         why_easy="Direct read; two libraries agreed on the corpus test."),
    dict(id="E15", group="notation", fact="Ornament signs (trill, mordent, turn)",
         chatgpt_ids="mark.ornament",
         reports="Per staff: counts by kind (trill-mark, wavy-line without a trill mark, mordent, inverted mordent, turn, inverted or delayed turn, schleifer, shake, other), bars.",
         definition="Children of <notations><ornaments>; <tremolo> inside ornaments is E17, not here.",
         implementation="Raw walk; music21 note.expressions (Trill, Mordent, InvertedMordent, Turn, ...) as the second reader (corpus Op. 1 No. 3: Turn 5, Trill 2).",
         library_and_prior_evidence="Old branch: no measured finding for ornament signs; a SMuFL glyph was once misread as a fingering. rung_pieces.py counts ornaments without kinds.",
         pitfalls="'tr' typed as <words>; <other-ornament> with a SMuFL glyph (reported as other).",
         tests_pass_fail_fool="Pass: a trill mark on a half note -> 1 trill. Fail: none -> 0. Fool: 'tr' as <words> -> 0 trills, listed under text.",
         in_our_files="trill-mark 129 (15.3%), mordent 42 (5.0%), inverted mordent 89 (10.6%), turn 17 (2.0%) of 842",
         used_for="3.4 (trill, mordent), difficulty, step 4 generator check",
         why_easy="Direct read."),
    dict(id="E16", group="notation", fact="Arpeggiated-chord sign",
         chatgpt_ids="mark.arpeggiate",
         reports="Per staff: chords with <arpeggiate> (direction when given) and with <non-arpeggiate>, bars.",
         definition="<notations><arpeggiate> on any note of a chord marks that chord.",
         implementation="Raw walk; music21 expressions.ArpeggioMark as the second reader (ran on corpus Op. 1 No. 1: 6).",
         library_and_prior_evidence="Old branch: no finding (its 'arpeggio' rule was a broken-chord pattern, a different thing).",
         pitfalls="Arpeggio spanning both staves (one sign per staff in the file).",
         tests_pass_fail_fool="Pass: wavy line on a 4-note chord -> 1. Fail: plain chord -> 0. Fool: a broken chord written out in eighths -> 0 (that is a pattern, not the sign).",
         in_our_files="153 of 842 (18.2%)",
         used_for="E37 (a wide chord marked to be rolled is not a stretch), difficulty, 8.4 performance marks",
         why_easy="Direct read."),
    dict(id="E17", group="notation", fact="Tremolo marks",
         chatgpt_ids="mark.tremolo",
         reports="Per staff: single-note and two-note tremolos with number of strokes, bars.",
         definition="<ornaments><tremolo type='single|start|stop|unmeasured'>; the text value is the number of strokes.",
         implementation="Raw walk; music21 expressions.Tremolo as the second reader (ran on corpus Op. 1 No. 4: 24).",
         library_and_prior_evidence="Old branch: read through partitura ornaments; no measured count.",
         pitfalls="Measured repeated notes written out (that is E40's repeated notes, not a tremolo sign).",
         tests_pass_fail_fool="Pass: three-stroke tremolo on a half note -> 1 single, 3 strokes. Fail: none -> 0. Fool: written-out 32nd repetitions -> 0.",
         in_our_files="19 of 842 (2.3%)",
         used_for="BL.6 (tremolo), difficulty",
         why_easy="Direct read."),
    dict(id="E18", group="notation", fact="Glissando and slide marks",
         chatgpt_ids="mark.glissando",
         reports="Per staff: glissando and slide spans with start and end notes, bars; 'gliss.' words listed separately.",
         definition="<notations><glissando> and <slide> start/stop pairs.",
         implementation="Raw walk; music21 spanner.Glissando as the second reader (only tested on a constructed object; no corpus piano file has one).",
         library_and_prior_evidence="Old branch: no finding.",
         pitfalls="'gliss.' typed as words with no span; a span with no stop.",
         tests_pass_fail_fool="Pass: a glissando from C4 to C6 -> 1 span. Fail: none -> 0. Fool: 'gliss.' as words only -> 0 spans, listed as text.",
         in_our_files="glissando 2, slide 4 of 842",
         used_for="3.4 (glissando)",
         why_easy="Direct read; rare, so low value."),
    dict(id="E19", group="notation", fact="Fermatas",
         chatgpt_ids="mark.fermata",
         reports="Fermatas on notes, rests and barlines, with bar and staff.",
         definition="<notations><fermata> on a note or rest, and <barline><fermata>.",
         implementation="Raw walk; music21 expressions.Fermata as the second reader (ran on corpus Schoenberg Op. 19/2: 2).",
         library_and_prior_evidence="Old branch: read through partitura; no measured count.",
         pitfalls="The same fermata written on both staves (count per staff and per time position).",
         tests_pass_fail_fool="Pass: fermata on the final chord -> 1. Fail: none -> 0. Fool: fermata on both staves at the same beat -> 1 time position, 2 marks.",
         in_our_files="305 of 842 (36.2%)",
         used_for="A.6 (fermata), tempo-change list (E26)",
         why_easy="Direct read."),
    dict(id="E20", group="notation", fact="Dynamic marks",
         chatgpt_ids="mark.dynamics",
         reports="Each mark (pppp to ffff, mp, mf, sf, sfz, sffz, fz, fp, rf, rfz, other) with bar and staff; the set of levels used; softest and loudest; time positions where the two staves have different dynamics.",
         definition="Children of <direction><direction-type><dynamics> (staff from the direction's <staff>) and of <notations><dynamics>. Words such as 'dolce' or 'cresc.' are not dynamics.",
         implementation="Raw walk; music21 dynamics.Dynamic as the second reader (corpus Op. 1 No. 1: mf 3, f 3, p 1). Do not use partitura for this: it classed the word 'calando' as a dynamic.",
         library_and_prior_evidence="Old branch: sf, sfz and fz counts read through partitura equalled the raw counts (Moonlight III 49, Hall of the Mountain King 39).",
         pitfalls="Dynamics typed as words ('p dolce'); <other-dynamics>; a direction without a staff number (applies to staff 1).",
         tests_pass_fail_fool="Pass: p at bar 1 and f at bar 9 -> 2 marks, range p to f. Fail: none -> empty. Fool: 'dolce' words -> not a dynamic.",
         in_our_files="435 of 842 (51.7%)",
         used_for="A.6 (loud and soft), B.8 (pp), 1.6 (mp, mf), 3.4 (sforzando), 7.4 (different dynamics in each hand), difficulty, step 4 generator check",
         why_easy="Direct read."),
    dict(id="E21", group="notation", fact="Hairpins and cresc./dim. words",
         chatgpt_ids="mark.hairpin",
         reports="Wedges (crescendo, diminuendo) with staff and bars; 'cresc.', 'dim.', 'decresc.' words listed separately with bars.",
         definition="<wedge type='crescendo|diminuendo|stop' number>; words matched against a closed list (cresc, crescendo, dim, diminuendo, decresc, decrescendo, with or without a full stop).",
         implementation="Raw walk; music21 dynamics.Crescendo and Diminuendo as the second reader (corpus Op. 1 No. 1: 2 crescendos). partitura found none on the same file, so it is not used.",
         library_and_prior_evidence="Old branch: crescendo read through partitura; diminuendo apparently missing there.",
         pitfalls="Unclosed wedges; a wedge on one staff meant for both.",
         tests_pass_fail_fool="Pass: a crescendo wedge over bars 3-4 -> 1. Fail: none -> 0. Fool: 'cresc.' words -> 0 wedges, 1 word.",
         in_our_files="347 of 842 (41.2%)",
         used_for="A.6, B.8 and 1.6 (crescendo, diminuendo, hairpins), step 4 generator check",
         why_easy="Direct read; music21 matched on the corpus test."),
    dict(id="E22", group="notation", fact="Articulation marks",
         chatgpt_ids="mark.articulation",
         reports="Per staff: counts by kind (staccato, staccatissimo, tenuto, detached-legato, accent, strong accent, spiccato, breath mark, other), bars.",
         definition="Children of <notations><articulations>.",
         implementation="Raw walk; music21 note.articulations as the second reader (corpus Op. 1 No. 1: staccato 12, accent 8 in music21 and partitura alike).",
         library_and_prior_evidence="Old branch: accents read through partitura (accent items 101 PDMX).",
         pitfalls="Articulations typed as words; a staccato on every note of a chord counted once per chord (report both).",
         tests_pass_fail_fool="Pass: four staccato quarters -> 4 staccatos. Fail: none -> 0. Fool: a 3-note chord with one staccato -> 1 chord.",
         in_our_files="staccato 315 (37.4%), accent 264 (31.4%), tenuto 87 (10.3%) of 842",
         used_for="A.2 (staccato), A.6 and 1.6 (accents), step 4 generator check",
         why_easy="Direct read; two libraries agreed."),
    dict(id="E23", group="notation", fact="Slurs",
         chatgpt_ids="mark.slur",
         reports="Per staff: number of slurs, notes under slurs (share of all notes), average notes per slur, bars; slurs that join two notes of the same pitch listed separately (likely a mis-encoded tie).",
         definition="<slur type='start|stop' number> paired by number within a staff and voice.",
         implementation="Raw walk; music21 spanner.Slur as the second reader.",
         library_and_prior_evidence="Old branch: no finding. rung_pieces.py counts music21 Slur objects in the bars used.",
         pitfalls="Dangling starts or stops; slurs crossing staves; same-pitch slurs.",
         tests_pass_fail_fool="Pass: a slur over four notes -> 1 slur, 4 notes. Fail: none -> 0. Fool: a 'slur' between two Cs of the same pitch -> listed as possible tie.",
         in_our_files="510 of 842 (60.6%)",
         used_for="A.2 (legato), B.8 (phrase marks), 1.6 (slurs), step 4 generator check",
         why_easy="Direct read."),
    dict(id="E24", group="notation", fact="Pedal marks",
         chatgpt_ids="mark.pedal; mark.pedal-kind",
         reports="Pedal events (start, change, stop) with bars; pedalled spans; share of bars under pedal; sostenuto; una corda and tre corde from words.",
         definition="<direction-type><pedal type='start|stop|change|continue|sostenuto|resume|discontinue'>; words matched to a closed list for una corda / u.c. / tre corde / con pedale / senza pedale.",
         implementation="Raw walk; music21 expressions.PedalMark as the second reader. Our probe on 4 candidate files: music21 32 against 33 raw starts in one file, equal in the other three, so the raw count is the reference.",
         library_and_prior_evidence="Old branch: no finding. rung_pieces.py counts any object whose class name contains 'pedal' (replaced by this row).",
         pitfalls="'Ped.' as words only; pedal lines with no stop; marks on staff 1 applying to the whole piano.",
         tests_pass_fail_fool="Pass: Ped. at bar 1, change at bar 2, release at bar 3 -> 1 span with 1 change. Fail: none -> 0. Fool: 'con pedale' words with no marks -> 0 events, listed as text.",
         in_our_files="179 of 842 (21.3%)",
         used_for="A.6 (first pedal), B.8 (connected pedal), 1.6 (pedalling), 7.4 (una corda), J.5 (pedal in tunes), step 4 generator check",
         why_easy="Direct read."),
    dict(id="E25", group="notation", fact="Tempo marks",
         chatgpt_ids="mark.tempo-text",
         reports="Metronome marks (beat unit, dots, per minute, bar); <sound tempo> values (quarter notes per minute) with bars; the opening tempo word matched to a closed list (Grave to Prestissimo); a tempo map in quarter notes per minute.",
         definition="<metronome><beat-unit>, <beat-unit-dot>, <per-minute>; <sound tempo> is quarter notes per minute by the MusicXML definition. A dotted-quarter = 60 mark becomes 90 quarters per minute. A tempo word alone gives no number (a default number per word would be a guess).",
         implementation="Raw walk; music21 tempo.MetronomeMark.getQuarterBPM and metronomeMarkBoundaries as the second reader. partitura returned no tempo directions on a corpus file that has them, so it is not used.",
         library_and_prior_evidence="Old branch: validated on named items (Op. 10 No. 1 quarter = 176; Asturias has no metronome mark but <sound tempo> 144).",
         pitfalls="A metronome mark and a <sound tempo> that disagree (report both); per-minute ranges ('100-108'); marks that are words only.",
         tests_pass_fail_fool="Pass: quarter = 120 -> 120. Fail: no tempo at all -> UNKNOWN. Fool: dotted quarter = 60 in 6/8 -> 90 quarters per minute, not 60.",
         in_our_files="metronome 471 (55.9%), sound tempo 602 (71.5%) of 842",
         used_for="Notes per second (D01), step 4 generator check (exercise at the requested tempo)",
         why_easy="Direct read plus one unit conversion."),
    dict(id="E26", group="notation", fact="Tempo-change words",
         chatgpt_ids="mark.tempo-change; notation.swing-mark",
         reports="Each rit., rall., accel., a tempo, Tempo I, rubato, allargando, stringendo, meno mosso, più mosso, and swing or straight-eighths directions (words, or the <swing> element), with bar; unrecognised direction words listed unclassified.",
         definition="<direction-type><words> matched case-insensitively to the closed list above and its abbreviations (rit., ritard., ritardando, rall., rallentando, accel., accelerando). Anything else is listed as 'other words', never classified.",
         implementation="Raw walk over <words>; music21 TextExpression as the second reader (music21 does not turn these into RitardandoSpanner from XML).",
         library_and_prior_evidence="Old branch: validated on named items (Op. 9 No. 2 'poco rit.', 'a tempo'); French words ('Animez un peu') stayed unclassified.",
         pitfalls="Words in other languages; words split across two directions.",
         tests_pass_fail_fool="Pass: 'rit.' at bar 15, 'a tempo' at bar 17 -> 2 entries. Fail: none -> empty. Fool: 'ritmico' (a character word) -> other words, not a ritardando.",
         in_our_files="words present in 553 of 842 (65.7%); tempo-change share not counted yet",
         used_for="A.6 (ritardando), 7.8 (tempo changes in reading), J.1 and 2.4 (a swing direction in a piece), step 4 generator check",
         why_easy="Closed word list; unknown words are listed, not guessed."),
    dict(id="E27", group="notation", fact="Fingering numbers",
         chatgpt_ids="mark.fingering",
         reports="Per staff: share of notes with a <fingering>, substitutions (e.g. 3-1), bars; digit-only <words> or lyrics listed separately as possible fingering.",
         definition="<notations><technical><fingering> (with substitution and alternate attributes).",
         implementation="Raw walk; music21 articulations.Fingering as the second reader. partitura keeps them on note.technical (its iter_all found none).",
         library_and_prior_evidence="Old branch: validated (Hanon 1 right hand 61 digits; Mozart K. 2 easy had 0 <fingering> but 71 digit words).",
         pitfalls="Fingering typed as words or lyrics; '0'; stacked chord fingerings.",
         tests_pass_fail_fool="Pass: five fingered notes -> share 5 of n. Fail: none -> 0. Fool: digits typed as lyrics -> 0 fingerings, listed as possible fingering text.",
         in_our_files="103 of 842 (12.2%)",
         used_for="Information for lessons and Haiku agents (scale and early-position pieces: P.4, A.2, B.4, 1.2); step 4 generator check (fingering printed where the exercise promises it)",
         why_easy="Direct read."),
    dict(id="E29", group="notation", fact="Chord symbols",
         chatgpt_ids="notation.chord-symbols; harmony.rhythm and harmony.chord-vocabulary (from symbols only)",
         reports="Number of chord symbols, distinct symbols, kinds (major, minor, dominant 7th, other), slash basses, N.C., duplicates removed (the same symbol on both staves at the same time), symbols per bar, bars.",
         definition="<harmony> with <root>/<root-step>, <root-alter>, <kind>, <bass>; chord names typed as <words> are not counted here.",
         implementation="Raw walk; music21 harmony.ChordSymbol as the second reader for <harmony> elements only.",
         library_and_prior_evidence="Old branch: own reader and music21's <harmony> reader equal on 459 of 460 items; duplicates on two staves were common (4,984 down to 3,619 after removing them). music21's text parser misread 'Bb7' as root B, so text chord names are left out.",
         pitfalls="Duplicates on both staves; guitar-frame symbols; Roman-numeral or function kinds.",
         tests_pass_fail_fool="Pass: C, F, G7 over three bars -> 3 symbols, 3 distinct. Fail: none -> 0. Fool: 'Bb7' typed as words -> 0 symbols here.",
         in_our_files="39 of 842 (4.6%)",
         used_for="B.7 (first lead sheet: a piece with chord symbols), 4.3, 5.3, J.1, J.3, PR.1 (lead sheets), step 4 generator check",
         why_easy="Direct read; the library agreed on 459 of 460."),
    dict(id="E30", group="notation", fact="Slash notation",
         chatgpt_ids="notation.slash-rhythm",
         reports="Slash noteheads and slash measure styles, bars.",
         definition="<notehead>slash</notehead>; <measure-style><slash> or <beat-repeat>.",
         implementation="Raw walk.",
         library_and_prior_evidence="Old branch: validated (So Danço Samba 28 slashes; no measure-style slash anywhere).",
         pitfalls="None known beyond rarity.",
         tests_pass_fail_fool="Pass: four slash noteheads in a bar -> 4. Fail: normal noteheads -> 0. Fool: x noteheads -> 0.",
         in_our_files="1 of 842",
         used_for="Comping charts (B.7, J and PR rungs); very rare in our files",
         why_easy="Direct read; low value."),
    dict(id="E31", group="notation", fact="Repeat signs, endings and jump marks (presence only)",
         chatgpt_ids="mark.repeat (presence part)",
         reports="Forward and backward repeat barlines with bars, endings with numbers and bars, D.C., D.S., Fine, Coda, Segno marks with bars.",
         definition="<barline><repeat direction>, <ending number type>, <segno>, <coda>, and <sound dacapo|dalsegno|fine|tocoda> plus words matched to D.C./D.S./Fine/Coda. The order in which the bars are played is NOT computed in this batch.",
         implementation="Raw walk; music21 bar.Repeat and spanner.RepeatBracket as the second reader.",
         library_and_prior_evidence="Old branch: reading the signs is easy; expanding them is not: on 81 disputed files music21's expander was right on 27 and partitura's on 21, while the old project's own unroller reached 80 of 81 only after a coda fix. Expansion is left for a later batch.",
         pitfalls="Jumps written only as words; endings without numbers.",
         tests_pass_fail_fool="Pass: a backward repeat at bar 8 with endings 1 and 2 -> listed. Fail: none -> empty. Fool: a double barline (not a repeat) -> not listed.",
         in_our_files="repeat 298 (35.4%), ending 101 (12.0%), segno 6, coda 6 of 842",
         used_for="1.7 (form: whether repeats exist, not what the form is), step 4 generator check; played length later",
         why_easy="Direct read once expansion is left out."),
    dict(id="E32", group="notation", fact="Length in bars",
         chatgpt_ids="form.length (written part)",
         reports="Number of measures, number excluding a pickup, total notated length in quarter notes (repeats not expanded).",
         definition="Count of <measure> elements in the part; length from E02.",
         implementation="Raw walk; music21 measure count as the second reader.",
         library_and_prior_evidence="shortlist.csv and the file checks already report bars this way.",
         pitfalls="Multi-bar rests count as one measure each in the file (correct).",
         tests_pass_fail_fool="Pass: 16 measures -> 16. Fail: n/a. Fool: a pickup plus 16 full bars -> 17 measures, 16 excluding the pickup.",
         in_our_files="all files",
         used_for="Level fit (at most 48 bars at Level B), difficulty (length; one of Sébastien et al.'s criteria), step 4 generator check",
         why_easy="A count."),
    # ---------------------------------------------------------------- pitch statistics
    dict(id="E33", group="pitch", fact="Pitch range per staff, whole piece and per bar",
         chatgpt_ids="hands.per-bar-range (per staff, not per hand)",
         reports="Per staff: lowest and highest sounding pitch, span in semitones; the same per bar; grace notes included and excluded.",
         definition="Sounding MIDI pitch of every non-cue note written on the staff (ottava already applied, E04).",
         implementation="music21 pitches per PartStaff, or analysis.discrete.Ambitus().getPitchSpan; partitura note_array pitch and staff fields as the second reader (corpus Op. 1 No. 1 staff 1: E-flat4 to E-flat7 in both).",
         library_and_prior_evidence="Old branch: validated (Asturias compass 31-103). Range bounds it used came from jSymbolic as kept in music21.",
         pitfalls="Staff is not hand: notes written on one staff and played by the other hand are counted on their staff. This row never says 'hand'.",
         tests_pass_fail_fool="Pass: right hand C4-G4 -> 7 semitones. Fail: n/a. Fool: a note under an 8va written C6 -> counted at C7.",
         in_our_files="all files",
         used_for="P.4 and A.2 (five-finger range), A.1 and B.1 (reading range), difficulty (range), level fit, step 4 generator check (range limits)",
         why_easy="Min and max over library pitches; two libraries agreed."),
    dict(id="E34", group="pitch", fact="Pitch inventory and black-key share",
         chatgpt_ids="pitch.inventory; pitch.black-key-share",
         reports="Per staff and overall: distinct pitches, distinct pitch classes, share of notes on black keys (pitch classes 1, 3, 6, 8, 10), counting every note of every chord.",
         definition="Attacked notes (tie continuations not counted again); grace notes excluded.",
         implementation="music21 or partitura pitches; own one-line count.",
         library_and_prior_evidence="Old branch: validated (G-flat arpeggio share 1.0; G-flat five-finger 0.778). The research agent's quick share left chord notes out; this definition includes them.",
         pitfalls="Enharmonic spelling does not matter here (C-flat is a white key).",
         tests_pass_fail_fool="Pass: C major scale -> 0 black. Fail: n/a. Fool: a chord C-E-flat-G -> 1 of 3 black, counted inside the chord.",
         in_our_files="all files",
         used_for="P.1 (black-key groups), P.4 (white-key positions), difficulty, step 4 generator check",
         why_easy="A count."),
    dict(id="E35", group="pitch", fact="Pitch entropy",
         chatgpt_ids="reading.pitch-entropy",
         reports="Per staff and overall: Shannon entropy in bits of the pitch distribution and of the pitch-class distribution.",
         definition="H = -sum(p log2 p) over the shares of attacked notes per pitch (or pitch class); tie continuations and grace notes excluded.",
         implementation="numpy over the note list (muspy has the same one-line function; adding it as a dependency is not worth it).",
         library_and_prior_evidence="Old branch: validated with an independent implementation (Hall of the Mountain King right hand 5.42; ostinato fifths 1.0).",
         pitfalls="Longer pieces have more varied pitches; the statistic is reported with the note count.",
         tests_pass_fail_fool="Pass: two pitches equally often -> 1.0. Fail: one pitch only -> 0. Fool: four pitches, one taking 97% -> well below 2.",
         in_our_files="all files",
         used_for="Difficulty only",
         why_easy="A formula."),
    # ---------------------------------------------------------------- per-staff texture
    dict(id="E36", group="texture", fact="Notes struck together, per staff",
         chatgpt_ids="texture.block-chords (per staff); interval.harmonic",
         reports="Per staff: histogram of how many notes start together (1, 2, 3, 4, 5 or more), the largest, the bars with 4 or more; harmonic intervals of two-note attacks (in semitones).",
         definition="Notes on the same staff with the same onset, across all written voices; grace notes and tie continuations excluded. The largest chord within one written voice is reported too (the two differed on 23 of the 109 shortlist files).",
         implementation="Group the note list by (staff, onset); music21 chord.Chord size per voice as the second view.",
         library_and_prior_evidence="ChatGPT's shortlist review used the per-staff definition; my recount per voice agreed on bars, notes and grace notes on all 109 files, and differed on the largest chord on 23 because of the definition.",
         pitfalls="Two voices on one staff may be split between the hands; stacks of 7 or more on one staff usually mean duplicated voices (Clair de lune had 8 in one voice), reported as 'possible encoding fault'.",
         tests_pass_fail_fool="Pass: a C-E-G chord -> one 3-note attack. Fail: single notes -> all 1. Fool: two voices on staff 1 starting a 2-note chord and a single note together -> 3 per staff, 2 per voice.",
         in_our_files="chord element present in 722 of 842 (85.7%)",
         used_for="Level fit (at most 3-note chords at Level B), B.5 (triads in pieces), difficulty (polyphony; one of Sébastien et al.'s criteria), encoding-fault flag, step 4 generator check",
         why_easy="A group-by over the note list."),
    dict(id="E37", group="texture", fact="Span of notes struck together, per staff",
         chatgpt_ids="technique.span (per staff)",
         reports="Per staff: largest and median span in semitones of notes starting together; bars with spans over 12 and over 14; whether the chord carries an arpeggio sign (E16).",
         definition="Highest minus lowest pitch in each per-staff attack from E36.",
         implementation="From E36.",
         library_and_prior_evidence="Old branch: a reach flag over 16 semitones was validated as a flag only (43 PDMX files flagged).",
         pitfalls="A span on one staff may be shared between hands; a rolled chord is not a stretch; neither is decided here, only reported.",
         tests_pass_fail_fool="Pass: C4-C5 -> 12. Fail: single notes -> 0. Fool: a 10th marked with an arpeggio sign -> 16 reported with the arpeggio flag.",
         in_our_files="all files",
         used_for="Difficulty (stretch), playability flags, level fit",
         why_easy="Subtraction over E36."),
    dict(id="E38", group="texture", fact="Octaves on one staff",
         chatgpt_ids="texture.octaves (simultaneous part)",
         reports="Per staff: attacks whose lowest and highest notes are exactly 12 semitones apart (with at most one note between), the longest run of consecutive octave attacks, bars.",
         definition="From E36 attacks: highest - lowest = 12 and at most 3 notes.",
         implementation="From E36 (music21 hasAnyRepeatedDiatonicNote returned 0 on a corpus file that has octaves, so it is not used).",
         library_and_prior_evidence="Old branch: no finding.",
         pitfalls="Broken octaves (alternating) are a pattern, not this row.",
         tests_pass_fail_fool="Pass: C3+C4 -> octave. Fail: C3+G3 -> not. Fool: C3+E3+G3+C4 (4 notes) -> not an octave attack.",
         in_our_files="all files",
         used_for="Difficulty (octave passages), RG.4 and BL.6 (octave textures)",
         why_easy="Arithmetic over E36."),
    dict(id="E39", group="texture", fact="Melodic leaps and jumps, per staff",
         chatgpt_ids="interval.melodic; technique.leap-size (per staff)",
         reports="Per staff: histogram of intervals in semitones between consecutive attacks, largest leap, and the count of jumps over 12 semitones made in less than 2 beats.",
         definition="The outer line of each staff by convention: the top note of each attack on staff 1 and the bottom note on staff 2; interval = pitch difference between consecutive attacks of that line. Also per written voice where a staff has more than one voice. The jump count follows Sébastien et al. (2012): over 12 semitones within 2 beats.",
         implementation="From the note list sorted by onset per staff.",
         library_and_prior_evidence="Old branch: no measured finding (the app detector counted steps, skips and leaps on chord tops and bottoms). music21 melodicIntervals and its jSymbolic interval features mix both staves, so per-staff is our own.",
         pitfalls="With two voices on a staff, the top line jumps between voices; the per-voice figure is reported beside it. This is a statistic, not a melody.",
         tests_pass_fail_fool="Pass: C4-D4-E4 -> two steps of 2. Fail: one repeated note -> 0. Fool: an Alberti figure on staff 2 -> the bottom line stays put on repeated low notes; the jumps come from the upper notes only in the per-voice figure.",
         in_our_files="all files",
         used_for="A.1 (intervals to the 5th), B.1 (intervals to the octave), difficulty (hand displacement), step 4 generator check (interval limits)",
         why_easy="Differences over a sorted list; the convention is stated, not inferred."),
    dict(id="E40", group="texture", fact="Repeated notes and runs of equal values",
         chatgpt_ids="rhythm.repeated-notes; rhythm.equal-stream",
         reports="Per staff and voice: longest run of the same pitch struck again and again; longest run of consecutive attacks with the same written value (count, value, bars).",
         definition="Runs inside one written voice, broken by a rest, a tie or a different value.",
         implementation="From the per-voice note list.",
         library_and_prior_evidence="Old branch: validated (Asturias right hand repeated-note run 96; Hanon 20 run of 241 sixteenths).",
         pitfalls="Voices badly separated in the file give short runs.",
         tests_pass_fail_fool="Pass: 16 sixteenths in a row -> run 16. Fail: alternating values -> 1. Fool: 8 sixteenths, an eighth rest, 8 sixteenths -> two runs of 8, not 16.",
         in_our_files="all files",
         used_for="1.13, 2.11, 3.10 (Hanon-type even streams), difficulty (endurance), step 4 generator check",
         why_easy="Run-length count."),
    dict(id="E41", group="texture", fact="Written voices per staff",
         chatgpt_ids="texture.voice-count (written voices only)",
         reports="Per staff: number of distinct <voice> numbers per bar; bars with 2 or more voices.",
         definition="The file's own <voice> numbers on each staff. Not musical independence and not an estimate.",
         implementation="Raw walk; music21 Measure.voices as the second reader. partitura estimate_voices is NOT used (an estimate across staves; it raised RecursionError on a corpus file).",
         library_and_prior_evidence="Old branch: voice collisions found in a few files; no count.",
         pitfalls="Exporters create voices for single notes (a voice with one note in one bar).",
         tests_pass_fail_fool="Pass: a bar with voices 1 and 2 on staff 1 -> 2. Fail: one voice -> 1. Fool: voice 2 holding only rests -> reported, with notes-in-voice count 0.",
         in_our_files="voice element in all 842",
         used_for="Excerpts for readers (voices listed separately, as ref_check.py already does), 7.4 (a pointer to contrapuntal pieces, not a judgment), difficulty (polyphony)",
         why_easy="Direct read."),
    # ---------------------------------------------------------------- two staves
    dict(id="E42", group="two staves", fact="Attack rate per staff and the ratio between staves",
         chatgpt_ids="coordination.unequal-rates; rhythm.beat-onset-share",
         reports="Per bar and overall: attacks per beat on each staff; the ratio; share of beats with an attack on either staff.",
         definition="Attacks = distinct onsets of non-grace notes per staff; beat from the time signature in force.",
         implementation="From the note list.",
         library_and_prior_evidence="Old branch: beat-onset share validated on one item (Hanon 61 of 62).",
         pitfalls="Staff is not hand (the old project found the staff rule disagreeing with a second reader on 3.3% of notes in a 33-item sample, and wrong on 41.5% of notes under printed hand words); rows say 'staff'.",
         tests_pass_fail_fool="Pass: eighths over half notes in 4/4 -> 2 and 0.5 per beat. Fail: n/a. Fool: a chord counts as one attack, not three.",
         in_our_files="all files",
         used_for="A.4 (hands together), 1.5 (busy left hand under a melody), difficulty (coordination)",
         why_easy="Counting onsets."),
    dict(id="E43", group="two staves", fact="Attacks shared between the staves",
         chatgpt_ids="coordination.synchrony-share; texture.hands-together",
         reports="Share of attack times where both staves attack together; share of bars where both staves sound at some point.",
         definition="Attack times on staff 1 and staff 2 compared exactly (same onset).",
         implementation="Set intersection over onset times per staff.",
         library_and_prior_evidence="Old branch: handsTogether detector exists (detect.ts line 611); no measured finding.",
         pitfalls="As E42 (staff, not hand).",
         tests_pass_fail_fool="Pass: melody over a held chord each bar -> low shared share, both staves sound in every bar. Fail: right hand alone -> 0. Fool: a staff-2 note tied over the barline -> sounds but does not attack.",
         in_our_files="all files",
         used_for="A.4 (hands together), difficulty (coordination), step 4 generator check",
         why_easy="Set intersection."),
    dict(id="E44", group="two staves", fact="Staves taking turns",
         chatgpt_ids="texture.alternating-hands",
         reports="Bars where both staves have notes but never sound at the same moment; longest run of such bars; hand-off count.",
         definition="Within a bar: the sounding intervals (onset to onset + duration, ties merged) of staff 1 and staff 2 never overlap, and both staves have notes.",
         implementation="Interval overlap test per bar.",
         library_and_prior_evidence="Old branch: no finding.",
         pitfalls="Pedal makes notes overlap in sound; this row uses written durations only.",
         tests_pass_fail_fool="Pass: right hand bars 1-2, left hand bars 3-4 on separate beats -> turn-taking. Fail: melody over chords -> no. Fool: left hand note held under the right hand's entry -> overlap, so not turn-taking.",
         in_our_files="all files",
         used_for="P.5 and A.4 (pieces where hands alternate before playing together)",
         why_easy="Interval overlap."),
    dict(id="E45", group="two staves", fact="One staff holding while the other moves",
         chatgpt_ids="coordination.sustain-vs-move",
         reports="Spans where a note or chord on one staff sounds for at least one beat (ties merged) while the other staff has 2 or more attacks; count, total beats, bars, which staff holds.",
         definition="Exact intervals from written durations; 'at least one beat' from the time signature in force.",
         implementation="Interval test over the note lists.",
         library_and_prior_evidence="Old branch: no finding.",
         pitfalls="As E42 (staff, not hand); pedal ignored.",
         tests_pass_fail_fool="Pass: a whole-note chord on staff 2 under four quarters on staff 1 -> one span of 4 beats. Fail: both staves in quarters together -> none. Fool: staff 2 repeating the same chord in quarters -> no hold (re-struck).",
         in_our_files="all files",
         used_for="A.4 and 1.5 (held accompaniment under a moving melody), 2.5 (a setting for voicing practice; voicing itself is not detected)",
         why_easy="Interval test."),
    dict(id="E46", group="reading", fact="Visual density per bar",
         chatgpt_ids="reading.visual-density",
         reports="Per staff-bar: notes, accidentals (E07), ledger-line notes (E05); the median and the densest bars.",
         definition="Counts from E05, E07 and E11 per bar and staff.",
         implementation="Combines earlier rows.",
         library_and_prior_evidence="Old branch: uncertain (La Campanella at most 34 notes on one staff-bar) because it used the failing display model for accidentals; E07 avoids that.",
         pitfalls="Density is not difficulty by itself (repetition makes dense bars easy to read).",
         tests_pass_fail_fool="Pass: a bar with 8 notes and 2 accidentals -> 8 and 2. Fail: an empty bar -> 0. Fool: a whole-bar rest in one staff -> 0 notes on that staff.",
         in_our_files="all files",
         used_for="Choosing excerpts for the reading rungs (B.12, 1.11, 2.10, 3.9, 4.7, 5.7, 6.7, 7.8, 8.8), difficulty",
         why_easy="Sums of earlier rows."),
    # ---------------------------------------------------------------- difficulty
    dict(id="D01", group="difficulty", fact="Notes per second at the marked tempo",
         chatgpt_ids="technique.velocity",
         reports="Per staff and both together: attacks per second and notes per second (chord notes each counted), over the whole piece and its densest 4 bars, at the tempo map from E25; repeats not expanded.",
         definition="Quarter-note positions converted to seconds with the tempo map; no tempo -> UNKNOWN (no default tempo is assumed). For 8notes songs the tempo 8notes lists can be used, marked as from 8notes (the owner allowed 8notes tempos earlier).",
         implementation="music21 secondsMap or own conversion from E25; partitura not used for tempo.",
         library_and_prior_evidence="Old branch: validated (Hanon 20 3.89 notes a second at quarter = 60; Op. 10 No. 1 right hand 11.32 at 176). Playing speed is the first of Sébastien et al.'s seven criteria.",
         pitfalls="The marked tempo may be an editor's or a MIDI export's default (a <sound tempo> of exactly 120 with no metronome mark is reported as 'possible default').",
         tests_pass_fail_fool="Pass: sixteenths at quarter = 60 -> 4 per second. Fail: no tempo -> UNKNOWN. Fool: dotted quarter = 60 in 6/8 eighths -> 3 per second, not 2.",
         in_our_files="tempo known in up to 602 of 842 (71.5%) through <sound tempo>",
         used_for="Difficulty",
         why_easy="Arithmetic over E25 and the note list."),
    dict(id="D02", group="difficulty", fact="Difficulty statistics measured against published levels",
         chatgpt_ids="difficulty.level; difficulty.reading; difficulty.rhythm; difficulty.pitch-navigation; difficulty.technique; meta.published-grade",
         reports="For each statistic (D01, E35 entropy, E33 range, E37 largest span, E39 jumps per bar, E36 share of chords and largest chord, E07 accidentals per 100 notes, E11 shortest value and share of sixteenths or shorter, E13 tuplet share, E14 grace notes per 100 notes, E41 voices, E32 length, E06 signature size, E09 compound or changing metre): its rank correlation with the published level; then the share of held-out files a simple combination places within one level; then a list of files whose statistics disagree with their listed level by 3 or more (mismatch alarm).",
         definition="Published levels from chosen.csv (135 files, checked identity) reported separately from the exam-list matches in candidates-passing.csv (395 distinct files, identity matched by title, arrangement not checked). Levels on our spine (B, 1-8). The combination is fitted on part of the files and tested on the rest (leave-one-out), and the pass mark is fixed before the run.",
         implementation="numpy and scipy (Spearman); a small ordinal model or nearest-neighbour median; no new dependency.",
         library_and_prior_evidence="Published: Ramoneda et al. 2022 (Mikrokosmos, 3 classes) report a notes-only baseline of 64±8% test accuracy and 78±6% with fingering features (read from the PDF). The old project fitted a level on its own levels (645 items) with no outside calibration; that is why published levels are the target here.",
         pitfalls="Exam-list matches include wrong arrangements (the 109-file review found several), so their labels are noisy; levels B-2 are mostly simple arrangements and Grades 6-8 mostly originals, so the statistics may separate styles as much as levels.",
         tests_pass_fail_fool="Pass mark (proposal): within one level on 70% of held-out chosen.csv files. Fail: below that, the combination is not used to assign levels, only as a mismatch alarm. Fool check: shuffle the levels and rerun; the score must fall to chance.",
         in_our_files="530 files with a published level (135 + 395, overlap not yet removed)",
         used_for="Step 3: a check on published placements (mismatch alarm); a judged level, labelled 'judged, not published', only if the pass mark is met and the owner wants it",
         why_easy="Statistics over rows above; the risk is in reading the result, not in the code."),
    dict(id="D03", group="difficulty", fact="Published difficulty model (CIPI) run on our files",
         chatgpt_ids="difficulty.level (external model)",
         reports="Henle-scale level 1-9 per file from the published model; its agreement with our published levels on the same files as D02.",
         definition="compute_difficulty(path) from Ramoneda et al. 2024 (Expert Systems with Applications), trained on 652 Henle-graded classical scores; reported ensemble result 39.5% exact over 9 levels and 87.3% within one level on its own test data (read through a summariser, not from the PDF).",
         implementation="Separate Python environment: the repository pins torch 2.0.1 with Linux-only CUDA and triton wheels and music21 8.3, so on this Windows machine it needs CPU torch and relaxed pins. Not easy; listed because it is the reuse-first option the owner asked us to look for.",
         library_and_prior_evidence="Code: github.com/PRamoneda/difficulty-prediction-CIPI, AGPL-3.0 (fine for personal use). Models ship in the package.",
         pitfalls="Trained on classical originals, so easy song arrangements are outside its data; Henle levels are not exam grades, so the mapping is measured on our files, not assumed.",
         tests_pass_fail_fool="Pass: runs on 20 chosen.csv files of known level and its order agrees with ours better than D02's. Fail: install fails or agreement is worse; dropped. Fool: a Grade 8 piece and a Level B piece must not come out the same level.",
         in_our_files="all supported files",
         used_for="Same as D02",
         why_easy="NOT easy: listed for the owner's decision (medium; a one-off environment, then one function call per file)."),
]


# Changes after ChatGPT's independent review (2026-10-10, README_ChatGPT_independent_review.md), with the measured
# checks on our 842 candidate files that settled its four technical points. Each entry overrides fields of a row and
# says what changed in review_change.
UPDATES = {
    "E01": dict(
        reports="For every file: parts, part names, staves per part, and the staves list used by all per-staff rows (each staff of each pitched part). Two-staff relations (E42-E45) run only when there are exactly two piano staves: one part with two staves, or two one-staff parts neither of which names another instrument.",
        definition="Every staff of every pitched part is a staff for the per-staff rows, whatever the layout. Two piano staves = one part with two staves, or two one-staff parts whose names pass quality_check.not_piano; staff 1 is the upper (first) one. Otherwise the two-staff rows return UNKNOWN.",
        tests_pass_fail_fool="Pass: grand staff -> 2 staves, relations run. Pass: two one-staff parts named Right Hand / Left Hand -> 2 staves, relations run. Fail: three staves (voice plus a two-staff piano) -> per-staff rows run on all three; relations UNKNOWN. Fool: two one-staff parts 'Violin' and 'Piano' -> relations UNKNOWN.",
        in_our_files="measured on 842: one part with two staves 675; two one-staff parts 127 (some may pair another instrument); two parts with two staves 35; other 5",
        review_change="ChatGPT: do not drop other layouts. Measured: refusing all but one two-staff part would lose 167 of 842 files; now per-staff rows run on any layout and only the two-staff relations need two piano staves."),
    "E02": dict(
        reports="For each measure: a unique index (0, 1, 2 ...) and the printed number (with any suffix), implicit flag, notated length against the time signature (full, short, over-full); explicit rests and unfilled voice gaps reported apart.",
        review_change="ChatGPT: keep a unique measure index beside the printed number; separate rests from unfilled gaps."),
    "E04": dict(
        definition="<octave-shift type='down|up|stop' size='8|15' number='n'>, matched by number within a staff. MusicXML stores the sounding pitch and the shift says how the print differs: a usual 8va is type='down' (printed an octave below the sound). Measured on our files: notes under type='down' spans sit in octaves 5-7 (13,196 in octave 6), under type='up' in octaves 0-3, so <pitch> is the sounding pitch.",
        implementation="Raw walk; displayed pitch = sounding pitch moved by the shift (down 8 -> one octave lower on the page, up 8 -> one higher, 15 -> two). music21 spanner.Ottava as the second reader (in our probe its spans matched the raw starts on 4 of 4 files).",
        review_change="ChatGPT: state the direction (8va = type down) and keep sounding and displayed pitch apart. Measured on our files and confirmed."),
    "E05": dict(
        definition="Displayed staff position from the clef in force and the displayed pitch (E04: sounding pitch moved by any ottava). Ledger lines = lines passed beyond the staff: middle C in treble 1 below; B3 in treble 1 (the space under the first ledger line); A5 in treble 1 above; C6 in treble 2; middle C in bass 1 above; E2 in bass 1 below. Counts above 5 are kept as data and also flagged 'possible missing 8va'.",
        review_change="ChatGPT: keep high counts as data with a separate flag rather than hiding them; base on displayed pitch."),
    "E08": dict(
        library_and_prior_evidence="ChatGPT asked whether files omit <alter> on notes covered by the signature. Measured on our 842 files: of 246,796 notes on a signature-altered step, 235,106 carry the matching <alter>, 11,501 more are explained by a natural earlier in the bar or a tie, and 189 (0.08%, 61 files) are unexplained. So the encoded <alter> is used, with accidental carry within the bar.",
        definition="A note counts when its step is one the signature alters and its effective alter equals the signature's (from <alter>, which MusicXML requires for the sounding pitch). Notes naturalised by an accidental, or carrying it forward in the bar, do not count.",
        review_change="ChatGPT's concern that <alter> may be omitted: measured, 189 of 246,796 notes unexplained; definition kept, with accidental carry stated."),
    "E09": dict(
        reports="Each signature exactly as written (beats including additive strings like 3+2, beat-type, symbol) with its bar; changes; a class (simple, compound, irregular) when the signature fixes it, UNKNOWN when it does not (6/4 and 3/2 can be grouped more than one way; 5, 7, 11 numerators without a written sum).",
        review_change="ChatGPT: class is a convention; keep the written signature first and UNKNOWN where the grouping is open (6/4 now UNKNOWN unless beaming is read later)."),
    "E10": dict(
        reports="Pickup CANDIDATE when the first bar is shorter than the signature; the implicit flag; the last bar's length; a pickup is called confirmed only when the short first bar and the implicit flag or a matching short last bar agree.",
        review_change="ChatGPT: a short first bar is a candidate, not proof; report the observations and their agreement."),
    "E11": dict(
        definition="Written <type> and <dot> of each non-grace, non-cue note and rest, and the encoded <duration> beside it. A tie chain is linked by <tie> (sound) or <tied> (notation) between notes of the same pitch on the same staff; two tied notes are one chain, two written notes.",
        review_change="ChatGPT: read both <tie> and <tied>; keep written type and encoded duration as separate facts."),
    "E12": dict(
        definition="Two consecutive NOTES (not rests) in the same voice and staff, the second starting where the first ends: (dotted quarter, eighth) or (dotted eighth, sixteenth), in a bar whose signature is simple (E09). Compound and UNKNOWN-class bars are excluded.",
        tests_pass_fail_fool="Pass: 4/4 'dotted quarter, eighth, half' -> 1. Fail: even quarters -> 0. Fool: dotted quarter then an eighth REST -> 0; 6/8 dotted quarters -> 0.",
        review_change="ChatGPT: notes only, never rests."),
    "E13": dict(
        reports="Per staff: notes and runs by tuplet ratio (3:2, 6:4, 5:4, 2:3 ...), whether a bracket or number is printed (separately), and notes with an implausible ratio listed as suspect.",
        definition="A tuplet note has <time-modification> with actual-notes and normal-notes both between 2 and 12, unequal, and a ratio strictly between 0.5 and 2. Other ratios (e.g. 28:6, 80:12, 6:6, 2:1) are re-export artefacts: reported as suspect, not as tuplets. Printed <tuplet> elements are reported as a separate display fact.",
        library_and_prior_evidence="ChatGPT: a bracket-only rule misses unbracketed tuplets. Measured on our files: 6,011 of 107,140 time-modified notes lie outside any <tuplet> span, 4,906 of them at 3:2 in 92 files, so bracket-only was wrong for us (the old branch's 230-of-231 figure was on its own catalogue). Suspect ratios outside spans include 28:6, 80:12, 21:32.",
        tests_pass_fail_fool="Pass: three eighths at 3:2 with no <tuplet> element -> 3 triplet notes, bracket not printed. Fail: plain eighths -> 0. Fool: a 28:6 ratio -> 0 tuplet notes, 1 suspect.",
        review_change="ChatGPT: required change (unbracketed tuplets). Measured: 4,906 unbracketed 3:2 notes in 92 files; definition now from time-modification with a plausibility rule."),
    "E20": dict(
        definition="Children of <direction-type><dynamics> and of <notations><dynamics>. The staff is the direction's <staff>; when absent in a two-staff part it is 'unspecified' (not staff 1). Ordinary levels (pppp..ffff, mp, mf) are ordered; accent dynamics (sf, sfz, fz, fp, rf ...) are listed apart, not placed on the scale.",
        review_change="ChatGPT: staff unspecified rather than staff 1; accent dynamics kept off the loudness scale."),
    "E23": dict(
        definition="<slur type='start|stop' number> paired by number within the part (a slur may change voice or staff); notes under a slur = notes of the start note's staff between its start and stop.",
        review_change="ChatGPT: pair by number within the part, not by staff and voice."),
    "E24": dict(
        definition="<direction-type><pedal type='start|stop|change|continue|sostenuto|resume|discontinue'>; staff 'unspecified' when the direction has none. Sustain, sostenuto and soft pedal (una corda, from words) are separate kinds, never one 'pedal' flag.",
        review_change="ChatGPT: no invented staff; sustain, sostenuto and una corda kept apart."),
    "E25": dict(
        reports="Three separate observations: metronome marks (beat unit, dots, per minute, or the text when it is a range or an equation), <sound tempo> values, and the opening tempo word (Grave to Prestissimo, closed list). A tempo map in quarters per minute is built from metronome marks, else <sound tempo>; when they disagree both are kept and flagged.",
        review_change="ChatGPT: keep metronome, sound tempo and text apart; ranges and metric equations are not parsed into one number."),
    "E26": dict(
        definition="<words> matched as whole words, case-insensitive, to this closed list: rit, rit., ritard, ritardando, rall, rall., rallentando, accel, accel., accelerando, a tempo, tempo I, tempo primo, rubato, allargando, stringendo, meno mosso, piu mosso / più mosso, swing, swung, straight (eighths), plus the <swing> element. Anything else is listed as other words. 'ritmico' and 'accelerated' do not match.",
        review_change="ChatGPT: the definition now lists every promised word; whole-word matching."),
    "E32": dict(
        used_for="Difficulty (length; one of Sébastien et al.'s criteria), step 4 generator check",
        review_change="ChatGPT: removed 'at most 48 bars at Level B', which came from my own level_fit.py filter, not a published source; multi-bar rests reported apart."),
    "E33": dict(
        definition="Sounding MIDI pitch of every non-cue note on the staff, read straight from <pitch> (already sounding; no ottava shift is added).",
        tests_pass_fail_fool="Pass: C4-G4 -> 7 semitones. Fail: n/a. Fool: a note printed C6 under an 8va (encoded C7, type down) -> counted at C7, not shifted again to C8.",
        review_change="ChatGPT: avoid shifting twice; <pitch> is already the sounding pitch (measured on our files, see E04)."),
    "E36": dict(
        reports="Per staff: histogram of notes starting together across voices, and the same within one written voice, side by side; unison doublings (same pitch twice) counted once with a flag; stacks of 7 or more flagged as possible encoding fault. These are notated clusters, not claims about one hand.",
        review_change="ChatGPT: keep per-staff and per-voice figures side by side; no single-hand claim."),
    "E38": dict(
        reports="Per staff: pure octave dyads (two notes 12 semitones apart), attacks that contain an octave between their outer notes with notes inside (e.g. C-E-C), and the longest run of consecutive pure octave dyads; bars.",
        definition="From E36 attacks: pure dyad = exactly two notes, highest - lowest = 12; octave-containing = highest - lowest = 12 with 3 or more notes.",
        tests_pass_fail_fool="Pass: C3+C4 -> pure dyad. Fail: C3+G3 -> neither. Fool: C3+E3+C4 -> octave-containing, not a pure dyad.",
        review_change="ChatGPT: a C-E-C chord is not an octave; split the two kinds."),
    "E39": dict(
        fact="Staff outer-edge movement and per-voice intervals",
        definition="Two separate figures: (a) staff outer-edge movement: top note of each attack on staff 1, bottom note on staff 2, interval to the next attack, a displacement statistic and never called melody; (b) melodic intervals within each written voice. Jumps: over 12 semitones within 2 quarter notes (after Sébastien et al. 2012), from (a).",
        review_change="ChatGPT: do not call the outer edge melodic; keep per-voice intervals separate; the time window is in quarter notes."),
    "E40": dict(
        fact="Repeated pitches; runs of equal values (two separate counts)",
        reports="Per staff and voice, two outputs: (1) longest run of the same single pitch struck again and again; (2) longest run of consecutive attacks with the same written value. Count, value or pitch, bars for each.",
        definition="Runs inside one written voice; a rest breaks both; a tie continuation is not an attack (it neither extends nor breaks a run of attacks).",
        tests_pass_fail_fool="Pass: 16 different-pitch sixteenths -> equal-value run 16, repeated-pitch run 1. Pass: 8 repeated Cs in mixed values -> repeated-pitch run 8. Fool: 8 sixteenths, an eighth rest, 8 sixteenths -> two runs of 8.",
        review_change="ChatGPT: split into two counters."),
    "E42": dict(
        reports="Per bar and overall: attacks per quarter note on each staff, and attacks per beat where the beat is fixed by the signature (dotted quarter in compound time; UNKNOWN for UNKNOWN-class signatures); the ratio between staves (undefined when one staff has none); share of beats with an attack on either staff.",
        review_change="ChatGPT: declare the denominator (per quarter and per felt beat separately); ratio undefined at zero."),
    "E43": dict(
        reports="Shared-attack share = attack times common to both staves / all distinct attack times on either (union); bars where both staves SOUND at the same moment (overlapping written durations) and, separately, bars where both have notes at some point.",
        review_change="ChatGPT: declare the denominator (union) and separate sounding overlap from shared attacks (needed for texture.hands-together)."),
    "E44": dict(
        reports="(1) Bars where both staves have notes but never sound at the same moment; (2) separately, hand-offs between bars: a bar with notes on one staff only followed by a bar with notes on the other only.",
        tests_pass_fail_fool="Pass (1): in one 4/4 bar, staff 1 plays beats 1 and 3, staff 2 beats 2 and 4, quarters -> turn-taking bar. Pass (2): staff 1 alone in bar 1, staff 2 alone in bar 2 -> 1 hand-off, 0 turn-taking bars. Fool: staff 2's note held under staff 1's entry -> overlap, not turn-taking.",
        review_change="ChatGPT: my pass example contradicted the definition; within-bar turn-taking and between-bar hand-offs are now two outputs."),
    "E45": dict(
        definition="A note or chord on one staff sounding at least 1 quarter note (ties merged) while the other staff has 2 or more attacks strictly inside that time; a re-struck note ends the hold.",
        review_change="ChatGPT: state the time unit (quarter notes)."),
    "D01": dict(
        reports="Per staff and both together: attacks per second and notes per second (chord notes each counted), whole piece and densest 4 bars, with the tempo's source named (metronome, sound tempo, 8notes) or UNKNOWN; a lone <sound tempo> of 120 with no metronome mark is UNKNOWN (possible export default).",
        review_change="ChatGPT: tempo source named; possible export default treated as UNKNOWN."),
    "D02": dict(
        group="difficulty experiment",
        reports="For each statistic: its rank correlation with the published level; a simple combination's held-out error against baselines (always the middle level; always the most common level), per level; and a mismatch list (files whose statistics sit 3 or more levels from their listed level) for checking by reading. Used as an alarm, never to assign a level.",
        definition="Labels only from chosen.csv (checked identity); exam-list matches with unchecked arrangement are not used as truth. Held-out testing keeps all files of one work together. No fixed pass mark; the result is judged against the baselines and by how many mismatch alarms turn out to be real problems when read.",
        tests_pass_fail_fool="Control: shuffled levels must do no better than the baselines.",
        why_easy="NOT easy: an experiment over the easy rows, run after them.",
        review_change="ChatGPT: no arbitrary 70% gate; baselines, grouped held-out testing, checked labels only, alarm use only."),
    "D03": dict(
        group="difficulty experiment",
        definition="compute_difficulty(path) from Ramoneda et al. 2024 (Expert Systems with Applications), trained on 652 Henle-graded classical scores; the paper reports 39.5% balanced accuracy over 9 Henle levels. (The 87.3% within-one figure came through a summariser and is unconfirmed.)",
        why_easy="NOT easy: optional, after D02, in its own CPU environment.",
        review_change="ChatGPT: deferred as an optional benchmark after D02; the unconfirmed 87.3% figure marked as such."),
}


def main():
    out = os.path.join(HERE, "characteristics-easy.csv")
    with open(out, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=COLS)
        w.writeheader()
        assert set(UPDATES) <= {r["id"] for r in ROWS}
        for r in ROWS:
            r = {**r, "review_change": ""}
            for k, v in UPDATES.get(r["id"], {}).items():
                assert k in COLS, (r["id"], k)
                r[k] = v
            assert set(r) == set(COLS), (r["id"], set(COLS) ^ set(r))
            w.writerow(r)
    print(out, len(ROWS), "rows")


if __name__ == "__main__":
    main()
