/**
 * The shapes of `catalog.json` and `curriculum.json` as the app reads them.
 *
 * These mirror `content/catalog.schema.json` and `content/curriculum.schema.json`, which
 * are the authority — the schemas validate the build, these types describe what arrives at
 * runtime. Fields the app does not use yet are omitted rather than typed loosely, so a
 * mistake is a compile error and not an `undefined` two screens later.
 */

export type ItemType = 'song' | 'exercise' | 'drill';
export type Hands = 'both' | 'right' | 'left';
/** Where an item's `level` came from — replan §1.4. */
export type LevelSource = 'judged' | 'estimated';

export interface ItemSource {
  name: string;
  url?: string | null;
  license: string;
  pd_region?: string | null;
  editionNotes?: string | null;
}

export interface ItemMedia {
  kind: string;
  label: string;
  url: string;
}

export interface CatalogItem {
  id: string;
  type: ItemType;
  title: string;
  level: number;
  /**
   * Whether `level` was judged for this piece or estimated (replan §1.4).
   *
   * `estimated` means an opus was banded to one number on import, or a model
   * computed it from the score's features. The app prints those as `≈ 7.1`
   * and offers "Re-level" so the owner can replace the guess; doing so makes
   * the item `judged`. Optional in the type, required in the schema: an older
   * catalog in a browser cache must not crash the app.
   */
  levelSource?: LevelSource;
  hands: Hands;
  tracks: string[];
  concepts: string[];
  /** null for an import placeholder and for a drill generated at runtime. */
  file?: string | null;
  importHint?: string | null;
  /** Other items that train the same thing — docs/00 D21, docs/04 §2 "Swap this". */
  alternatives?: string[];
  variantOf?: string | null;
  tags?: string[];
  composer?: string | null;
  arranger?: string | null;
  genre?: string[];
  durationSec?: number | null;
  tempoBpm?: number | null;
  keySig?: string | null;
  timeSig?: string | null;
  abrsmGradeApprox?: number | null;
  source?: ItemSource | null;
  media?: ItemMedia[];
  teaching?: {
    lessonIds?: string[];
    notes?: string | null;
    /**
     * Named practice sections for the loop (docs/04 §5, P18).
     *
     * Bars are 1-based positions in the *printed* score, which is what a
     * player counts — not the model's unrolled index, where a piece with a
     * repeat has twice as many.
     */
    sections?: { label: string; fromMeasure: number; toMeasure: number }[];
  } | null;
  drill?: { kind: string; params?: Record<string, unknown> } | null;
  /**
   * Set on the items synthesised from the `imports` store (docs/04 §4). The
   * Library and the Score screen both need to know that this one's bytes come
   * from IndexedDB rather than from a URL under `content/`.
   */
  imported?: boolean;
  /** `pdf` items open in the PDF viewer (docs/04 §5b), never the Score screen. */
  kind?: 'musicxml' | 'pdf';
  /**
   * Rungs an *imported* item was assigned to (replan §4.3).
   *
   * Distinct from `teaching.lessonIds`, which is what a bundled item's author
   * said it teaches. This one is what the owner said when he saved it, and it
   * is why `curriculum/load.ts` can append the piece to those rungs' song
   * options at runtime.
   */
  lessonIds?: string[];
}

/** Generated by tools/content/finder.py into the built curriculum (replan §4.1). */
export interface Finder {
  skill: string;
  levelWords: string;
  constraints: string[];
  avoid: string[];
  examples?: { title: string; composer?: string; note: 'bundled' | 'wanted' }[];
  formats: string;
  searchQuery: string;
  chatPrompt: string;
}

/**
 * What a rung is still short of (replan §4.2), written by validate.py.
 *
 * The app reads it rather than recounting: the counting rules — the floor, the
 * song-optional rung that counts both lists together — live in the validator,
 * and having them in two places is how the two would come to disagree.
 */
export interface Needs {
  songs: number;
  exercises: number;
  /** Always 0 until the shelf of paper books exists (replan §5). */
  paper: number;
  /** How many of this rung's options have a level inside its band. */
  inBand: number;
  floor: number;
}

/** A concept id, its display name, and how to find music that trains it. */
export interface ConceptEntry {
  id: string;
  display: string;
  /** True for a feature of this app rather than a musical skill: no finder. */
  appFeature?: boolean;
  finder?: Finder;
}

export interface Mastery {
  exercisesRequired: number;
  songsRequired: number;
  minAccuracy: number;
  minTempoPct: number;
  custom?: string;
}

export interface Lesson {
  id: string;
  title: string;
  concepts: string[];
  textFile: string;
  exerciseOptions: string[];
  songOptions: string[];
  mastery: Mastery;
  /**
   * True when no song tests this unit's skill — reading by interval, the first scale,
   * accompaniment patterns, the theory and improvisation tracks (docs/02 Part G). The
   * lesson then completes on two exercises instead of an exercise and a song.
   */
  songOptional?: boolean;
  /** Orientation lessons that are a single thing by nature: the placement test, the tour. */
  optionsExempt?: boolean;
  prerequisites?: string[];
  estimatedDays?: number;
  /** How to go and find more for this rung. Absent only on an exempt rung. */
  finder?: Finder;
  /**
   * What to play from a book instead, if he has one (replan §5.2).
   *
   * Prose, not data: "or bars 1-16 of whatever your method book gives for
   * hands together with a held left hand". It is a sentence rather than a
   * search because a method book is not searchable — he is looking at a shelf.
   */
  paperHint?: string;
  /**
   * Registered book pieces assigned to this rung, appended at runtime by the
   * shelf overlay. Never in the built curriculum: the shelf lives on the
   * phone, and nothing about which books he owns belongs in the repository.
   */
  paperOptions?: string[];
  /** What it is short of, written by validate.py. */
  needs?: Needs;
  /** `[min, max]` level across this rung's options (replan §1.7). */
  levelBand?: [number, number];
}

export interface Unit {
  id: string;
  title: string;
  track: string;
  lessons: Lesson[];
}

export interface Stage {
  number: number;
  title: string;
  summary: string;
  units: Unit[];
  approxDuration?: string;
  abrsmGradeApprox?: number | string | null;
}

export interface Track {
  id: string;
  title: string;
  description: string;
  startsAtStage: number;
  /** Switched on for a new learner; the Plan screen's track chips change it. */
  defaultActive?: boolean;
}

export interface Curriculum {
  version: number;
  tracks: Track[];
  stages: Stage[];
  /** Display names and finders for every concept id used anywhere (replan §4.1). */
  concepts?: ConceptEntry[];
}

/** What the learner has passed, keyed by item id. P7 stores this in IndexedDB. */
export interface PassRecord {
  itemId: string;
  passed: boolean;
  mastered?: boolean;
  /**
   * True when the pass is the learner's own word rather than a measurement —
   * "I already know this", or a run against paper the app could not see.
   */
  selfPassed?: boolean;
}
