// @vitest-environment jsdom
/**
 * The two levelling implementations must stay one formula (replan §4.4).
 *
 * `tools/content/difficulty.py` levels what the pipeline touches; this port
 * levels what the owner imports on his phone. Two implementations of one model
 * drift, and drift here means a piece he imports lands on a different rung
 * from the same piece the quarry found. So both are run over the same fixture
 * scores and held to 0.2 of a stage.
 *
 * The fixture is regenerated by `tools/content/export_levelling_fixture.py`.
 */
import { beforeAll, describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { OpenSheetMusicDisplay } from 'opensheetmusicdisplay';
import { edgeFixtures, generatedFixtures, loadFixture, type Fixture } from './helpers/fixtures';
import { extractScoreModel, keySignatureName } from '../../src/score/extractScoreModel';
import type { ScoreModel } from '../../src/score/types';
import {
  estimate,
  features,
  keyAccidentals,
  printedNotes,
  type LevelModel,
} from '../../src/score/difficulty';

interface FixtureScore {
  name: string;
  dir: string;
  features: Record<string, number>;
  level: number;
  source: string;
}

const EXPECTED = JSON.parse(
  readFileSync(join(process.cwd(), 'tests', 'fixtures', 'levelling.json'), 'utf8'),
) as { scores: FixtureScore[] };

const MODEL = JSON.parse(
  readFileSync(
    join(process.cwd(), '..', 'content', 'sources', 'level-model.json'),
    'utf8',
  ),
) as LevelModel;

/** How far the two may disagree, in stages. The spec's number, not a fitted one. */
const TOLERANCE = 0.2;

const models = new Map<string, ScoreModel>();

async function modelFor(fixture: Fixture): Promise<ScoreModel> {
  const cached = models.get(fixture.name);
  if (cached) return cached;
  const osmd = await loadFixture(fixture.path);
  const model = extractScoreModel(osmd, { id: fixture.name });
  models.set(fixture.name, model);
  return model;
}

describe('the level model', () => {
  it('reads its coefficients from the committed file, not from source', () => {
    expect(MODEL.fitted).toBe(true);
    expect(Object.keys(MODEL.weights ?? {}).length).toBeGreaterThan(0);
  });

  it('falls back to the table when there is no fit', () => {
    const unfitted: LevelModel = {
      fitted: false,
      fallback: { bins: [{ maxNotesPerBar: 4, minShortestValue: 0.5, level: 2 }] },
    };
    const result = estimate({ notesPerBar: 3, shortestValue: 1 }, unfitted);
    expect(result.source).toBe('fallback');
    expect(result.level).toBe(2);
  });

  it('clamps to the stage range', () => {
    const wild: LevelModel = { fitted: true, bias: 500, weights: { bars: 1 }, means: {} };
    expect(estimate({ bars: 1 }, wild).level).toBe(9);
    const tiny: LevelModel = { fitted: true, bias: -500, weights: { bars: 1 }, means: {} };
    expect(estimate({ bars: 1 }, tiny).level).toBe(1);
  });

  it('names the three features that moved it most', () => {
    const result = estimate(
      { bars: 40, notesPerBar: 12, ledgerRatio: 0.4, shortestValue: 0.25 },
      MODEL,
    );
    expect(result.drivers).toHaveLength(3);
    expect(result.source).toBe('model');
  });
});

describe('key signatures', () => {
  it('counts sharps and flats from the stored name', () => {
    expect(keyAccidentals('C major')).toBe(0);
    expect(keyAccidentals('D major')).toBe(2);
    expect(keyAccidentals('E-flat major')).toBe(3);
    expect(keyAccidentals('A minor')).toBe(0);
    expect(keyAccidentals('C minor')).toBe(3);
    expect(keyAccidentals(undefined)).toBe(0);
  });

  it('reads every name the model can actually store', () => {
    // The test above is the one that let the bug through, and it is kept
    // because it is still true. What it could not catch is that it writes its
    // own input: "E-flat major" is a string no part of this app produces.
    // `model.keySig` is filled by `keySignatureName`, which writes "Eb major",
    // and the lookup tables were written the long way — so sixteen of the
    // thirty signatures, every flat key and every sharp key, resolved to
    // nothing and were scored as having no accidentals at all. A piece in
    // D flat reached the level model looking like C major.
    //
    // So this one does not name a single key. It goes through the producer for
    // all fifteen signatures in both modes and asks for the number back, which
    // is the only version of this test that can find the two modules
    // disagreeing about what a key signature is called.
    const wrong: string[] = [];
    for (let fifths = -7; fifths <= 7; fifths += 1) {
      for (const mode of [0, 1]) {
        const name = keySignatureName(fifths, mode);
        expect(name, `no name for fifths ${String(fifths)}`).toBeDefined();
        const counted = keyAccidentals(name);
        if (counted !== Math.abs(fifths)) {
          wrong.push(`"${String(name)}" counted ${String(counted)}, has ${String(Math.abs(fifths))}`);
        }
      }
    }
    expect(wrong, `key names the difficulty model cannot read:\n${wrong.join('\n')}`).toEqual([]);
  });
});

describe('printed notes', () => {
  it('counts a repeated bar once, however many passes the player makes', async () => {
    const repeats = edgeFixtures().find((f) => /repeat/i.test(f.name));
    if (!repeats) return;
    const model = await modelFor(repeats);
    const printed = printedNotes(model);
    const played = model.steps.reduce((n, step) => n + step.notes.length, 0);
    expect(printed.length).toBeLessThanOrEqual(played);
    // The features must be measured off the printed score, because that is
    // what Python read.
    expect(features(model).bars).toBe(model.sourceMeasureCount);
  });
});

/**
 * A two-bar lead sheet: three printed chord symbols over five melody notes.
 *
 * Written into the test rather than added to `tests/fixtures/scores/edge/`
 * because OSMD cannot load a `<harmony>` under jsdom at all — laying a chord
 * symbol out goes through `VexFlowTextMeasurer`, which sets `.font` on the 2D
 * context jsdom does not implement — so a lead sheet in that directory would
 * take `scoreModel`, `engineScoring` and `scoreSmoke` down with it. The stub
 * below is the smallest thing that lets the parse finish, and it is put back
 * afterwards so no other test inherits it.
 */
const LEAD_SHEET = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <work><work-title>Lead sheet with chord symbols</work-title></work>
  <part-list><score-part id="P1"><part-name>Melody</part-name></score-part></part-list>
  <part id="P1">
    <measure number="1">
      <attributes><divisions>4</divisions><key><fifths>0</fifths></key>
        <time><beats>4</beats><beat-type>4</beat-type></time><staves>1</staves>
        <clef number="1"><sign>G</sign><line>2</line></clef></attributes>
      <harmony><root><root-step>C</root-step></root><kind>major</kind></harmony>
      <note><pitch><step>C</step><octave>4</octave></pitch><duration>4</duration><voice>1</voice><type>quarter</type><staff>1</staff></note>
      <note><pitch><step>D</step><octave>4</octave></pitch><duration>4</duration><voice>1</voice><type>quarter</type><staff>1</staff></note>
      <harmony><root><root-step>G</root-step></root><kind>dominant</kind></harmony>
      <note><pitch><step>E</step><octave>4</octave></pitch><duration>4</duration><voice>1</voice><type>quarter</type><staff>1</staff></note>
      <note><pitch><step>D</step><octave>4</octave></pitch><duration>4</duration><voice>1</voice><type>quarter</type><staff>1</staff></note>
    </measure>
    <measure number="2">
      <harmony><root><root-step>F</root-step></root><kind>major</kind></harmony>
      <note><pitch><step>C</step><octave>4</octave></pitch><duration>16</duration><voice>1</voice><type>whole</type><staff>1</staff></note>
    </measure>
  </part>
</score-partwise>`;

describe('a printed chord symbol is not a sounding note', () => {
  it('gives a lead sheet the melody it has, not the chords it names', async () => {
    const canvas = HTMLCanvasElement.prototype as unknown as { getContext: unknown };
    const original = canvas.getContext;
    canvas.getContext = () => ({
      font: '',
      measureText: () => ({ width: 10 }),
      fillText: () => undefined,
      save: () => undefined,
      restore: () => undefined,
    });
    let model: ScoreModel;
    try {
      const container = document.createElement('div');
      document.body.appendChild(container);
      const osmd = new OpenSheetMusicDisplay(container, { autoResize: false, backend: 'svg' });
      await osmd.load(LEAD_SHEET);
      model = extractScoreModel(osmd, { id: 'lead-sheet' });
    } finally {
      canvas.getContext = original;
    }

    // Five melody notes, three chord symbols. `sounding()` on the Python side
    // drops the symbols from every walk it makes; here they never arrive,
    // because OSMD parses `<harmony>` into a chord symbol container on the
    // source measure and `extractScoreModel` walks voice entries. This test is
    // the guard on that: it has never been red, and it will be the moment the
    // extractor starts letting a symbol through into `steps[].notes`.
    expect(printedNotes(model).map((n) => n.midi)).toEqual([60, 62, 64, 62, 60]);

    const values = features(model);
    // Nothing the symbols could have contributed: no simultaneity, no hand
    // span, no crossing, and a note density of the melody alone.
    expect(values.maxSimultaneousRight).toBe(0);
    expect(values.maxSimultaneousLeft).toBe(0);
    expect(values.maxSpanRight).toBe(0);
    expect(values.maxSpanLeft).toBe(0);
    expect(values.handCrossings).toBe(0);
    expect(values.notesPerBar).toBe(5 / 2);
    // A C major triad printed over the C would be a seven-semitone leap to the
    // G7 above the third beat; the melody's widest step is a tone.
    expect(values.maxLeapRight).toBe(2);
  });
});

describe('two voices on one staff are two lines', () => {
  // `voice_lines` in `tools/content/difficulty.py`, ported. Held against the
  // numbers Python wrote into the fixture rather than against numbers this test
  // invents, which is the only version of it that can catch the two drifting.
  //
  // Red before the port: measuring every note on the staff by onset read the
  // two voices of `two-voices` as chords — `maxSpanRight` 7 and `maxSpanLeft` 4
  // against Python's 0 and 0 — and ran `cross-staff`'s two upper-staff voices
  // into one melodic line, `maxLeapRight` 8 against Python's 1, which is the
  // fixture the agreement test failed on.
  for (const name of ['two-voices', 'cross-staff']) {
    it(`measures ${name} the way difficulty.py does`, async () => {
      const fixture = edgeFixtures().find((f) => f.name === name);
      if (!fixture) throw new Error(`no edge fixture named "${name}"`);
      const expected = EXPECTED.scores.find((s) => s.name === name);
      if (!expected) throw new Error(`no levelling fixture for "${name}"`);
      const values = features(await modelFor(fixture));
      for (const key of ['maxSpanRight', 'maxSpanLeft', 'maxLeapRight', 'maxLeapLeft', 'rangeRight', 'rangeLeft', 'voicesPerStaff']) {
        expect(values[key], `${name}.${key}`).toBe(expected.features[key]);
      }
    });
  }
});

describe('agreement with tools/content/difficulty.py', () => {
  const fixtures = [...edgeFixtures(), ...generatedFixtures()];
  const byName = new Map(EXPECTED.scores.map((s) => [s.name, s]));

  beforeAll(() => {
    expect(EXPECTED.scores.length).toBeGreaterThan(10);
  });

  it('has a Python estimate for the fixtures it is going to compare', () => {
    const compared = fixtures.filter((f) => byName.has(f.name));
    expect(compared.length).toBeGreaterThan(10);
  });

  for (const fixture of fixtures) {
    const expected = byName.get(fixture.name);
    if (!expected) continue;
    it(`agrees within ${String(TOLERANCE)} of a stage on ${fixture.name}`, async () => {
      const model = await modelFor(fixture);
      const ours = estimate(features(model), MODEL);
      expect(Math.abs(ours.level - expected.level)).toBeLessThanOrEqual(TOLERANCE);
    });
  }
});
