// @vitest-environment jsdom
/**
 * The two levelling implementations must stay one formula (replan §4.4).
 *
 * `tools/content/difficulty.py` levels what the pipeline touches; this port
 * levels what the owner imports on his phone. Two implementations of one model
 * drift, and drift here means a piece he imports lands on a different rung
 * from the same piece the quarry found. So both are run over the same fixture
 * scores and held to 0.2 of a stage.
 *
 * The fixture is regenerated by `tools/content/export_levelling_fixture.py`.
 */
import { beforeAll, describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { edgeFixtures, generatedFixtures, loadFixture, type Fixture } from './helpers/fixtures';
import { extractScoreModel } from '../../src/score/extractScoreModel';
import type { ScoreModel } from '../../src/score/types';
import {
  estimate,
  features,
  keyAccidentals,
  printedNotes,
  type LevelModel,
} from '../../src/score/difficulty';

interface FixtureScore {
  name: string;
  dir: string;
  features: Record<string, number>;
  level: number;
  source: string;
}

const EXPECTED = JSON.parse(
  readFileSync(join(process.cwd(), 'tests', 'fixtures', 'levelling.json'), 'utf8'),
) as { scores: FixtureScore[] };

const MODEL = JSON.parse(
  readFileSync(
    join(process.cwd(), '..', 'content', 'sources', 'level-model.json'),
    'utf8',
  ),
) as LevelModel;

/** How far the two may disagree, in stages. The spec's number, not a fitted one. */
const TOLERANCE = 0.2;

const models = new Map<string, ScoreModel>();

async function modelFor(fixture: Fixture): Promise<ScoreModel> {
  const cached = models.get(fixture.name);
  if (cached) return cached;
  const osmd = await loadFixture(fixture.path);
  const model = extractScoreModel(osmd, { id: fixture.name });
  models.set(fixture.name, model);
  return model;
}

describe('the level model', () => {
  it('reads its coefficients from the committed file, not from source', () => {
    expect(MODEL.fitted).toBe(true);
    expect(Object.keys(MODEL.weights ?? {}).length).toBeGreaterThan(0);
  });

  it('falls back to the table when there is no fit', () => {
    const unfitted: LevelModel = {
      fitted: false,
      fallback: { bins: [{ maxNotesPerBar: 4, minShortestValue: 0.5, level: 2 }] },
    };
    const result = estimate({ notesPerBar: 3, shortestValue: 1 }, unfitted);
    expect(result.source).toBe('fallback');
    expect(result.level).toBe(2);
  });

  it('clamps to the stage range', () => {
    const wild: LevelModel = { fitted: true, bias: 500, weights: { bars: 1 }, means: {} };
    expect(estimate({ bars: 1 }, wild).level).toBe(9);
    const tiny: LevelModel = { fitted: true, bias: -500, weights: { bars: 1 }, means: {} };
    expect(estimate({ bars: 1 }, tiny).level).toBe(1);
  });

  it('names the three features that moved it most', () => {
    const result = estimate(
      { bars: 40, notesPerBar: 12, ledgerRatio: 0.4, shortestValue: 0.25 },
      MODEL,
    );
    expect(result.drivers).toHaveLength(3);
    expect(result.source).toBe('model');
  });
});

describe('key signatures', () => {
  it('counts sharps and flats from the stored name', () => {
    expect(keyAccidentals('C major')).toBe(0);
    expect(keyAccidentals('D major')).toBe(2);
    expect(keyAccidentals('E-flat major')).toBe(3);
    expect(keyAccidentals('A minor')).toBe(0);
    expect(keyAccidentals('C minor')).toBe(3);
    expect(keyAccidentals(undefined)).toBe(0);
  });
});

describe('printed notes', () => {
  it('counts a repeated bar once, however many passes the player makes', async () => {
    const repeats = edgeFixtures().find((f) => /repeat/i.test(f.name));
    if (!repeats) return;
    const model = await modelFor(repeats);
    const printed = printedNotes(model);
    const played = model.steps.reduce((n, step) => n + step.notes.length, 0);
    expect(printed.length).toBeLessThanOrEqual(played);
    // The features must be measured off the printed score, because that is
    // what Python read.
    expect(features(model).bars).toBe(model.sourceMeasureCount);
  });
});

describe('agreement with tools/content/difficulty.py', () => {
  const fixtures = [...edgeFixtures(), ...generatedFixtures()];
  const byName = new Map(EXPECTED.scores.map((s) => [s.name, s]));

  beforeAll(() => {
    expect(EXPECTED.scores.length).toBeGreaterThan(10);
  });

  it('has a Python estimate for the fixtures it is going to compare', () => {
    const compared = fixtures.filter((f) => byName.has(f.name));
    expect(compared.length).toBeGreaterThan(10);
  });

  for (const fixture of fixtures) {
    const expected = byName.get(fixture.name);
    if (!expected) continue;
    it(`agrees within ${String(TOLERANCE)} of a stage on ${fixture.name}`, async () => {
      const model = await modelFor(fixture);
      const ours = estimate(features(model), MODEL);
      expect(Math.abs(ours.level - expected.level)).toBeLessThanOrEqual(TOLERANCE);
    });
  }
});
