"""
E50a: the generator of `tools/content/former_identities.json`, the historical dated identities (the reviewer's
rule, `docs/review/responses/questions-71bd6cee.md`, which replaced a rolling date window): every dated file
music21 wrote that a catalogue able to store a learner's material could have served. Never edited by hand.

    python scripts-former-identities.py --add <content dir> <label> [<content dir> <label> ...]
        reads each catalogue's rows (`catalog.json` and the score files beside it, in place, never written) and
        adds every file identity whose file is a dated music21 `.mxl` in the converter's layout, as
        `convert.dated_form` records it (its date, its sha256, the sha256 of its undated form, each proved by
        putting the date back); entries already in the table are kept, none is removed.
    python scripts-former-identities.py --check <content dir> [<content dir> ...]
        lists the dated music21 identities a catalogue holds that the table does not: the reviewer's stop
        condition. Exit 1 when there is any.
    python scripts-former-identities.py --reprove <content dir> <label>
        re-proves every entry already in the table under the converter's current bytes (the reviewer's
        required correction, questions-bd7d303e.md §5: one canonical creating system): for each entry, the
        catalogue's file at the entry's path gives the music's undated text; that text with the entry's date
        put back, zipped under creating system 0 or 3, must give the entry's own sha256, which fixes the
        entry's `system`, and `undated` becomes the sha256 of the undated form as the converter zips it now.
        An entry that does not re-prove stops the run and nothing is written; none is added or dropped.

The output is deterministic: entries sorted by file, date and sha256, one per line.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

W = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(W / "tools" / "content"))
import convert  # noqa: E402

TABLE = convert.FORMER_IDENTITIES_FILE
BOUNDS = {
    "lower": (
        "D4 (9193261b, 2026-09-28): the first catalogue carrying provenance.identity and the first app storing a "
        "material on a run; no learner row written before it names a file identity. The converter epoch it was "
        "built under (392890bc, 2026-09-16, the last change of convert.py, abc_tools.py and the music21 pin, which "
        "the tool fingerprint keys the cache on) dates every build-converted file such a catalogue can hold on or "
        "after 2026-09-16; the committed PDMX copies it serves keep their own quarry dates, from 2026-09-06."
    ),
    "upper": (
        "the laptop's deployable catalogues before E50a: the main checkout's app/public/content and app/dist/content "
        "(D25: the phone installs what the laptop serves), both written 2026-09-29 22:28 and identical; the latest "
        "dated identity in them is the upper bound, never a future date."
    ),
}


def read_table() -> dict:
    if TABLE.is_file():
        return json.loads(TABLE.read_text(encoding="utf-8"))
    return {"identities": [], "sources": []}


def dated_identities(folder: Path) -> tuple[int, list[dict]]:
    rows = json.loads((folder / "catalog.json").read_text(encoding="utf-8"))
    found: list[dict] = []
    for row in rows:
        identity = (row.get("provenance") or {}).get("identity") or {}
        if identity.get("kind") != "file":
            continue
        raw = (folder / row["file"]).read_bytes()
        entry = convert.dated_form(raw)
        if entry is None:
            continue
        if entry["sha256"] != identity["sha256"]:
            raise SystemExit(f"{row['id']}: the catalogue's identity is not its file's sha256")
        found.append({**entry, "file": row["file"]})
    return len(rows), found


def write_table(table: dict) -> None:
    entries = sorted({e["sha256"]: e for e in table["identities"]}.values(), key=lambda e: (e["file"], e["date"], e["sha256"]))
    dates = sorted({e["date"] for e in entries})
    head = {
        "_comment": (
            "E50a: the historical dated identities music21 wrote, which a learner's stored run, encounter, pruned "
            "run's summary or project may name. convert.former_identities re-proves an entry against the undated "
            "file the converter writes now (putting the entry's date back gives the entry's bytes) and the build "
            "records the proved ones as provenance.formerIdentities. Historical compatibility data, not a rolling "
            "window: generated by docs/prompts/runs/E50a/scripts-former-identities.py, never edited by hand; a dated "
            "identity found outside it (--check) is added deliberately with --add."
        ),
        "bounds": {**BOUNDS, "dates": f"{dates[0]} to {dates[-1]}" if dates else "none"},
        "sources": table.get("sources", []),
    }
    text = json.dumps(head, indent=2, ensure_ascii=False)[:-2] + ',\n  "identities": [\n'
    text += ",\n".join("    " + json.dumps({k: e[k] for k in ("file", "date", "system", "sha256", "undated")}, ensure_ascii=False) for e in entries)
    text += "\n  ]\n}\n"
    TABLE.write_text(text, encoding="utf-8", newline="\n")


def main(argv: list[str]) -> int:
    if argv[:1] == ["--add"] and len(argv) >= 3 and len(argv) % 2 == 1:
        table = read_table()
        known = {e["sha256"] for e in table["identities"]}
        for folder, label in zip(argv[1::2], argv[2::2]):
            rows, found = dated_identities(Path(folder))
            added = [e for e in found if e["sha256"] not in known]
            known |= {e["sha256"] for e in added}
            table["identities"] += added
            table.setdefault("sources", []).append({"catalogue": label, "rows": rows, "dated": len(found), "added": len(added)})
            print(f"{label}: {rows} rows, {len(found)} dated music21 identities, {len(added)} added")
        write_table(table)
        print(f"{TABLE.relative_to(W).as_posix()}: {len(known)} identities")
        return 0
    if argv[:1] == ["--reprove"] and len(argv) == 3:
        import hashlib

        folder, label = Path(argv[1]), argv[2]
        table = read_table()
        failed: list[str] = []
        systems: dict[int, int] = {}
        for entry in table["identities"]:
            path = folder / entry["file"]
            entries = convert._entries(path.read_bytes()) if path.is_file() else None
            at = None
            if entries is not None:
                at = convert._score_at(entries, undated=False)
                if at is not None:
                    text = entries[at][1].decode("utf-8")
                    entries = list(entries)
                    entries[at] = (entries[at][0], convert.without_encoding_date(text).encode("utf-8"))
                else:
                    at = convert._score_at(entries, undated=True)
            proved = [system for system in (0, 3) if at is not None and entries is not None
                      and (rebuilt := convert._redated(entries, at, entry["date"], system)) is not None
                      and hashlib.sha256(rebuilt).hexdigest() == entry["sha256"]]
            if len(proved) != 1 or entries is None:
                failed.append(f"{entry['file']} {entry['date']} {entry['sha256'][:12]}")
                continue
            entry["system"] = proved[0]
            entry["undated"] = hashlib.sha256(convert.pinned_archive(entries)).hexdigest()
            systems[proved[0]] = systems.get(proved[0], 0) + 1
        if failed:
            print(f"STOP: {len(failed)} entries do not re-prove against {folder}; nothing written")
            for line in failed[:50]:
                print(f"   {line}")
            return 1
        table.setdefault("sources", []).append({"reproved": label, "entries": len(table["identities"]),
                                                 "systems": {str(k): v for k, v in sorted(systems.items())}})
        write_table(table)
        print(f"{label}: {len(table['identities'])} entries re-proved; creating systems {systems}")
        return 0
    if argv[:1] == ["--check"] and len(argv) >= 2:
        known = {e["sha256"] for e in read_table()["identities"]}
        outside = 0
        for folder in argv[1:]:
            rows, found = dated_identities(Path(folder))
            missing = [e for e in found if e["sha256"] not in known]
            outside += len(missing)
            print(f"{folder}: {rows} rows, {len(found)} dated music21 identities, {len(missing)} outside the table")
            for e in missing[:50]:
                print(f"   STOP: {e['file']} dated {e['date']}, sha256 {e['sha256']}")
        return 1 if outside else 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
