"""G30's content itemisation (operating-procedure §12): every family row and every generated item whose bytes change.

usage: python docs/prompts/runs/G30/scripts-content_items.py <baseline.json> <catalog-after.json> <out.txt> [<catalog-base.json>]

`baseline.json` is scripts-baseline.py's record of the base (7d9de990): each item of the 43 families with its
printed-finger count, identity, former identities and music digest there. `catalog-after.json` is the catalogue
the edited build wrote. The plan is built again here, on the edited generator, for each item's printed fingers
and music digest now. The contract rows are read at the base (`git show 7d9de990:...`, read only) and now.
"""
from __future__ import annotations

import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / "tools" / "content"))

import family_contracts as FC  # noqa: E402
import generate_exercises as G  # noqa: E402

BASE = "7d9de990"


def fingered(sc) -> int:
    return sum(h["fingered"] for h in FC.physical_facts(sc)["hands"].values())


def main() -> None:
    baseline = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    after_rows = {row["id"]: row for row in json.loads(Path(sys.argv[2]).read_text(encoding="utf-8"))}
    before_table = json.loads(subprocess.run(["git", "show", f"{BASE}:tools/content/family_contracts.json"], cwd=ROOT,
                                             capture_output=True, check=True).stdout.decode("utf-8"))["families"]
    now_table = FC.contracts()
    now = {}
    for sc, entry in G.default_plan(quick=False):
        if entry["id"] in baseline:
            now[entry["id"]] = (fingered(sc), FC.music_digest(sc, entry))
    by_family = defaultdict(list)
    for item_id, one in sorted(baseline.items()):
        by_family[one["family"]].append(item_id)
    lines = ["# G30 content items (generated by scripts-content_items.py; operating-procedure §12)", "",
             "## Family rows (`tools/content/family_contracts.json`, `physical.fingering` and `version`)", ""]
    for family in sorted(by_family):
        b, n = before_table[family], now_table[family]
        reason = b["physical"]["fingering"]["note"]
        lines.append(
            f"- `{family}` ({len(by_family[family])} items): printed {b['physical']['fingering']['printed']!r} -> "
            f"{n['physical']['fingering']['printed']!r}; version {b['version']} -> {n['version']}; "
            f"fingered strikes over the family's items (a chord counts once) {sum(baseline[i]['fingered'] for i in by_family[family])} -> "
            f"{sum(now[i][0] for i in by_family[family])}. Why: the row's own note at the base, \"{reason}\"")
    lines += ["", "## Contract texts corrected or annotated (same file)", ""]
    for family in sorted(now_table):
        for key in ("admission",):
            if before_table[family].get(key) != now_table[family].get(key):
                lines.append(f"- `{family}`.{key}: \"{before_table[family][key]}\" -> \"{now_table[family][key]}\"")
        bt = before_table[family]["roles"].get("transfer")
        nt = now_table[family]["roles"].get("transfer")
        if bt != nt:
            lines.append(f"- `{family}`.roles.transfer: \"{bt}\" -> \"{nt}\"")
        bn = before_table[family]["physical"]["fingering"].get("note")
        nn = now_table[family]["physical"]["fingering"].get("note")
        if bn != nn and before_table[family]["physical"]["fingering"]["printed"] == now_table[family]["physical"]["fingering"]["printed"]:
            lines.append(f"- `{family}`.physical.fingering.note: \"{bn}\" -> \"{nn}\"")
    import importlib.util  # noqa: PLC0415

    spec = importlib.util.spec_from_file_location("edit_consumers", Path(__file__).with_name("scripts-edit_consumers.py"))
    consumers = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(consumers)
    lines += ["", "## Lesson and vocabulary sentences that said a G30 family's fingering is printed", ""]
    for rel, old, new in consumers.EDITS:
        if rel.startswith("content/"):
            text = (ROOT / rel).read_text(encoding="utf-8").replace("\r\n", "\n")
            line = text[:text.index(new)].count("\n") + 1 if new in text else "?"
            lines.append(f"- `{rel}`:{line}: \"{' '.join(old.split())}\" -> \"{' '.join(new.split())}\"")
    lines += ["", "## Generated items (`scores/generated/<id>.mxl` and the catalogue row): one per item", ""]
    moved_digest = []
    for family in sorted(by_family):
        for item_id in by_family[family]:
            one = baseline[item_id]
            row = after_rows[item_id]["provenance"]
            identity = row["identity"]
            formers = row.get("formerGeneratorIdentities") or []
            fingers_now, digest_now = now[item_id]
            if digest_now != one["digest"]:
                moved_digest.append(item_id)
            carried = ", ".join(f"v{f['version']}" for f in formers) or "none"
            lines.append(
                f"- `{item_id}`: fingered strikes {one['fingered']} -> {fingers_now}; notes unchanged "
                f"(music digest {'equal' if digest_now == one['digest'] else 'MOVED'}); identity {family} "
                f"v{one['identity']['version']} -> v{identity['version']}; former identities carried: {carried}")
    lines += ["", f"items: {len(baseline)}; music digest moved: {len(moved_digest)} {moved_digest}"]
    if len(sys.argv) > 4:
        # The whole catalogue, base against now: every field path that differs, counted over the rows,
        # and every review bit that moved (D2's record reads the exact identity, never the continuity).
        from collections import Counter  # noqa: PLC0415

        base_rows = {row["id"]: row for row in json.loads(Path(sys.argv[4]).read_text(encoding="utf-8"))}
        paths: Counter = Counter()

        def walk(x, y, path: str) -> None:
            if isinstance(x, dict) and isinstance(y, dict):
                for key in sorted(set(x) | set(y)):
                    walk(x.get(key), y.get(key), f"{path}.{key}")
            elif x != y:
                paths[path] += 1

        review_moves = []
        for item_id, before in base_rows.items():
            after = after_rows[item_id]
            walk(before, after, "")
            for key in ("review",):
                rv_b = (before.get("provenance") or {}).get(key)
                rv_a = (after.get("provenance") or {}).get(key)
                if rv_b != rv_a:
                    review_moves.append(f"- `{item_id}`: provenance.review {json.dumps(rv_b)} -> {json.dumps(rv_a)} "
                                        "(the decision was recorded on the identity this lane retired, so it is stale)")
        lines += ["", "## The rest of the catalogue (base catalogue against the G30 build, every row)", "",
                  f"- rows: {len(base_rows)} before, {len(after_rows)} after; every field path that differs, with the "
                  "number of rows it differs on:",
                  *(f"  - `{path}`: {count}" for path, count in sorted(paths.items())),
                  *review_moves]
    Path(sys.argv[3]).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(baseline)} items, {len(by_family)} families; digest moved: {len(moved_digest)}")


if __name__ == "__main__":
    main()
